### ISSUE TITLE
[Bug] web-browser插件无法访问网页内容

### ISSUE THREAD

**Issue by zacario-li** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#100]
**Describe the bug**
web-browser插件无法访问网页内容

**To Reproduce**
提问：总结一下这个页面的主要内容“[https://www.nmpa.gov.cn/xxgk/fgwj/gzwj/gzwjylqx/20231206164421158.html”](https://www.nmpa.gov.cn/xxgk/fgwj/gzwj/gzwjylqx/20231206164421158.html%E2%80%9D)
回答：我无法直接访问该网页，因为在尝试获取页面内容时遇到了HTTP 412错误。这通常意味着服务器需要满足某些前提条件才能提供请求的资源，这可能与缺少正确的HTTP头部、Cookies或者是由于服务器配置导致的访问限制。

您可以尝试直接访问该网站，或者提供更多的信息或其他资源，我会尽力帮助您获取所需的内容。如果您有该页面的具体内容或问题，也可以直接告诉我，我会尽量提供帮助。

**Expected behavior**
正确的解读提供的网址内容

**Screenshots**

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser [chrome]
 - Version [116.0.5845.96]

**Comment by Hk-Gosuto** [comment]
这个是该站点的反爬机制导致的，网站第一次访问的时候就是会返回状态码 412 导致无法拿到页面内容
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/ba2d515b-d618-42ca-8965-c3950c8b6497)

**Comment by pacmandoh** [comment]
> 这个是该站点的反爬机制导致的，网站第一次访问的时候就是会返回状态码 412 导致无法拿到页面内容 ![image](https://private-user-images.githubusercontent.com/14031260/290729530-ba2d515b-d618-42ca-8965-c3950c8b6497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MjY5MDYsIm5iZiI6MTcwMjYyNjYwNiwicGF0aCI6Ii8xNDAzMTI2MC8yOTA3Mjk1MzAtYmEyZDUxNWItZDYxOC00MmNhLTg5NjUtYzM5NTBjOGI2NDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA3NTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MWRlYzVjZmZlNzFmMmQ3NTY4NmJiM2FiMmNjMzMzN2FkMDhkN2M0MTViZDY1NmRkNTEyOGI4M2U1MjFhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W5pFAYQUjiyG7DV95xGXSwuZcCBu6CIjgBSNHjVUig0)

带gov后缀的网站，懂得都懂....

**Comment by zacario-li** [comment]
> 这个是该站点的反爬机制导致的，网站第一次访问的时候就是会返回状态码 412 导致无法拿到页面内容 ![image](https://private-user-images.githubusercontent.com/14031260/290729530-ba2d515b-d618-42ca-8965-c3950c8b6497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzIzNDksIm5iZiI6MTcwMjk3MjA0OSwicGF0aCI6Ii8xNDAzMTI2MC8yOTA3Mjk1MzAtYmEyZDUxNWItZDYxOC00MmNhLTg5NjUtYzM5NTBjOGI2NDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3NDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YzgyYjA3OGYyMzlhNTdmOTQ5YjViNGNjMmJjNjViOWNhM2E2NTk1ZmZhMTVlMzIwN2NlZTMyOGI5MDI2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_FD3CfB9g6EkZNiFaJosmIp0jwwZ8K3iSAhoG1U93g)

其实我想表达的意思是，我用浏览器，不需要任何账号，可以直接访问(大概浏览器用了user profiles配置了一些什么，我不太清楚)，那web-brwoser插件是不是也可以继承当前用户的浏览器信息，进行这个页面的请求和内容读取呢？

**Comment by Hk-Gosuto** [comment]
> > 这个是该站点的反爬机制导致的，网站第一次访问的时候就是会返回状态码 412 导致无法拿到页面内容 ![image](https://private-user-images.githubusercontent.com/14031260/290729530-ba2d515b-d618-42ca-8965-c3950c8b6497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzIzNDksIm5iZiI6MTcwMjk3MjA0OSwicGF0aCI6Ii8xNDAzMTI2MC8yOTA3Mjk1MzAtYmEyZDUxNWItZDYxOC00MmNhLTg5NjUtYzM5NTBjOGI2NDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3NDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YzgyYjA3OGYyMzlhNTdmOTQ5YjViNGNjMmJjNjViOWNhM2E2NTk1ZmZhMTVlMzIwN2NlZTMyOGI5MDI2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_FD3CfB9g6EkZNiFaJosmIp0jwwZ8K3iSAhoG1U93g)
> 
> 其实我想表达的意思是，我用浏览器，不需要任何账号，可以直接访问(大概浏览器用了user profiles配置了一些什么，我不太清楚)，那web-brwoser插件是不是也可以继承当前用户的浏览器信息，进行这个页面的请求和内容读取呢？

[webbrowser](https://github.com/langchain-ai/langchainjs/blob/90b8e70/langchain/src/tools/webbrowser.ts) 插件是 langchainjs 官方插件，如果对该插件的实现方式有疑问可以直接提 issues 到 [langchainjs](https://github.com/langchain-ai/langchainjs) 项目。
