### ISSUE TITLE
[Bug] gpt-4-1106-preview 模型关闭插件后使用报错

### ISSUE THREAD

**Issue by liaokongVFX** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#103]
**Describe the bug**
更新了v2.9.13版本后发现，当我关闭插件功能使用 gpt-4-1106-preview 模型时会报错 `"The server had an error while processing your request. (request id: 20231215124044212391379twXuW1QT) (request id: 202312152****) (request id: 202312*****)"` 的错误。而打开插件功能， gpt-4-1106-preview 模型就可以正常使用。目前只发现这一种模型会有这个问题。

**Screenshots**
关闭插件功能：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/13622183/52ee9635-cf81-498e-9aba-0385257132fc)
打开插件功能：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/13622183/4c0f73d9-711a-4a20-94e2-ec6cf04fb2e7)

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
试一下这个版本的镜像：`gosuto/chatgpt-next-web-langchain:nightly`

**Comment by liaokongVFX** [comment]
试了下`gosuto/chatgpt-next-web-langchain:nightly`镜像，关了插件使用gpt-4-1106-preview 模型，变成报404的错了
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/13622183/12ed1488-7013-4047-aa4f-64dbc251549a)
我看请求被重定向到了这个地址
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/13622183/bb7baa99-9d1c-4476-a939-64be389fad8b)

**Comment by Hk-Gosuto** [comment]
是否配置了自定义接口？

**Comment by liaokongVFX** [comment]
没有哦，而且还是只有 gpt-4-1106-preview 模型关了插件会有这种问题，其他模型都没出现这个问题，之前用的 v2.9.12 版本也没有这个问题。

**Comment by Hk-Gosuto** [comment]
我使用以下命令运行了容器，并且在 InPrivate 窗口中进行了验证，没有遇到这个 404 的错误：
```bash
docker run -it --rm -p 3000:3000 gosuto/chatgpt-next-web-langchain:nightly
```
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/c9b8176a-d02a-44e5-938c-2fc104d4a154)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/3da65f44-8e6f-4fbf-9c61-78d58e53c5d3)
