### ISSUE TITLE
[Bug] Cloudflare cdn 会导致插件显示出错，将所有报文输出

### ISSUE THREAD

**Issue by kflyfly** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#105]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
插件版，一但开启插件功能，就会出现下面的回复，导致无法使用：
````
<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>404: This page could not be found</title><meta name="next-head-count" content="3"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js"></script><script src="/_next/static/chunks/webpack-816dd4f2dcd42389.js" defer=""></script><script src="/_next/static/chunks/framework-4498e84bb0ba1830.js" defer=""></script><script src="/_next/static/chunks/main-42643f50d61246ff.js" defer=""></script><script src="/_next/static/chunks/pages/_app-0fe44225c17aa1f2.js" defer=""></script><script src="/_next/static/chunks/pages/_error-a73f64b4ecbfa014.js" defer=""></script><script src="/_next/static/7Vasmhw25HziFz0kOlbVk/_buildManifest.js" defer=""></script><script src="/_next/static/7Vasmhw25HziFz0kOlbVk/_ssgManifest.js" defer=""></script></head><body><div id="__next"><div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="line-height:48px"><style>body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}</style><h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">404</h1><div style="display:inline-block"><h2 style="font-size:14px;font-weight:400;line-height:28px">This page could not be found<!-- -->.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":404}},"page":"/_error","query":{},"buildId":"7Vasmhw25HziFz0kOlbVk","nextExport":true,"isFallback":false,"gip":true,"scriptLoader":[]}</script></body></html>
````
**如何复现**

- 如果关闭Cloudfalre CDN 直接访问网站，插件可以正常使用。
- 如果在有Cloudflare的 CDN情况下，关闭所有插件功能，可以正常使用
- 复现：浏览器隐身打开，不需要输入密码，直接在对话框输入文字，只要有任意插件开启，即可出现此问题

**截图**
![Weixin Image_20231219194634](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/63854859/a5417b6c-51d7-4ee3-bcb3-f7d9f8a64f26)
**一些必要的信息**
 - 系统：[Windwos，iPhone, android 的浏览器均出现]
 - 浏览器： [chrome, safari]
 - 版本： [docker 版本最新版，通过回滚到一个月以前的或者2个月以前的版本，问题依旧存在。]
 - 部署方式：[docker 部署]

**Comment by Hk-Gosuto** [comment]
docker 部署后又套了一层 Cloudflare cdn？

**Comment by kflyfly** [comment]
架构：
docker--主机--CloudFlare--用户
目前：
docker--主机--用户：不受影响，插件功能正常
docker--主机--CloudFlare--用户，任意一个插件功能开启就会报错。

我猜测是Cloudflare的问题，但不知道怎么更改和修复错误。

**Comment by Hk-Gosuto** [comment]
我看 cf 报的是一个 404，怀疑是插件的相关接口没有正确进行代理，既然你是 docker 部署，需要确认下 `/api/langchain/tool/agent/nodejs` 这个路由是否被正确转发。
也可以观察一下 nginx 那边的日志，确认下在 404 的时候请求的是什么路由，是不是需要在 cf 那边做一些什么额外的配置。

**Comment by kflyfly** [comment]
> 我看 cf 报的是一个 404，怀疑是插件的相关接口没有正确进行代理，既然你是 docker 部署，需要确认下 `/api/langchain/tool/agent/nodejs` 这个路由是否被正确转发。 也可以观察一下 nginx 那边的日志，确认下在 404 的时候请求的是什么路由，是不是需要在 cf 那边做一些什么额外的配置。

谢谢，查询了日志，日志显示没有出错。/api/langchain/tool/agent/nodejs 可以被主机的端口反代正常处理。目前能确定是cloudflare 的proxy问题。已经去他们community 发帖反馈了。看看能不能解决。

**Comment by kflyfly** [comment]
排查出问题了，确实是cloudflare的问题。
问题原因：
docker 更新了版本。
但cloudflare 依旧使用的旧的网页缓存，由于旧网页版本缓存（如v2.9）和新版本（v2.10）的基本逻辑架构一样，但是插件功能可能不一样，所以会导致插件乱码。
解决办法： nginx 增加设置缓存，或者更改网页界面，触发Cloudflare 识别到网页内容的改变，更新缓存
