### ISSUE TITLE
[Feature] 考虑支持gpt-4-all模型的文件上传吗

### ISSUE THREAD

**Issue by Feliks151450** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#109]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
gpt-4-all这个模型支持画图，联网搜索，分析URL，分析文件/图片等，但是在next web里没有按钮，希望可以有个上传图片/文件的按钮

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Hk-Gosuto** [comment]
切换到 `gpt-4-vision-preview` 模型就可以上传图片了，目前文件分析只有 `PDF浏览器` 插件，需要提供 pdf 文件的 url 来调用。

**Comment by Hk-Gosuto** [comment]
https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/issues/77
