### ISSUE TITLE
gosuto/ddg-api

### ISSUE THREAD

**Issue by guyuexue** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#11]
docker run -p 8000:8000 gosuto/ddg-api
这个docker镜像好像没开放,需要登录才能下载
`docker: Error response from daemon: pull access denied for gosuto/ddg-api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

**Comment by Hk-Gosuto** [comment]
新版本已经不需要额外部署 `ddg-api` 这个项目了，在不进行额外配置的情况下默认使用的就是 `DuckDuckGo` 搜索引擎。
详情请查看 [ReadMe](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain?tab=readme-ov-file#%E5%BC%80%E5%8F%91%E8%AE%A1%E5%88%92)
