### ISSUE TITLE
[Feature] - 支持自定义 DALL-E 插件模型版本

### ISSUE THREAD

**Issue by happychos** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#110]
- [ x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
3.5keyDALL-E插件无响应

**如何复现**
官方直通3.5KEY之前一直正常使用，今天无法生成图片了，cloudflare R2 中也没有图片，但4.0Key可以正常使用，估计可能和官方调整api权限有关，普号没有dalle-3权限了，可否设置如果是3.5key自动调用dalle-2。
**截图**

**一些必要的信息**
 - 系统： windows 10
 - 浏览器： chrome
 - 版本： v2.9.13
 - 部署方式： vercel及cloudflare

**Comment by snakeying** [comment]
openai在中国时间12月20日暂停了3.5调用DALL-E的权限，重开时间另行通知，跟nextweb没有关系

**Comment by Hk-Gosuto** [comment]
配置环境变量：`DALLE_MODEL=dall-e-2`
