### ISSUE TITLE
Plugins not working with Azure OpenAi API[Bug] 

### ISSUE THREAD

**Issue by crypticatul** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#115]
**Describe the bug**
When I enable the plugins while using Azure API, it just doesn't respond, while it works normally if plugins are disabled.

**To Reproduce**
Enable Plugins from the icon 
1. Type any query/message and click on SEND.
2. No response from agent.

**Expected behavior**
It should respond. Basically plugins not working with Azure OpenAI API.

**Screenshots**
Here is the message from the Console tab in Inspect Element.

[ToolAgent] start
page-3ffa08eb22c1c457.js:1 [Request] openai payload: Object
baseUrl
: 
"/api/openai/"
frequency_penalty
: 
0
maxIterations
: 
10
messages
: 
(12) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
model
: 
"gpt-4-1106-preview"
presence_penalty
: 
0
returnIntermediateSteps
: 
true
stream
: 
true
temperature
: 
0.3
top_p
: 
1
useTools
: 
(6) ['web-search', 'calculator', 'web-browser', 'WikipediaQueryRun', 'dalle_3_image_generator', 'arxiv']
[[Prototype]]
: 
Object

**Deployment**
- [ ] Docker
- [ x] Netlify
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows 11]
 - Browser [Brave]
 - Version [Latest]

**Additional Logs**
It seems it is taking BASE-URL as OpenAI's Base url, I tried changing the openAi base url to Azure base url in the Constant.ts still its not working.

**Comment by Hk-Gosuto** [comment]
Plugins such as dall-e that require openai keys do not support azure for the time being.
