### ISSUE TITLE
[建议] 成为独立项目

### ISSUE THREAD

**Issue by snakeying** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#116]
鉴于next web项目已经被收购，是否考虑将这个项目独立出来呢？刚接手不到一周加个gemini就已经出了问题，还是很简单就能解决的。。像这样

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3615

Yda也不再负责了

**Comment by Hk-Gosuto** [comment]
ChatGPT-Next-Web 目前看还是基于 MIT 开源协议的，后续如果 ChatGPT-Next-Web 项目出现商业行为的话则会考虑将本项目独立。
