### ISSUE TITLE
[Bug] Plugins are not working on locales other than 'en' and 'cn'

### ISSUE THREAD

**Issue by magicnov** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#12]
**Describe the bug**
If you change app language for example to Russian, plugins will not work.

**To Reproduce**
Change the language of the site to any other than English or Chinese

**Screenshots**
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/54899018/3bffacbf-cf9c-420b-a024-194ce07b6392)

**Comment by Hk-Gosuto** [comment]
Thank you for identifying the issue. This issue has been resolved in the latest version. Please update your code to the latest version.
