### ISSUE TITLE
[Bug] [GoogleCustomSearch]中的环境变量：GOOGLE_API_KEY 和Gemini-Pro 模型配置密钥 GOOGLE_API_KEY这两者变量名称相同？

### ISSUE THREAD

**Issue by ccinoo** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#121]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。

[GoogleCustomSearch]中的环境变量：GOOGLE_API_KEY 和Gemini-Pro 模型配置密钥 GOOGLE_API_KEY这两者变量名称相同？

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/30647119/b8a06b97-4a24-49af-8855-07f69f0f4dec)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/30647119/e92d4cc4-887f-4ab1-b8ae-f62e4388c36d)

**一些必要的信息**
 - 系统：[windows 10]
 - 浏览器： [chrome]
 - 版本： [2.9.13]
 - 部署方式：[vercel]

**Comment by Hk-Gosuto** [comment]
是相同的，同一个项目创建的密钥是同一个。

**Comment by ccinoo** [comment]
> 是相同的，同一个项目创建的密钥是同一个。

那是我理解错了，我以为是GOOGLE GEMINI API KEY了。

**Comment by Hk-Gosuto** [comment]
> > 是相同的，同一个项目创建的密钥是同一个。
> 
> 那是我理解错了，我以为是GOOGLE GEMINI API KEY了。

Gemini 的 key 和这个可以共用，如果你已经有了 Gemini 的 key 那额外再配置一个 `GOOGLE_CSE_ID` 就可以用这个插件了。
