### ISSUE TITLE
[Bug] arxiv 搜索不到内容

### ISSUE THREAD

**Issue by jorejia** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#122]
**Describe the bug**
在1c845c部署的，arxiv 的回复一律是"很抱歉，根据ArXiv数据库的结果，没有找到XXXX请尝试使用其他关键词或搜索引擎进行进一步的查询。"，已排除 openai key 的问题

**Comment by Hk-Gosuto** [comment]
接口有速率限制：https://info.arxiv.org/help/api/tou.html
