### ISSUE TITLE
[Feature] 兼容通过代理接口转发的老版本 openai 接口数据结构

### ISSUE THREAD

**Issue by jorejia** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#123]
**Describe the bug**
我的环境是用one api进行分流，将gpt-3.5-turbo分流到对接的web模拟的api，其他的仍然是openai的api_key，走真实api_key是正常的，走模拟的key会报以下错误
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/9987064/bbc07122-280a-4478-8d6b-0deefbab6818)
我用同样的环境在Next-web原项目上测试，并没有报错，能正常使用

**Comment by Hk-Gosuto** [comment]
非 openai 官方 api 接口不支持函数调用。

**Comment by jorejia** [comment]
> 非 openai 官方 api 接口不支持函数调用。

我知道这点，在使用非官方接口是关闭了插件使用的

**Comment by Hk-Gosuto** [comment]
为了兼容视觉模型，统一修改了 message 的对象格式，检查一下转发的接口是否不支持该结构的 json 对象：
```json
{
    "messages": [
        {
            "role": "system",
            "content": [
                {
                    "type": "text",
                    "text": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2023/12/26 16:44:19\nLatex inline: $x^2$ \nLatex block: $$e=mc^2$$\n\n"
                }
            ]
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "return 1"
                }
            ]
        }
    ]
}
```

**Comment by jorejia** [comment]
应该是这个原因，回退到 v2.9.12 则没有问题了，个人觉得相比于获取难度较高的 gpt4 key，还是gpt3.5第三方接口更加有用，是否可以考虑单独做一个支持的选项，类似对Gemini-Pro的支持
