### ISSUE TITLE
[Feature] 添加对wolframalpha的支持

### ISSUE THREAD

**Issue by pengtb** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#129]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
可以为一些专业问题提供解答。

**你想要什么功能或者有什么建议？**
添加一个新的可以搜索wolframalpha的插件，或者整合到现有的搜索插件中，从而可以搜索wolframalpha，并得到一些专业解答。
大概就像[这样](https://writings.stephenwolfram.com/2023/03/chatgpt-gets-its-wolfram-superpowers/)

**有没有可以参考的同类竞品？**
如[chuanhuchatgpt](https://github.com/GaiZhenbiao/ChuanhuChatGPT)

**其他信息**

**Comment by Hansonwong47** [comment]
是的，可以添加wolfram， API Key自己写

**Comment by Hansonwong47** [comment]
API Key就在环境变量里面设定

**Comment by Hansonwong47** [comment]
Hk-Gosuto你認為怎樣呢?

**Comment by Hk-Gosuto** [comment]
langchain 包含了这个服务的官方插件，后面我会引入到当前项目中。

**Comment by Hansonwong47** [comment]
> langchain 包含了这个服务的官方插件，后面我会引入到当前项目中。

希望快点完成，这样会加强GPT的数学能力

**Comment by Hansonwong47** [comment]
@Hk-Gosuto 大概几时可以增加wolfram插件
