### ISSUE TITLE
[Bug] 发现个问题

### ISSUE THREAD

**Issue by qingyuan0o0** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#13]
**描述问题**
单独部署docker的时候没有问题，一切正常
但是部署cloudflare pages出问题了

**如何复现**
你部署一次pages就可以看到问题了
部署成cloudflare pages的时候发现问题：
1.首先设置next.config.mjs中API_URL不起作用
'''    const apiUrl = process.env.API_URL;
    if (apiUrl) {
      console.log("[Next] using api url ", apiUrl);
      ret.push({
        source: "/api/:path*",
        destination: `${apiUrl}/:path*`,
      });
    }'''
需要单独再填写一次API_URL和key在设置中
2.部署在CF中，搜索功能返回404
**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
不启用搜索功能的时候，可以正常交互，而启用功能后，发起会话返回内容如下
<html> <head><title>404 Not Found</title></head> <body> <center><h1>404 Not Found</h1></center> <hr><center>nginx</center> </body> </html>      
看了下是https://cf的地址/api/langchain/tool/agent 这个页面不存在
**一些必要的信息**
 - 系统：[windows 10]
 - 浏览器： [chrome]
 - 版本： [2.9.3]
 - 部署方式：[cloudflare page next]

**Comment by Hk-Gosuto** [comment]
我使用当前 main 分支最新代码部署了一个 Cloudflare Pages 应用，地址如下：
https://665eb31c.chatgpt-next-web-langchain-evu.pages.dev

进行了以下几条路径的验证，插件功能正常：
- 在环境变量中配置 BASE_URL 和 OPENAI_API_KEY 
- 在程序设置中配置 接口地址 和API KEY

请尝试拉取最新代码后部署，如还有问题请提供该问题的更多细节。

**Comment by n3ap** [comment]
搜索能默认关闭吗，想用再开，有的第三方代理不支持用，得关一下。

**Comment by qingyuan0o0** [comment]
我部署在本地，好像没有每次都去搜索，有的时候是直接api回复了，没有经过搜索，但是开关我并没有关闭，用川虎好像开关打开必然搜索！

**Comment by Hk-Gosuto** [comment]
> 搜索能默认关闭吗，想用再开，有的第三方代理不支持用，得关一下。

最新版本可以在插件列表中单独关闭插件，也可以在聊天窗口开关整个插件功能。

**Comment by qingyuan0o0** [comment]
> 我使用当前 main 分支最新代码部署了一个 Cloudflare Pages 应用，地址如下： https://665eb31c.chatgpt-next-web-langchain-evu.pages.dev
> 
> 进行了以下几条路径的验证，插件功能正常：
> 
> * 在环境变量中配置 BASE_URL 和 OPENAI_API_KEY
> * 在程序设置中配置 接口地址 和API KEY
> 
> 请尝试拉取最新代码后部署，如还有问题请提供该问题的更多细节。

经过测试，你的版本为2.9.5最新版本，我之前fork的版本为2.9.3，进行同步后依旧是2.9.3，不晓得是否需要删除重构，你的确实没有碰到这类的异常，请问你后台使用的是什么方式搜索的ddg吗？

**Comment by supercyx3** [comment]
大佬有交流群吗，申请加入

**Comment by Hk-Gosuto** [comment]
> > 我使用当前 main 分支最新代码部署了一个 Cloudflare Pages 应用，地址如下： https://665eb31c.chatgpt-next-web-langchain-evu.pages.dev
> > 进行了以下几条路径的验证，插件功能正常：
> > 
> > * 在环境变量中配置 BASE_URL 和 OPENAI_API_KEY
> > * 在程序设置中配置 接口地址 和API KEY
> > 
> > 请尝试拉取最新代码后部署，如还有问题请提供该问题的更多细节。
> 
> 经过测试，删除重构后确实为2.9.5的版本，但是搜索功能依旧异常404，测试了main分支，并且设置了BASE_URL:[https://api.chatanywhere.cn,预设了Key，但是并不生效，能否请教构建参数是否使用的是否是教程提供的？](https://api.chatanywhere.cn,%E9%A2%84%E8%AE%BE%E4%BA%86Key%EF%BC%8C%E4%BD%86%E6%98%AF%E5%B9%B6%E4%B8%8D%E7%94%9F%E6%95%88%EF%BC%8C%E8%83%BD%E5%90%A6%E8%AF%B7%E6%95%99%E6%9E%84%E5%BB%BA%E5%8F%82%E6%95%B0%E6%98%AF%E5%90%A6%E4%BD%BF%E7%94%A8%E7%9A%84%E6%98%AF%E5%90%A6%E6%98%AF%E6%95%99%E7%A8%8B%E6%8F%90%E4%BE%9B%E7%9A%84%EF%BC%9F) 尝试过教程提供的那串构建参数构建失败，替换成官方建议的构建代码，不知道是不是问题出在这里？ https://23f0f8f8.chatgpt-next-web-langchain.pages.dev/ 测试这个是异常的，不输入密码而使用url以及key，搜索功能404 https://f55f0c37.chatgpt-next-web-langchain.pages.dev/ 测试这个是正常，但是默认url、key、code为空，搜索功能正常，所以问题不知道在哪里。。 还发现了一个问题，web_get功能在cf失效了显示如下： duckduckgo_search:国庆期间庐山景区附近酒店近3年的平均价格 web-browser:https://hotels.ctrip.com/hotel/lushan2#ctm_ref=hod_hp_sb_lst 很抱歉，由于技术问题，我无法直接为您提供庐山景区附近酒店近3年的平均价格。您可以尝试通过旅行网站如携程、Booking.com等进行搜索和比较不同时间段的酒店价格，以获取更准确的信息。另外，您也可以联系当地的旅行社或酒店进行咨询，他们可以提供更详细的信息和帮助您安排行程。

我是参考官方该文档进行部署的 [cloudflare-pages](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/cloudflare-pages-en.md) 
我检查了一下你异常的地址，在 `/api/openai/v1/chat/completions` 路由请求时同样出现了 404 的问题，怀疑是你部署的问题，建议按照我上面提供的文档地址重新部署。
关于 web-browser 插件的问题，这个插件是基于嵌入模型+gpt总结来进行网页检索的，并不太稳定，你这种问题最好的方式是实现一个酒店住宿的检索插件。

**Comment by Hk-Gosuto** [comment]
> 大佬有交流群吗，申请加入

现在这个项目用户量不太多，就没有建立交流群，如果有问题或者建议可以先提 issues。
