### ISSUE TITLE
[Bug] Google Gemini 模式没有进行流式数据返回

### ISSUE THREAD

**Issue by h1xy** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#131]
昨天编译的版本，如果env文件中没有填google_API_key并请求gemini-pro模型，会提示没有google_API_key。

但是我是要通过one-api提供gemini的渠道的，能否做个判断，如果没有填google_API_key，也支持通过openai接口来请求gemini。

第二个问题是看项目说明文档说支持gemini流式传输，但是实测不支持，回答全部生成后一起出来。

**Comment by Hk-Gosuto** [comment]
第一个问题按我的理解，是否将 `GOOGLE_API_KEY` 配置为 `OPENAI_API_KEY` 相同的值就可以解决？
第二个问题确实是个 bug，迁移上游项目时的接口方法是同步的。

**Comment by Hk-Gosuto** [comment]
gemini 模型流式传输问题修复了，兼容的问题比较麻烦，按现有设计不太好做兼容，可以考虑自定义个模型名，并在 one-api 那边对模型名进行重写。
