### ISSUE TITLE
[Feature] Dall·E 插件的完整参数

### ISSUE THREAD

**Issue by d0j1a1701** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#132]
https://platform.openai.com/docs/api-reference/images/create

注意到 Dall·E 的 API 包括 `style` 参数，可以调整图片的风格（超现实/写实），目前没有传这个参数，导致无法让模型画出写实风格的图片。

同时模型的 `quality` 参数直接传进了 Prompt，我十分怀疑这是否有效，因为 API 中有单独的一个 `quality` 参数。

**Comment by Hk-Gosuto** [comment]
插件目前只公开了 `prompt` 和 `size` 两个参数
计划将 `quality` 和 `style ` 也提供给模型调用

**Comment by d0j1a1701** [comment]
我已经做了一个简单的实现，参见 https://github.com/d0j1a1701/ChatGPT-Next-Web-LangChain/blob/main/app/api/langchain-tools/dalle_image_generator.ts，但因为我还对代码做了其它改动，所以就不发 PR 了
