### ISSUE TITLE
[Bug] Gemini 模型鉴权异常

### ISSUE THREAD

**Issue by happychos** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#136]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用的google_api_key,其他模型用one-api,Gemini-Pro改为流式响应更新后不可用，同样的参数回滚到上一个版本就没有问题，

**如何复现**
更新后发现gemini-pro不可用，回滚后可用。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：vercel

**Comment by MuRo-J** [comment]
+1,测试接口
```curl
 curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"say hello~"}]}]}' \
  -X POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:streamGenerateContent\?key\=key
 
```
可用,部署后没用

**Comment by Hk-Gosuto** [comment]
是否配置了 `GOOGLE_BASE_URL` 对应原版参数为 `GOOGLE_URL`
原版需要配置为 `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:streamGenerateContent`
本项目配置为 `https://generativelanguage.googleapis.com`
此处存在差异，检查一下配置是否正确

**Comment by MuRo-J** [comment]
谢谢作者,辛苦您啦
我确认了下Server的log显示
```
[Base Url] https://generativelanguage.googleapis.com
[Server Config] using 1 of 1 api key
```
然后 网站的log显示
```
[30/Dec/2023:00:31:30 +0800] ＂POST /api/google/v1/models/gemini-pro:streamGenerateContent HTTP/2.0＂ 401 40 
```
有可能和上面的不是同一个问题,然后 key我curl测试是可用的,我再看下

**Comment by ychappyboy** [comment]
> 是否配置了 `GOOGLE_BASE_URL` 对应原版参数为 `GOOGLE_URL`
> 原版需要配置为 `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:streamGenerateContent`
> 本项目配置为 `https://generativelanguage.googleapis.com`
> 此处存在差异，检查一下配置是否正确

我试了加了GOOGLE_BASE_URL还是不行，但是去掉CODE参数就一切正常了

**Comment by Hk-Gosuto** [comment]
> [Base Url] https://generativelanguage.googleapis.com

我试了一下 确实是 gemini 模型鉴权的问题，该问题很快会被修复
