### ISSUE TITLE
gemini-pro输出重复内容

### ISSUE THREAD

**Issue by happychos** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#138]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
vercel更新到最新gemini-pro出现输出重复的问题

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
![Screenshot_2023-12-30-20-29-22-543_com android chrome](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/139939316/4e3af8d1-68e1-4268-ba42-7fca87ae201d)

**一些必要的信息**
 - 系统：[android 11 / ios 16]
 - 浏览器： [chrome]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[vercel部署]

**Comment by MuRo-J** [comment]
上游已知问题,貌似得等待下Google能有 text-stream
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3703

**Comment by MuRo-J** [comment]
上游大佬兼容了这个问题,同时还修复了一个 Gemini的安全策略配置问题
[fredliang44](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commits?author=fredliang44)

**Comment by Hk-Gosuto** [comment]
已合并上游仓库代码

**Comment by MuRo-J** [comment]
> 已合并上游仓库代码

辛苦啦!我测试了下 现在回复正常,而且不重复啦~

**Comment by MuRo-J** [comment]
> > 已合并上游仓库代码
> 
> 辛苦啦!我测试了下 现在回复正常,而且不重复啦~

现在结果有些诡异,重复倒是不一定,但是非常诡异
![CleanShot 2024-01-02 at 13 15 22](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/64354330/cec3d9f0-358d-43b5-9269-032a75172073)

会调用两遍不同的接口,短句没有测试出来,添麻烦了

[02/Jan/2024:13:14:29 +0800] ＂POST /api/google/v1/models/gemini-pro:streamGenerateContent HTTP/2.0＂ 
02/Jan/2024:13:14:32 +0800] ＂POST /api/google/v1/models/gemini-pro:generateContent HTTP/2.0＂ 200 1193

**Comment by Hk-Gosuto** [comment]
> > > 已合并上游仓库代码
> > 
> > 
> > 辛苦啦!我测试了下 现在回复正常,而且不重复啦~
> 
> 现在结果有些诡异,重复倒是不一定,但是非常诡异 ![CleanShot 2024-01-02 at 13 15 22](https://private-user-images.githubusercontent.com/64354330/293630350-cec3d9f0-358d-43b5-9269-032a75172073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzM5MzUsIm5iZiI6MTcwNDE3MzYzNSwicGF0aCI6Ii82NDM1NDMzMC8yOTM2MzAzNTAtY2VjM2Q5ZjAtMzU4ZC00M2I1LTkyNjktMDMyYTc1MTcyMDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA1MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjI1NDFmM2Q5OWE2NDcwNTU4ZjBkNDVmZmM3Y2M1ZTg2OWIzMTY4ZDI4NGJhYjZjN2FkNzY5MmM1YzFkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X-cSnT0UmZM3-yTKzw-dRUAILyrjX0j5-Fz6rNqWLBE)
> 
> 会调用两遍不同的接口,短句没有测试出来,添麻烦了
> 
> [02/Jan/2024:13:14:29 +0800] ＂POST /api/google/v1/models/gemini-pro:streamGenerateContent HTTP/2.0＂ 02/Jan/2024:13:14:32 +0800] ＂POST /api/google/v1/models/gemini-pro:generateContent HTTP/2.0＂ 200 1193

/api/google/v1beta/models/gemini-pro:generateContent 接口调用是用来总结对话内容摘要的

**Comment by MuRo-J** [comment]
> > > > 已合并上游仓库代码
> > > 
> > > 
> > > 辛苦啦!我测试了下 现在回复正常,而且不重复啦~
> > 
> > 
> > 现在结果有些诡异,重复倒是不一定,但是非常诡异 ![CleanShot 2024-01-02 at 13 15 22](https://private-user-images.githubusercontent.com/64354330/293630350-cec3d9f0-358d-43b5-9269-032a75172073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzM5MzUsIm5iZiI6MTcwNDE3MzYzNSwicGF0aCI6Ii82NDM1NDMzMC8yOTM2MzAzNTAtY2VjM2Q5ZjAtMzU4ZC00M2I1LTkyNjktMDMyYTc1MTcyMDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA1MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjI1NDFmM2Q5OWE2NDcwNTU4ZjBkNDVmZmM3Y2M1ZTg2OWIzMTY4ZDI4NGJhYjZjN2FkNzY5MmM1YzFkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X-cSnT0UmZM3-yTKzw-dRUAILyrjX0j5-Fz6rNqWLBE)
> > 会调用两遍不同的接口,短句没有测试出来,添麻烦了
> > [02/Jan/2024:13:14:29 +0800] ＂POST /api/google/v1/models/gemini-pro:streamGenerateContent HTTP/2.0＂ 02/Jan/2024:13:14:32 +0800] ＂POST /api/google/v1/models/gemini-pro:generateContent HTTP/2.0＂ 200 1193
> 
> /api/google/v1beta/models/gemini-pro:generateContent 接口调用是用来总结对话内容摘要的

非常感谢您耐心回复,我再次拉了一遍最新仓库,结果正常啦
![CleanShot 2024-01-03 at 12 12 41](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/64354330/9efe9da5-a011-4434-93f6-9c1479d38fbf)
