### ISSUE TITLE
[Bug] 插件结果强制返回英文

### ISSUE THREAD

**Issue by d0j1a1701** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#139]
无论你使用什么语言询问，调用插件后结果都会变为英文。

复现方法：

使用 `gpt-4-1106-preview` 模型，激活 `Wolfram Alpha` 插件，询问「分析函数 $y=cos x + 2sin x$」

模型返回内容：

The function $y = \cos(x) + 2\sin(x)$ has been analyzed, and here are the key points:

**Alternate Form:**
The function can be expressed in an alternate form using complex exponentials:
$$ y = \left(\frac{1}{2} + i\right) e^{-ix} + \left(\frac{1}{2} - i\right) e^{ix} $$

**Roots:**
The roots of the equation $\cos(x) + 2\sin(x) = 0$ are given by:
$$ x = \pi n - \tan^{-1}\left(\frac{1}{2}\right), \text{ where } n \in \mathbb{Z} $$

**Properties as a Real Function:**
- **Domain:** The function is defined for all real numbers ($\mathbb{R}$).
- **Range:** The range of the function is between the maximum and minimum values it can take, which are related to the expression $2 \sin(2 \tan^{-1}(1/2 (-1 - \sqrt{5}))) + \cos(2 \tan^{-1}(1/2 + \sqrt{5}/2))$ for the minimum and $2 \sin(2 \tan^{-1}(1/2 (\sqrt{5} - 1))) + \cos(2 \tan^{-1}(1/2 (\sqrt{5} - 1)))$ for the maximum.
- **Periodicity:** The function is periodic with a period of $2\pi$.

**Derivatives:**
- The first derivative with respect to $x$ is $2\cos(x) - \sin(x)$.
- The derivative with respect to $y$ is $0$, as $y$ is a function of $x$ and not vice versa.

**Implicit Derivatives:**
- The implicit derivative $\frac{dx}{dy}$ is $\frac{1}{2\cos(x) - \sin(x)}$.
- The implicit derivative $\frac{dy}{dx}$ is $2\cos(x) - \sin(x)$.

**Extrema:**
- **Global Maxima:** The maximum value of the function is $\sqrt{5}$, which occurs at $x = 2\pi n + 2\tan^{-1}\left(\frac{2}{1 + \sqrt{5}}\right)$ for any integer $n$.
- **Global Minima:** The minimum value of the function is $-\sqrt{5}$, which occurs at $x = 2\pi n - 2\tan^{-1}\left(\frac{2}{\sqrt{5} - 1}\right)$ for any integer $n$.

Here are the plots for the function over different intervals:

- Plot over the interval $[-2\pi, 2\pi]$:
  ![Plot over -2pi to 2pi](https://www6b3.wolframalpha.com/Calculate/MSP/MSP745119i967893b0eai8300004b17b4615ie37g44?MSPStoreType=image/png&s=18)

- Plot over the interval $[-8\pi, 8\pi]$:
  ![Plot over -8pi to 8pi](https://www6b3.wolframalpha.com/Calculate/MSP/MSP745219i967893b0eai83000054bi41731c16655e?MSPStoreType=image/png&s=18)

For more detailed analysis, you can visit the Wolfram|Alpha website with the provided [link](https://www6b3.wolframalpha.com/input?i=analyze+the+function+y%3Dcos%28x%29%2B2sin%28x%29).

**Comment by Hk-Gosuto** [comment]
模型问题非程序bug
