### ISSUE TITLE
[Bug] 模型会尝试使用 DallE 而不是 Wolfram Alpha 绘制函数图像

### ISSUE THREAD

**Issue by d0j1a1701** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#140]
复现方式：同时激活 DallE 和 Wolfram Alpha 插件，使用 `gpt-4-1106-preview` 模型，询问「画一下函数 $y=sin x + cos x$ 的图像」

**Comment by d0j1a1701** [comment]
感觉修改一下 DallE 插件的描述即可

**Comment by Hk-Gosuto** [comment]
更新到最新，并且在 prompt 中强调一下使用哪个插件
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/b639ccf4-33bf-4435-8310-620670145486)
