### ISSUE TITLE
[Feature] 是否考虑给 gpt-4-vision-preview 用上搜索

### ISSUE THREAD

**Issue by kaixindeken** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#145]

**Comment by Hk-Gosuto** [comment]
目前支持函数调用的模型只有下面几个，后面官方支持后会进行适配：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/7f08f630-ee96-4568-879c-c51909cdbd56)

**Comment by kaixindeken** [comment]
好嘞
