### ISSUE TITLE
[Bug] 自定义模型 Post请求会带上不应该出现的参数

### ISSUE THREAD

**Issue by Harry-zklcdc** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#147]
**Describe the bug**
通过 `oneAPI` 转发**自定义模型**的 OpenAI 格式接口，会出现请求地址不该带有的参数

**To Reproduce**
1. 设置**自定义模型** `mixtral-8x7b`、`ChatGLM3-6B`
2. 选用模型，并提问

**Expected behavior**
返回 422

**Screenshots**
<img width="1286" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/21104213/fadf5255-ac51-409b-afb1-30c105e27843">

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1
 - Browser: chrome
 - Version: 120.0.6099.129

**Additional Logs**
<img width="752" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/21104213/ce96e1cc-a9ed-4b00-843b-30aeb06be539">

**Comment by Harry-zklcdc** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3427#issuecomment-1853959695
上游仓库已有相关 issue，但未解决

**Comment by Hk-Gosuto** [comment]
你的 BASE_URL 中包含 path？

**Comment by Harry-zklcdc** [comment]
> 你的 BASE_URL 中包含 path？

并没有携带 path
<img width="625" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/21104213/60eb44da-8921-4d9d-a15e-08959d8e2db1">

**Comment by Hk-Gosuto** [comment]
发一下你接口请求的完整参数，我看下多了什么内容。

**Comment by Harry-zklcdc** [comment]
> 发一下你接口请求的完整参数，我看下多了什么内容。

#### 前端请求参数
<img width="643" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/21104213/e83de076-2633-4218-90ae-e6eeba916d27">
<img width="729" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/21104213/bfbd736c-bff5-4a73-99bd-b86279990684">

#### 后端日志
<img width="451" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/21104213/559d764c-fdda-4b6e-8a3b-7392fb942a3c">

#### OneAPI 日志
<img width="1045" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/21104213/a8065c94-b8e1-4764-b0d2-a33150516216">

**Comment by Hk-Gosuto** [comment]
你用 postman 或者类似的工具测试一下接口，看下是哪个参数导致的，看起来像是 max_tokens 没传导致的。

**Comment by Harry-zklcdc** [comment]
测试之后，确实是由 `max_tokens` 导致

但是还有另一个很奇怪的问题，我明明设置了 `max_tokens` 这个选项，但是却没有加入请求参数
<img width="1100" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/21104213/a03a878b-ae78-4d87-a2d0-a3a16d0045e3">

**Comment by Harry-zklcdc** [comment]
> 这个是上游仓库的业务，具体什么原因为也不是很清楚：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/cc86923fd578d3f9182df6d1cac86a6e97b30259/app/client/platforms/openai.ts#L92C18-L92C18

奇了怪了，上游仓库把 `max_tokens` 注释了🤔

**Comment by Hk-Gosuto** [comment]
openai 的接口也是支持 null 值的 。https://platform.openai.com/docs/api-reference/chat/create

**Comment by reece00** [comment]
test

**Comment by Harry-zklcdc** [comment]
> max_tokens 取消原因样本 [ChatGPTNextWeb#3199](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3199)

好叭
