### ISSUE TITLE
docker部署完成后apache反向代理，网站访问正常。图片是烂图，上传图片也是烂图。

### ISSUE THREAD

**Issue by koulas** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#148]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
docker部署完成后apache反向代理，网站访问正常。图片是烂图，上传图片也是烂图。

**截图**
![微信图片_20240105112451](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/2045443/4b8f584a-2a4c-498d-9fa2-63341609ba51)
![微信图片_20240105112440](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/2045443/03843165-bafb-4bb7-a1e1-db9829086b7c)
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：ubuntu
 - 浏览器： chrome, 
 - 版本： [填写设置页面的版本号]
 - 部署方式：docker

**Comment by pacmandoh** [comment]
请问您拉取最新代码了吗？能否提供一下控制台信息？

**Comment by koulas** [comment]
> 请问您拉取最新代码了吗？能否提供一下控制台信息？

更新最新版本后解决了，但是谷歌的gemin好像调用不了，已经填写了key

**Comment by Hk-Gosuto** [comment]
> > 请问您拉取最新代码了吗？能否提供一下控制台信息？
> 
> 更新最新版本后解决了，但是谷歌的gemin好像调用不了，已经填写了key

检查一下 `GOOGLE_BASE_URL ` 配置，本项目需要配置成 `https://generativelanguage.googleapis.com` 这种，不需要添加后面的 path

**Comment by koulas** [comment]
> > >

还是不能成功，已经填写https://generativelanguage.googleapis.com了

**Comment by pacmandoh** [comment]
> > > >
> 
> 
> 
> 还是不能成功，已经填写https://generativelanguage.googleapis.com了

@koulas 您在国内网络环境下可能需要中专地址，不使用代理无法访问接口

**Comment by koulas** [comment]
问题都已经解决
