### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pcb1998** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#149]
**描述问题**
使用dalle3画图，图是一点点加载显示出来的，十分慢，但是我看到对象存储中的同一张图片加载非常快。

**如何复现**
使用又拍云对象存储。然后让dalle3画图，图就想流式加载一样，但是对象存储哪里图片就一两秒加载完成了3Mb的图片。

**一些必要的信息**
 - 系统：[windows 10
 - 浏览器： [ chrome]
 - 版本： [v2.9.13]
 - 部署方式：[docker]

**Comment by Hk-Gosuto** [comment]
图片是中转到你应用部署的服务器上再显示的，如果你应用服务器网络不好，那加载的就慢。

**Comment by pcb1998** [comment]
没有疑问
