### ISSUE TITLE
[Bug]  TypeError: Cannot read properties of undefined (reading 'message')] 'writer error'

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#15]
**描述问题**
使用讯飞星火认知免费api，对接one-api，在chatgpt-next-web-LangChain中使用。
![image](https://github.com/songquanpeng/one-api/assets/70044239/90b671bd-9e4f-468b-bf73-a55d4b23930a)
回复一直都带有如下错误。
```
{
  "error": true,
  "message": "[object Object]"
}
```
在原版chatgpt-next-web不会出现这个问题。

**如何复现**
1.填写好配置
![image](https://github.com/songquanpeng/one-api/assets/70044239/18202d94-5593-4319-91be-8d56fa772a79)
2.选择模型
![image](https://github.com/songquanpeng/one-api/assets/70044239/3869a5f9-fef7-45fe-ae7b-967d250e2f56)
3.使用出错
![image](https://github.com/songquanpeng/one-api/assets/70044239/3605f0c5-2d4d-42d5-aca1-709544d5b62f)

**预期行为**
没有如下错误。
```
{
  "error": true,
  "message": "[object Object]"
}
```

**相关截图**
在one-api使用这个项目，one-api会出现下面错误。
![image](https://github.com/songquanpeng/one-api/assets/70044239/f51f14ab-1250-4342-8204-90d60ae50a64)
![image](https://github.com/songquanpeng/one-api/assets/70044239/6248317d-9cae-427e-8641-4825f72c5fb5)

**Deployment**
Docker

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Version 版本 116.0.1938.76 (正式版本) (64 位)

**Smartphone (please complete the following information):**
不会在手机使用。

**Additional Logs**
无

**Comment by cui8** [comment]
对了，我使用的版本是四天前github仓库的源码。
希望作者大大能解决下chatgpt-next-web-LangChain使用出错，而chatgpt-next-web不会出错的问题。
最后，感谢作者大大开源本项目，让我这个小白能用上ai。再次感谢

**Comment by Hk-Gosuto** [comment]
插件功能是基于微调版本的 OpenAI ChatGPT 模型实现的，仅限于以下几个模型。其它厂商的模型需要关闭插件功能，后面的版本我会修改规则将其它模型的插件功能默认关闭。
- gpt-4
- gpt-4-0613
- gpt-4-32k
- gpt-4-32k-0613
- gpt-3.5-turbo
- gpt-3.5-turbo-0613
- gpt-3.5-turbo-16k
- gpt-3.5-turbo-16k-0613
