### ISSUE TITLE
配置 S3 对象存储服务 使用minio但是一直报错  Image upload to OSS failed很抱歉，看起来在尝试生成图像时遇到了一些问题。

### ISSUE THREAD

**Issue by DC925928496** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#152]
如题，配置为
docker run -d -p 3002:3000 \
   -e OPENAI_API_KEY="sk-xxxxxxxx" \
   -e CODE="xxxxx" \
   -e BASE_URL="http://xxxxxxxxx" \
       -e CHOOSE_SEARCH_ENGINE="baidu" \
   -e S3_ENDPOINT="https://oos.xxxxxx.com" \
   -e S3_ACCESS_KEY_ID="xxxxxxx" \
   -e S3_SECRET_ACCESS_KEY="xxxxxxxxxxxxxxx" \
   -e S3_BUCKET="/static" \
   gosuto/chatgpt-next-web-langchain

**Comment by DC925928496** [comment]
只能指定在某个buckets，不能具体到其中的某个文件夹吗？比如，-e S3_BUCKET="static/test"

**Comment by Hk-Gosuto** [comment]
S3 协议不支持这种结构的 bucket ，关于 bucket 命名规则可以参考：https://docs.aws.amazon.com/zh_cn/AmazonS3/latest/userguide/bucketnamingrules.html
