### ISSUE TITLE
[Bug] PDF浏览器插件在抱脸space不可用

### ISSUE THREAD

**Issue by happychos** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#153]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
抱脸space部署，添加参数NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN=1也无法打开pdf浏览器，dockerfile文件如下:

FROM node:18
RUN git clone https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain.git
WORKDIR "ChatGPT-Next-Web-LangChain"

RUN yarn install && yarn build

EXPOSE 3000
CMD yarn start

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ android 11 / ios 16]
 - 浏览器： chrome,
 - 版本： [填写设置页面的版本号]
 - 部署方式：抱脸space

**Comment by Hk-Gosuto** [comment]
`NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` 是作为编译时环境变量，需要在编译前配置，可以参考：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/Dockerfile

**Comment by happychos** [comment]
> `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` 是作为编译时环境变量，需要在编译前配置，可以参考：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/Dockerfile

已解决，多谢大佬！
