### ISSUE TITLE
通过vercel部署在使用gpt-4-vision-preview模型分析图片时，频繁报错，无法正常使用

### ISSUE THREAD

**Issue by Hurry233** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#154]
**Describe the bug**
通过vercel部署在使用gpt-4-vision-preview模型分析图片时，频繁报错，无法正常使用

**Expected behavior**
偶尔偶尔能成功，大部分时候都是如下报错。

**Screenshots**
![1704780927287](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/80822989/f8ada90d-35fe-4d7b-9eeb-db50b84f5c06)
![1704781045160](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/80822989/0fe51c6e-f5f6-462c-a46f-85fcd1e738b1)
![1704781056654](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/80822989/15ed7620-3f50-45f7-b5e3-18086a78ca6e)

**Deployment**

- [x] Vercel

**Comment by Hurry233** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/80822989/9d931a43-813a-4906-8e25-c32b1d00ae8f)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/80822989/d88aef86-aa8d-4a61-9a92-f93f96a461fa)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/80822989/bee54031-979e-4850-a5a3-564560e23130)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/80822989/efacfb9a-c8ea-4547-91d3-e534b3e182ac)

日志log里主要报错，无论使用vercel自己分配的域还是自己绑定的都一样。然后新版本调用插件时前端报错：
![cf9e078185635130e798cb7aac9989a](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/80822989/e4fade60-2344-48ae-9099-6cfad8ac4a77)

**Comment by Hk-Gosuto** [comment]
在前端配置中设置一下自定义接口，试一下是不是 BASE_URL 中转的问题。

**Comment by Hurry233** [comment]
不行，删除BASE_URL后直接在前端修改接口，其他模型正常使用，gpt-4-vision-preview报错依然和之前一样

**Comment by Hk-Gosuto** [comment]
那可能是你的中转服务有问题，在前端配置自定义接口后所有请求都是直接发送到了你的中转服务中。
