### ISSUE TITLE
[Bug] 生成的DALL.E-3 图片可以浏览，但是 sandbox:// 地址无法显示；也不方便下载

### ISSUE THREAD

**Issue by koyo922** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#155]
如图，配置好R2和S3存储以后，可以正常生成图片；但是

- 没有提供下载途径（在图片上右击会直接将markdown copy到输入框，而非 提供下载菜单）
- markdown中的 sandbox:// 路径会显示失败，不好看

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/6063429/c744e5ee-a9ef-492a-a5e0-c0a5e03c4423)

**Comment by Hk-Gosuto** [comment]
上面的是程序直接输出的图片路径，下面是 gpt 自己构造的路径。两个其实是一张图。
可以先忽略，后面版本会尝试通过修改插件的提示词或其他方式解决。
