### ISSUE TITLE
[Bug] Vercel部署，输出突然停止，出现很多Task timed out after 10.0x seconds

### ISSUE THREAD

**Issue by A2Sumie** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#156]
**Describe the bug**
如题如图
<img width="1031" alt="图片" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/89308692/cad8b34d-1f57-41e1-9013-d1419b925918">
我在用1106然后用一些要输出方程式的东西。
计算器和Wolfram关了都经常这样。输出一点点就停了。能看到输出不完整
之前本地没遇到过但设备恰好出了问题。

**To Reproduce**
问一些数学问题，观察输出。

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by A2Sumie** [comment]
差了一下免费Vercel有10秒限制？大概没事了

**Comment by Hk-Gosuto** [comment]
你这里调用的 nodejs 版的插件接口，正常在 vercel 环境下应该是调用 /api/langchain/tool/agent/edge 这个在 vercel 中不会有超时的问题，你配置了 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` ?
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/2e572bb0-6750-4174-9df4-e10790c570b3)

**Comment by A2Sumie** [comment]
> 你这里调用的 nodejs 版的插件接口，正常在 vercel 环境下应该是调用 /api/langchain/tool/agent/edge 这个在 vercel 中不会有超时的问题，你配置了 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` ? ![image](https://private-user-images.githubusercontent.com/14031260/295756890-2e572bb0-6750-4174-9df4-e10790c570b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Mzc5MjMsIm5iZiI6MTcwNDkzNzYyMywicGF0aCI6Ii8xNDAzMTI2MC8yOTU3NTY4OTAtMmU1NzJiYjAtNjc1MC00MTc0LTlkZjQtZTEwNzkwYzU3MGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAxNDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ODBmYWE2ZTY3OWJjNDU3ZGFkZGNlZDhiNGIzYWI0OWVlOTAzODkwYWZkNTQ0MDMzNDYwZGQ1MGNkZjFhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sh7uy_qg2qqKdMT1BfGkcMe-rYImbr_chML1Ps979Zc)

应该是以前pdf提取刚上的时候闹着玩开过

**Comment by Hk-Gosuto** [comment]
> > 你这里调用的 nodejs 版的插件接口，正常在 vercel 环境下应该是调用 /api/langchain/tool/agent/edge 这个在 vercel 中不会有超时的问题，你配置了 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` ? ![image](https://private-user-images.githubusercontent.com/14031260/295756890-2e572bb0-6750-4174-9df4-e10790c570b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Mzc5MjMsIm5iZiI6MTcwNDkzNzYyMywicGF0aCI6Ii8xNDAzMTI2MC8yOTU3NTY4OTAtMmU1NzJiYjAtNjc1MC00MTc0LTlkZjQtZTEwNzkwYzU3MGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAxNDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ODBmYWE2ZTY3OWJjNDU3ZGFkZGNlZDhiNGIzYWI0OWVlOTAzODkwYWZkNTQ0MDMzNDYwZGQ1MGNkZjFhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sh7uy_qg2qqKdMT1BfGkcMe-rYImbr_chML1Ps979Zc)
> 
> 应该是以前pdf提取刚上的时候闹着玩开过

那删掉 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` 环境变量重新部署下就好了，vercel nodejs 运行时的限制比较多。

**Comment by A2Sumie** [comment]
> > > 你这里调用的 nodejs 版的插件接口，正常在 vercel 环境下应该是调用 /api/langchain/tool/agent/edge 这个在 vercel 中不会有超时的问题，你配置了 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` ? ![image](https://private-user-images.githubusercontent.com/14031260/295756890-2e572bb0-6750-4174-9df4-e10790c570b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Mzc5MjMsIm5iZiI6MTcwNDkzNzYyMywicGF0aCI6Ii8xNDAzMTI2MC8yOTU3NTY4OTAtMmU1NzJiYjAtNjc1MC00MTc0LTlkZjQtZTEwNzkwYzU3MGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAxNDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ODBmYWE2ZTY3OWJjNDU3ZGFkZGNlZDhiNGIzYWI0OWVlOTAzODkwYWZkNTQ0MDMzNDYwZGQ1MGNkZjFhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sh7uy_qg2qqKdMT1BfGkcMe-rYImbr_chML1Ps979Zc)
> > 
> > 
> > 应该是以前pdf提取刚上的时候闹着玩开过
> 
> 那删掉 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` 环境变量重新部署下就好了，vercel nodejs 运行时的限制比较多。

已经去掉了，完全OK，感谢
顺便请问一下，wolfram api是申请simple api吗，langchain的文档也没说是哪种

**Comment by Hk-Gosuto** [comment]
> > > > 你这里调用的 nodejs 版的插件接口，正常在 vercel 环境下应该是调用 /api/langchain/tool/agent/edge 这个在 vercel 中不会有超时的问题，你配置了 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` ? ![image](https://private-user-images.githubusercontent.com/14031260/295756890-2e572bb0-6750-4174-9df4-e10790c570b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Mzc5MjMsIm5iZiI6MTcwNDkzNzYyMywicGF0aCI6Ii8xNDAzMTI2MC8yOTU3NTY4OTAtMmU1NzJiYjAtNjc1MC00MTc0LTlkZjQtZTEwNzkwYzU3MGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAxNDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ODBmYWE2ZTY3OWJjNDU3ZGFkZGNlZDhiNGIzYWI0OWVlOTAzODkwYWZkNTQ0MDMzNDYwZGQ1MGNkZjFhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sh7uy_qg2qqKdMT1BfGkcMe-rYImbr_chML1Ps979Zc)
> > > 
> > > 
> > > 应该是以前pdf提取刚上的时候闹着玩开过
> > 
> > 
> > 那删掉 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN` 环境变量重新部署下就好了，vercel nodejs 运行时的限制比较多。
> 
> 已经去掉了，完全OK，感谢 顺便请问一下，wolfram api是申请simple api吗，langchain的文档也没说是哪种

申请 LLM API，这个确实有点模糊，后面我在文档中标注一下。
