### ISSUE TITLE
[Feature] 对话搜索功能，对话批量导出导入功能

### ISSUE THREAD

**Issue by chatGPTxx** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#158]
请问有添加搜索功能的计划吗？
比如在 对话列表上方增加搜索框，搜索对话标题和内容
![1704981494504](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/128958424/00c41bea-5cab-47bb-b2d6-0931d7d5d2ae)

另外如果对话列表可以支持批量选择再导出就更好了

**Comment by Hk-Gosuto** [comment]
这种通用需求可以先提到上游项目：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web

**Comment by chatGPTxx** [comment]
上游项目好像不怎么维护了。。 搜索有个PR 提了很久但是没有merge

**Comment by Hk-Gosuto** [comment]
只合并了搜索功能

**Comment by chatGPTxx** [comment]
谢谢！
