### ISSUE TITLE
访问功能权限限制诉求

### ISSUE THREAD

**Issue by lijz36** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#159]
为了限定指定用户可以访问，或者公司内部才能使用此功能，
咱们得模型是否可以添加配置实现：
    1. ip白名单列表。
    2. 指定USER-AGENT列表。
如果目前可以实现，麻烦知道一下，在什么位置，添加什么代码实现？谢谢！

**Comment by Hk-Gosuto** [comment]
ip 白名单可以在外面再套一层 nginx 实现
插件相关的内容如果你想改的话可以改 `app\plugins` 下的代码
