### ISSUE TITLE
[Feature] 搜索代理与原版使用的代理分开

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#16]
**这个功能与现有的问题有关吗？**
没有。

**你想要什么功能或者有什么建议？**
作者大大能把搜索代理分开吗？我对接了one-api，base_url是内网one-api地址，所以在使用ai模型时不需要代理。
但是，使用搜索需要代理，所以大佬能把搜索代理与原版使用的代理分开吗？
有什么冒犯大佬的地方，还请见谅。本人小白一枚，不懂技术，纯属根据自己的需求提问，感谢大佬。

**有没有可以参考的同类竞品？**
无。

**其他信息**
暂无。

**Comment by Hk-Gosuto** [comment]
增加了一个环境变量 `DDG_PROXY_URL` 示例配置 `DDG_PROXY_URL=http://127.0.0.1:7890`。

需要注意的是由于代理需要引用 nodejs 核心库，但是引用核心库会导致 vercel 的边缘函数运行时必须指定为 nodejs，而 nodejs 运行时版本边缘函数会有接口超时限制。
说人话就是开启 `DDG_PROXY_URL` 如果使用 vercel 部署，调用插件时可能会出现超时的情况。

不过鉴于你的使用场景应该不会有该问题。
其实我更建议把默认检索引擎配置为 SerpApi 或者 Bing，两个接口在国内使用目前不需要配置代理。

**Comment by cui8** [comment]
> 经过一些调试发现该特性与 vercel 运行时有冲突，由于目前主流部署方案还是 vercel，所以该特性将被移除。 如果有人有更好的方案欢迎提 PR。

非常感谢大佬，太热心了，我接受了大佬的建议，换成bing了，非常完美。
大佬，您的版本非常好用，就日志gpt答复的时候有显示，这个非常棒，我这个小白可以快速知道是否可用，而不是看不懂。我用原版没发现这个功能。
我想问下大佬，日志显示ai回复内容是由设置里的启用插件调试功能来决定的吗？
最后，希望大佬能在日志加入提问的问题，而不是只有ai回复的内容。

**Comment by Hk-Gosuto** [comment]
> > 经过一些调试发现该特性与 vercel 运行时有冲突，由于目前主流部署方案还是 vercel，所以该特性将被移除。 如果有人有更好的方案欢迎提 PR。
> 
> 非常感谢大佬，太热心了，我接受了大佬的建议，换成bing了，非常完美。 大佬，您的版本非常好用，就日志gpt答复的时候有显示，这个非常棒，我这个小白可以快速知道是否可用，而不是看不懂。我用原版没发现这个功能。 我想问下大佬，日志显示ai回复内容是由设置里的启用插件调试功能来决定的吗？ 最后，希望大佬能在日志加入提问的问题，而不是只有ai回复的内容。

中间显示的过程其实是 GPT 调用插件的入参，GPT 会根据你的提问来选择使用哪个插件，以及插件的输入是什么。
比如你让 GPT 搜索2023年的最新影视列表，它不会完全根据你的输入去搜索，而是把你的内容转换问搜索关键字，再调用搜索引擎。
中间过程的开关可以在设置中进行修改。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/afbe9285-3970-42ce-9565-06e8c897763e)

**Comment by cui8** [comment]
> > > 经过一些调试发现该特性与 vercel 运行时有冲突，由于目前主流部署方案还是 vercel，所以该特性将被移除。 如果有人有更好的方案欢迎提 PR。
> > 
> > 
> > 非常感谢大佬，太热心了，我接受了大佬的建议，换成bing了，非常完美。 大佬，您的版本非常好用，就日志gpt答复的时候有显示，这个非常棒，我这个小白可以快速知道是否可用，而不是看不懂。我用原版没发现这个功能。 我想问下大佬，日志显示ai回复内容是由设置里的启用插件调试功能来决定的吗？ 最后，希望大佬能在日志加入提问的问题，而不是只有ai回复的内容。
> 
> 中间显示的过程其实是 GPT 调用插件的入参，GPT 会根据你的提问来选择使用哪个插件，以及插件的输入是什么。 比如你让 GPT 搜索2023年的最新影视列表，它不会完全根据你的输入去搜索，而是把你的内容转换问搜索关键字，再调用搜索引擎。 中间过程的开关可以在设置中进行修改。 ![image](https://user-images.githubusercontent.com/14031260/268423924-afbe9285-3970-42ce-9565-06e8c897763e.png)

明白了，谢谢大佬，非常赞，辛苦了
