### ISSUE TITLE
[Bug] 搜索插件无法正常使用

### ISSUE THREAD

**Issue by yosh3289** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#163]
Vercel上使用“搜索引擎”插件（GoogleCustomSearch），无法正常返回搜索结果
![googlecustomsearch失效](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/27570755/d4cbd0e8-ddce-460c-b49c-893207516159)

**Comment by Hk-Gosuto** [comment]
看一下有没有错误日志，有的话发出来看下

**Comment by yosh3289** [comment]
我在vercel里面对比了用gcs和serp的log，目前没有发现任何差别。请问还有其他办法查询吗？
![gcs截图](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/27570755/40a6fa33-9021-4ece-b144-5abce83b261c)
![serp截图](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/27570755/7f248a20-1b2e-442f-954b-e09885000d2a)

**Comment by yosh3289** [comment]
> 我在vercel里面对比了用gcs和serp的log，目前没有发现任何差别。请问还有其他办法查询吗？ ![gcs截图](https://private-user-images.githubusercontent.com/27570755/299526420-40a6fa33-9021-4ece-b144-5abce83b261c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTI5MzksIm5iZiI6MTcwNjE1MjYzOSwicGF0aCI6Ii8yNzU3MDc1NS8yOTk1MjY0MjAtNDBhNmZhMzMtOTAyMS00ZWNlLWIxNDQtNWFiY2U4M2IyNjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAzMTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNDU0ZmZiNWVhZWRmZWIwNjE2MTIwNWQ3MGI2OWY5MzEzYTljNTE2MzZlMjNiZGVlNDU2ZDlhZTUxN2RhZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TqI0vtFiDuxhGhn-zUM9vt52PLdw9UCM76Jj_cwyvuA) ![serp截图](https://private-user-images.githubusercontent.com/27570755/299526424-7f248a20-1b2e-442f-954b-e09885000d2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTI5MzksIm5iZiI6MTcwNjE1MjYzOSwicGF0aCI6Ii8yNzU3MDc1NS8yOTk1MjY0MjQtN2YyNDhhMjAtMWIyZS00NDJmLTk1NGItZTA5ODg1MDAwZDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAzMTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NTRkNzFhNTBjZWE2OTVhNDQyMWUyYTY0YjVmOTYxYTQ1MzJkMjcwYzNhNWE3ZTEzMzZlZTM4ODExNmFkYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LYIVUKYOqzB4DBp_tw5SfH1gUFwf219tw1-WJF1Xhuw)

03分的是用google custom search搜索返回的日志，06分是用serp返回的日志

**Comment by yosh3289** [comment]
刚查询了一下gcs后台统计信息，确实没有返回网页搜索结果
![gcs日期截图](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/27570755/830e3760-ed5d-416a-8eca-f24a353ac394)

**Comment by Hk-Gosuto** [comment]
检查一下 GOOGLE_API_KEY GOOGLE_CSE_ID 两个参数，或者尝试升级项目到最新，我 vercel 上部署的也是用的这个插件并没有出现问题。![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/0459ab05-b101-42aa-909f-d098a252c09f)

**Comment by yosh3289** [comment]
请问这个api key是不是不能限制为仅gemini使用呢？
![googleapi截图](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/27570755/cd5a0e02-feb3-467e-9213-cccdb759f1ac)

**Comment by yosh3289** [comment]
已经查出问题了，我可能之前在GCP里把custerm search api关掉过所以其实服务一直没打开。谢谢协助！
