### ISSUE TITLE
[Feature] 加入新模型

### ISSUE THREAD

**Issue by d0j1a1701** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#166]
加入 OpenAI 新模型 `gpt-4-0125-preview` `gpt-4-turbo-preview`，很快还会有 `gpt-3.5-turbo-0125`，可以顺手也加上用于占位。

**Comment by MuRo-J** [comment]
上游添加啦，辛苦作者大大～
不过自定义模型名称自己添加后发现可以用，就是模型名称顺序在最后，并且没有 provider信息（不知道provider信息有啥影响）

**Comment by Hk-Gosuto** [comment]
最近有些事情，手边没有电脑用，预计周五前会合并代码。

**Comment by Hk-Gosuto** [comment]
代码已合并
