### ISSUE TITLE
[Bug] gpt4v模型即使配置了s3服务，对话接口依旧提交的是base64编码的图片数据，而不是图片url链接

### ISSUE THREAD

**Issue by RipperTs** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#167]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Hk-Gosuto** [comment]
设计如此，非bug
