### ISSUE TITLE
[Feature] 通过环境变量关闭自动生成标题和聊天总结

### ISSUE THREAD

**Issue by Feliks151450** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#168]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
能否在部署时就关掉自动生成标题的功能呢，很多人用的次数卡，生成标题就直接浪费掉一次使用次数了

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Hk-Gosuto** [comment]
这种通用的功能可以先提交到上游仓库，如果上游仓库拒绝实现且需求合理我这边会进行开发。

**Comment by Feliks151450** [comment]
> 这种通用的功能可以先提交到上游仓库，如果上游仓库拒绝实现且需求合理我这边会进行开发。

去看了一圈，基本上这种加环境变量控制的需求他们都不管

**Comment by Hk-Gosuto** [comment]
配置下面两个环境变量来关闭自动生成标题和历史摘要：
```
NEXT_PUBLIC_DISABLE_AUTOGENERATETITLE=1
NEXT_PUBLIC_DISABLE_SENDMEMORY=1
```
