### ISSUE TITLE
[Bug] 仍然不可以从剪切板粘贴图片

### ISSUE THREAD

**Issue by gaojunyang666** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#169]
开发者大大您好，目前的版本我测试下来发现还是不可以复制粘贴的方式来上传图片

**Comment by Hk-Gosuto** [comment]
大概是我后面优化时搞坏了，最近会修复。

**Comment by MuRo-J** [comment]
测试都可以，gtp-4-turbo-preview 模型 和名称 可以默认在首位啦 和 粘贴上传～辛苦作者大大！实在辛苦啦！

> 大概是我后面优化时搞坏了，最近会修复。
