### ISSUE TITLE
[插件问题] 无法调用插件

### ISSUE THREAD

**Issue by Sooloom** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#171]
我用的是本地模型，无法调用插件
帮我查找下关于白内障手术的学术论文
回复是
{"type": "function", "function": {"name": "arxiv", "description": "Run Arxiv search and get the article information.", "parameters": { "type": "object", "properties": { "searchQuery": { "type": "string", "description": "same as the search_query parameter rules of the arxiv API." }, "sortBy": { "type": "string", "description": "can be "relevance", "lastUpdatedDate", "submittedDate""}, "sortOrder": { "type": "string", "description": "can be either "ascending" or "descending""}, "start": { "type": "number", "default": 0, "description": "the index of the first returned result."}, "maxResults": { "type": "number", "default": 10, "description": "the number of results returned by the query."}}, "required": ["searchQuery", "sortBy", "sortOrder"], "additionalProperties": false, "$schema": "[http://json-schema.org/draft-07/schema#"}}}](http://json-schema.org/draft-07/schema#%22%7D%7D%7D)

请问是什么原因？

**Comment by Hk-Gosuto** [comment]
插件功能是基于 openai api 中的 [function-calling](https://platform.openai.com/docs/guides/function-calling) 功能实现的，其他模型如果不支持该参数则无法进行插件调用。

**Comment by Sooloom** [comment]
谢谢
