### ISSUE TITLE
[Bug] Wolfram Alpha 插件无效

### ISSUE THREAD

**Issue by amakerlife** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#175]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**

已设置 `WOLFRAM_ALPHA_APP_ID` 环境变量，且在 prompt 中明确说要用 Wolfram Alpha 求解，但 GPT3.5 会稳定使用 web-browser，GPT4 稳定不会使用这两个插件。

**截图**

![](https://img.makerlife.top/data/202402061010729.png)

![](https://img.makerlife.top/data/202402061013249.png)

**Comment by Hk-Gosuto** [comment]
检查插件开关是否开启：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/dac9d985-214d-4deb-baa1-17ed76ef31a0)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/1acbd3e5-67d1-42f5-a0d4-5c1716c44c6d)
