### ISSUE TITLE
gpt-3.5-turbo-0301跑到模型列表里了

### ISSUE THREAD

**Issue by SuiYunsy** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#176]
https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/7a3f6f83da6f214b4920f37a8210550bb9d9596c/app/constant.ts#L111

作者大大，我记得之前版本是没有gpt-3.5-turbo-0301这个模型的，但目前的代码中它又跑出来了。您可以看看要不要处理掉。

顺祝您龙年大吉O(∩_∩)O

**Comment by Hk-Gosuto** [comment]
应该是同步上游代码把这个版本的模型又带出来了，这个版本的模型也确实没什么存在的意义了，我去删掉。
