### ISSUE TITLE
[Feature] 增加绘图功能吗

### ISSUE THREAD

**Issue by n3ap** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#18]
/v1/image/generation

**Comment by Hk-Gosuto** [comment]
对接Dall-E？

**Comment by n3ap** [comment]
> 对接Dall-E？

差不多吧

**Comment by n3ap** [comment]
> 对接Dall-E？

# Using Image Generation (python):
```python
import requests
data = {"prompt":"a dog running in a house",
        "model":"stable-diffusion-2"
        }
headers = {
    "Content-type":"application/json",
    "Authorization": "Bearer YOUR_API_KEY"
}
response = requests.post("https://xxxxx/api/images/generations",json=data, headers=headers)
response = response.json()
print(response)
```

# Using Image Generation (Curl):

```curl
curl -X POST "https://api.webraft.in/api/images/generations" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer YOUR_API_KEY" \
     -d '{"prompt":"a dog running in a house","model":"stable-diffusion-2"}'

```
像它这样绘图模型可以改，不懂可不可以跟文本一样自定义模型。

**Comment by Hk-Gosuto** [comment]
stable-diffusion 是需要gpu资源的，如果个人想使用只能自己部署模型并运行在有gpu资源的机器上。
dall-e OpenAI 官方有提供接口，消耗账户金额即可调用。
如果只是 dall-e 应该可以用插件来实现。

**Comment by n3ap** [comment]
> stable-diffusion 是需要gpu资源的，如果个人想使用只能自己部署模型并运行在有gpu资源的机器上。
> dall-e OpenAI 官方有提供接口，消耗账户金额即可调用。
> 如果只是 dall-e 应该可以用插件来实现。

是吗，这代码我可以直接在Python上运行，然后它会返回一个图片链接。

**Comment by Hk-Gosuto** [comment]
因为你这个就是第三方提供的服务，这种服务一般并不稳定。
dall-e 我调研一下看看实现难度。

**Comment by Hk-Gosuto** [comment]
#20

**Comment by Hk-Gosuto** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/9aab55b4-6156-4f6d-8108-64af25fa7aa9)
