### ISSUE TITLE
[Bug]  明明上传了图片，但gpt回复我很抱歉，您似乎没有上传任何图片

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#182]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/a8951652-67c3-49d0-9ea4-2b3ba15454eb)
如上图所示，我在本地启动了该项目，配置好了apikey，s3又拍云存储等，切换到gpt4-vision-preview的模型，但是得到如上的回复，“很抱歉，您似乎没有上传任何图片。请上传一张图片，我会帮您进行分析和描述。"，辛苦大佬帮忙看下问题原因

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by Hk-Gosuto** [comment]
是否为官方 api 接口而不是其他服务转发？

**Comment by zpng** [comment]
> 是否为官方 api 接口而不是其他服务转发？

噢噢 的确是这个问题，为啥转发的不行啊大佬

**Comment by Hk-Gosuto** [comment]
程序的是通过 `image_url` 参数传递的图像的 base64 数据，可能你用的服务只是转发了普通的 gpt4 接口，并不支持图像上传。

**Comment by zpng** [comment]
噢噢 get
