### ISSUE TITLE
[Bug] v2.10.1版本使用gemini报错“empty response”

### ISSUE THREAD

**Issue by ccinoo** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#183]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
v2.10.1版本使用gemini报错“empty response”
**如何复现**
请告诉我们你是通过什么操作触发的该问题。
新建gemini对话或原有gemini对话都报错“empty response”

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![](https://pic.ccino.win/OB/2024/02/1707446960202402091049939.png)
**一些必要的信息**
 - 系统：[windows 10]
 - 浏览器： [chrome]
 - 版本： [v2.10.1]
 - 部署方式：[vercel]

**Comment by Hk-Gosuto** [comment]
目前主分支的最新版本没有复现该问题，更新代码到最新后检查一下配置是否有问题。

**Comment by ccinoo** [comment]
> 目前主分支的最新版本没有复现该问题，更新代码到最新后检查一下配置是否有问题。

感谢您这么快回复。如图已再次使用主分支最新版本重新部署，还是报错“empty response”
![](https://pic.ccino.win/OB/2024/02/1707450592202402091149279.png)

![](https://pic.ccino.win/OB/2024/02/1707450826202402091153503.png)

另外vercel部署日志中有以下报错：
`<html>
<body>

./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
--
11:50:48.020 | Module not found: Can't resolve 'aws-crt' in '/vercel/path0/node_modules/@aws-sdk/util-user-agent-node/dist-cjs'
11:50:48.020 |  
11:50:48.020 | Import trace for requested module:
11:50:48.020 | ./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
11:50:48.020 | ./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
11:50:48.020 | ./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
11:50:48.021 | ./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
11:50:48.021 | ./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
11:50:48.021 | ./app/utils/s3_file_storage.ts
11:50:48.021 | ./app/api/file/upload/route.ts
11:50:48.021 |  
11:50:48.024 | - info Linting and checking validity of types...
11:50:55.899 |  
11:50:55.900 | ./app/components/markdown.tsx
11:50:55.900 | 127:29  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
11:50:55.900 |  
11:50:55.900 | ./app/components/search-bar.tsx
11:50:55.900 | 163:6  Warning: React Hook useCallback has a missing dependency: 'input'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
11:50:55.901 | 204:6  Warning: React Hook useEffect has a missing dependency: 'setIsSearching'. Either include it or remove the dependency array. If 'setIsSearching' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps


</body>
</html>`

**Comment by Hk-Gosuto** [comment]
检查一下 `GOOGLE_BASE_URL` 和 `GOOGLE_API_KEY` 两个参数配置是否正确，如果是 vercel 环境部署的话可以不配置 `GOOGLE_BASE_URL`

**Comment by ccinoo** [comment]
> 检查一下 `GOOGLE_BASE_URL` 和 `GOOGLE_API_KEY` 两个参数配置是否正确，如果是 vercel 环境部署的话可以不配置 `GOOGLE_BASE_URL`

Vercel中环境变量`GOOGLE_API_KEY`我配置的是GoogleCustomSearch的KEY，gemini的`GOOGLE_API_KEY`和`GOOGLE_BASE_URL`我是通过启用“自定义接口”后手动配置的。因为我的这两个`GOOGLE_API_KEY`不同。

之前 vercel 环境变量中我是设置了`GOOGLE_BASE_URL`，我已删除后重新部署，还是由此报错。不知是否和我通过启用“自定义接口”后手动配置gemini有关，但之前版本是正常的。

**Comment by Hk-Gosuto** [comment]
应该是自定义接口那块的问题，估计是后面合代码引入的，今天就会修复。

**Comment by ccinoo** [comment]
> 应该是自定义接口那块的问题，估计是后面合代码引入的，今天就会修复。

大佬威武，感谢~~
