### ISSUE TITLE
[Bug] pdf插件总结pdf总结的跟我发给他的完全不相关，发渐冻症的pdf，返回深度学习卷积的总结

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#186]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我让pdf插件总结一个渐冻症相关的论文，但是却返回出来了卷积神经网络的返回，很奇怪。

问题：
帮我总结下该pdf https://arxiv.org/pdf/1401.0697v1.pdf
返回：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/2d90d1b0-5d1c-407f-a4aa-110b09785add)
可是该pdf的内容为：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/14a445fb-667f-44b4-89ab-ba030789c3d6)
，很奇怪，试了很多次都是这个返回，不理解这个是哪里的bug，辛苦大佬帮忙看下

**一些必要的信息**
 - 系统：[mac 13.6 (22G120)]
 - 浏览器： [chrome]
 - 版本： [v2.10.1]
 - 部署方式：[zeabur部署]

**Comment by Hk-Gosuto** [comment]
未能复现该问题
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/1ff42827-2438-49b1-bb1f-b24679bc3f39)

**Comment by zpng** [comment]
> 未能复现该问题 ![image](https://private-user-images.githubusercontent.com/14031260/303892511-1ff42827-2438-49b1-bb1f-b24679bc3f39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MTQ3ODIsIm5iZiI6MTcwNzYxNDQ4MiwicGF0aCI6Ii8xNDAzMTI2MC8zMDM4OTI1MTEtMWZmNDI4MjctMjQzOC00OWIxLWJiMWYtYjI0Njc5YmMzZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDAxMjEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZDBhZjgwODdhMjVkZGRjMTcwNmY1NjM0NDZkNzMwMjU0MDE5MjAzYjBmZTg0YTUzODIwNjkxMDU0YzJhOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g_-JtLA3iBLa_IdcuMJM0lWnjleN9HqgehATaFwH8bI)


那好奇怪啊，我是用这个插件的时候有时候用其他pdf能正确总结，有时候就跟这个issue一样不行，重试多少遍结果都一样，大佬能猜测出来啥原因吗，有可能跟配置和部署有关系吗

**Comment by zpng** [comment]
我刚又试了一遍还是一样的结果，还是会返回卷积神经网络相关内容
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/212fc453-2ed8-4bdc-a850-b8087b8c276a)

**Comment by Hk-Gosuto** [comment]
镜像是否为最新的？换其他pdf链接也是这样？

**Comment by zpng** [comment]
我是拉取的最新代码部署的，有的pdf链接可以，有的不行，很奇怪



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hk-Gosuto ***@***.***&gt;
发送时间: 2024年2月11日 10:16
收件人: Hk-Gosuto/ChatGPT-Next-Web-LangChain ***@***.***&gt;
抄送: zpng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Hk-Gosuto/ChatGPT-Next-Web-LangChain] [Bug] pdf插件总结pdf总结的跟我发给他的完全不相关，发渐冻症的pdf，返回深度学习卷积的总结 (Issue #186)





 
镜像是否为最新的？换其他pdf链接也是这样？

**Comment by zpng** [comment]
帮我总结下该pdf的内容: https://edu.sse.com.cn/theme/investors/share/c/4726971.pdf
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/207534cc-343a-4a46-869c-fcc1ee2610c2)
这个pdf总结的同样有问题，明明讲的是自己的投资故事，总结成了股票交易规则，完全不对
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/a156c185-521f-4c6d-be71-70c2e09cee6e)

@Hk-Gosuto

**Comment by Hk-Gosuto** [comment]
> 这个pdf总结的同样有问题，明明讲的是自己的投资故事，总结成了股票交易规则，完全不对
> 
> 帮我总结下该pdf的内容: https://edu.sse.com.cn/theme/investors/share/c/4726971.pdf ![image](https://private-user-images.githubusercontent.com/8509438/304114441-207534cc-343a-4a46-869c-fcc1ee2610c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDk5MzksIm5iZiI6MTcwNzc0OTYzOSwicGF0aCI6Ii84NTA5NDM4LzMwNDExNDQ0MS0yMDc1MzRjYy0zNDNhLTRhNDYtODY5Yy1mY2MxZWUyNjEwYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTQ1MzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM0YjdlODUyYWU3Mzg0ZWVmYzAyYTUyMjE1ZTgxZjE2MTU3YjhlYzM2ZDBhYzMyMDVjZGM1NmNmMzhkNzA2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mqAjIKDNf_RUlr-sNH2Rebn0nTgGen9zwJS1GkAdyQk) 这个pdf总结的同样有问题，明明讲的是自己的投资故事，总结成了股票交易规则，完全不对 ![image](https://private-user-images.githubusercontent.com/8509438/304114516-a156c185-521f-4c6d-be71-70c2e09cee6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDk5MzksIm5iZiI6MTcwNzc0OTYzOSwicGF0aCI6Ii84NTA5NDM4LzMwNDExNDUxNi1hMTU2YzE4NS01MjFmLTRjNmQtYmU3MS03MGMyZTA5Y2VlNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTQ1MzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjcwY2U1MGQ3YmM4ZjVhZmFhM2UwYjdmMGMxYTc1OTk2MWQzNjBmNWJjM2IxODg5NjUxY2VjYmJmZGYxMmQ0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.04mXPzxnEuuA2MJIwTodgIYNrx8uBad1geoQ08_N7Ig)
> 
> @Hk-Gosuto

总结也不是全文总结，是基于 langchian 的 `TextSplitter` 分割文本后的前4行，现有模型的上下文长度没办法对 pdf 进行全部文本总结，跟完整文档有出入也并不奇怪。

**Comment by Hk-Gosuto** [comment]
比如你上面的 pdf 的完整 prompt就是：
```
Text:我的投资故事 
1


我的投资故事分享

本人是国泰君安的一名普通
小散，2008年7月份入市，到现
在快满八个年头了，经历了2008
年低点、2009年小牛市以及后来
长达五年的猴市，也感受了去年
的火与冰。8年的炒股经历让我
从无知到知道无知，从无头苍蝇
到有的放矢。除了股市的盈亏，
还收获了更为宝贵的东西，那就
是认识了不少朋友，有聊得来的，
有吹牛的，有故弄高深的，也有
很多真诚的，热心的，有真才实
学的人。

这八年里，通过失败经验和
个人学习，有了些许经验，给大
家分享一下：
思考一：炒股的本质、人生
的本质
    股市如人生，人生如股市，
总有高低不平，总有潮涨潮落。
当初自己进股市炒股，为的是什
么，不就是赚点钱改善下生活质
量。其实现在生活还过得去，有
房住，有衣穿，有家庭，无风吹
日晒之忧，无下顿温饱之虑。何
以入市以来如此浮躁呢，猛然间
醒悟，缘于人性的不足-贪婪，因
为贪婪，让自己失去了理智，迷
失了方向，以致丢失生活的本真。
相信有不少初炒股的人有过和我
一样的经历，因为炒股，影响了
工作，冷落了家人，孩子学校有
活动，自己正在看指标，一句话， 我的投资故事
2

没空，一个亲近孩子的机会就此
消失；因为股票大跌，心情烦躁，
和老婆闹气的事也没有少。忽然
间自己体内有个声音，如晴天霹
雳让自己犹如冬天被冷水淋湿般
惊颤，“你在干什么！不要迷失
在歧途！”确实是误入歧途啊。
如此炒股，如此折腾，离原来的
意图越来越远啦！美好的生活是
人生主旋律，炒股是人生的小插
曲，小插曲须服从主旋律。于是，
和老婆上街看下衣服，陪孩子到
学校参加元旦游园活动，陪老父
亲回味下红歌，其乐融融，不亦
乐乎！哈，这才是生活的本真。
炒股应服务于生活，尚若因它影
响了生活质量，当让其消失。

思考二：小散作风，小散心
态
    道听途说，跟风操作，人云
亦云，高买低抛，无疑是自己经
常做的事。没有自己的理解，没
有自己的见地，没有用心理解股
票的道理。股票下跌时，惶惶不
可终日，割，它马上反弹；不割，
它一路狂跌丝毫不见抬头踪迹。
股票上升时，也混身不自在，不
如如何是好，卖，它却一路飙升；
不卖，它却应声下跌，确实让我
等小散不知如何是好。这一切皆
缘于自己的无知，没有了解其中
道理，没有理解其中趋势，分不
清主力是否在出货，是否在调整，
是否在拉升。盲目追高，盲目抄
底，也是我等小散资金损失的主
要原因。不知者无畏，不知道高
处不胜寒，低处不言底。只有做
到有把握，才可一战成功，尚若
相去甚远，应立即空仓反思，保
得本金在，不怕没柴烧。今后，
唯有用心参悟股票之道，慢慢把
握其趋势，慢慢去除小散作风，
小散心态，方能适应节奏，获得我的投资故事
3

收益。

思考三：投资与生活之道
    炒股，需要淡定，需要驽驾
之从容心。有了解，有把握，有
钱途。炒股是投资的一种，是放
鸡蛋的其中的一个篮子。得之我
幸，失之亦无伤大雅。股市有同
人生，人生同股市，无非涨跌，
得势时，春风得意，加薪进爵；
失势时，垂头丧气，前途暗淡。
得失涨跌之间，会有平衡之点，
是起还是再落，看你自己气势，
看你自己积聚的能量。投资与生
活，简而述之：理性投资，美好
生活。

“宠辱不惊，闲看庭前花开花落，
去留无意，漫随天外云卷云舒。”

附带：个人炒股笔迹



 我的投资故事
4






                                         国泰君安证券湖南常德人民路证券营业部
                                       投资者  老谭

I need a summary from the above text.
```

**Comment by Hk-Gosuto** [comment]
我这里使用的模型是 3.5 turbo，总结的内容倒是没有太大出入：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/e0ba9c56-3392-443a-b351-c7ca76d96cd2)

**Comment by zpng** [comment]
你的看起来还是蛮正常的，为啥我的初入这么大呢，你仔细看下我的那个gpt的回答非常离谱

**Comment by zpng** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/db2da4a3-0e75-49b1-97fd-8a64fea6124a)

**Comment by zpng** [comment]
@Hk-Gosuto 再给大佬一个输入，当我把其它插件都关闭，只打开pdf插件的时候，报下面的问题，所以看起来是因为pdf插件没有生效？但是引入了另外一个问题，这个为啥没生效呢？如果没生效之前的回答是啥回答呢，我在本地和zeabur线上部署测试都不行。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/157b18b5-b3d0-431e-91b8-d3c03a961a56)

**Comment by Hk-Gosuto** [comment]
> @Hk-Gosuto 再给大佬一个输入，当我把其它插件都关闭，只打开pdf插件的时候，报下面的问题，所以看起来是因为pdf插件没有生效？但是引入了另外一个问题，这个为啥没生效呢？如果没生效之前的回答是啥回答呢，我在本地和zeabur线上部署测试都不行。ps 我是刚拉取的最新代码测的 ![image](https://private-user-images.githubusercontent.com/8509438/304149940-157b18b5-b3d0-431e-91b8-d3c03a961a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3ODI1NTAsIm5iZiI6MTcwNzc4MjI1MCwicGF0aCI6Ii84NTA5NDM4LzMwNDE0OTk0MC0xNTdiMThiNS1iM2QwLTQzMWUtOTFiOC1kM2MwM2E5NjFhNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMjM1NzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE3YmMwNWI3YTk1MTkyYTk5MDA1NDQzZjUwYjFlZWY0OTA2MzgzMzY0NGFlNTA4NWJiYjk0NzcyMWEzMTRlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C7NrSxkgo_qC5htsn3OstKyB13t6sFy_QFFKtanmUIA)

这种可能是网络问题导致的，跟开关几个插件没什么关系。

**Comment by Hk-Gosuto** [comment]
我怀疑是你使用的模型的问题，你直接用上面的 prompt 来测试一下模型的返回看看吧。

**Comment by zpng** [comment]
另外我今天只打开pdf插件又测试了下，这次不说不能访问pdf了，这次访问结果跟第一次一样，返回的驴头不对马嘴的答案。
这个跟我的部署环境有关吗，我是zeabur us-east部署的，或者环境变量配置有关吗，我配置d的环境变量如下图所示。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/b03055d0-9753-4700-8053-9e2661ade85c)

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/b6b7dc75-afbc-4252-b531-25de49af8dea)

**Comment by Hk-Gosuto** [comment]
你看一下日志，我在最新的代码中把 pdf 插件处理好的 prompt 输出了，搜一下 `[pdf-browser]` 相关的日志。

**Comment by zpng** [comment]
> 你看一下日志，我在最新的代码中把 pdf 插件处理好的 prompt 输出了，搜一下 `[pdf-browser]` 相关的日志。

在日志中没有搜到[pdf-browser]这个日志，是不是没走到？

**Comment by zpng** [comment]
@Hk-Gosuto 
另外我把doc打印出来，发现doc其实是读到了的，所以应该是上面标红的       const vectorStore = await MemoryVectorStore.fromDocuments(
      docs,
      this.embeddings,
    );
    这段代码的问题
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/e63ddd1c-22be-4d7e-b8cd-37d0cbb93dd8)

**Comment by Hk-Gosuto** [comment]
你没走到的方法是将文档转换为向量的部分，你是不是用的转发服务之类的东西，没启用 openai 向量模型？

**Comment by zpng** [comment]
> 你没走到的方法是将文档转换为向量的部分，你是不是用的转发服务之类的东西，没启用 openai 向量模型？

我是用的转发服务，不过这个openai向量模型要怎么启用啊，需要用官方key才可以吗，不能转发服务吗

**Comment by Hk-Gosuto** [comment]
> > 你没走到的方法是将文档转换为向量的部分，你是不是用的转发服务之类的东西，没启用 openai 向量模型？
> 
> 我是用的转发服务，不过这个openai向量模型要怎么启用啊，需要用官方key才可以吗，不能转发服务吗

转发也可以，比如如果你用的是 one-api 转发的话，需要将 `text-embedding-ada-002` 这个嵌入模型加入到渠道的模型中，最好把所有 text 开头的模型都加进来。

**Comment by zpng** [comment]
> https://edu.sse.com.cn/theme/investors/share/c/4726971.pdf

打开text-embedding-ada-002这个的转发可以了，大佬牛逼👍🏻
