### ISSUE TITLE
[Bug] 拉起最新代码后，导出walform生成的图片可以了，但是导出dalle生成的图片时报错

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#188]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
拉起最新代码后，导出walform生成的图片可以了，但是导出dalle生成的图片时报错
如下图，让程序生成烟花的图片
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/72910189-7ba6-4010-b498-a70cadf82816)
然后点击导出 | 预览，
然后看网络控制台报错，
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/dcdc0f10-bdf8-493b-a804-d782164f0142)
看后端的log为，
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/842b1e47-0e1d-4091-8864-478cf5bd8e99)
之前这个导出还是可以的，之前导出walform的不行，现在是导出walform的可以，但是dalle生成的导出会有问题，应该是最近的修改引入的，辛苦大佬看下~

**一些必要的信息**
- System: [mac 13.6 (22G120)]
- Browser: [chrome]
- Version: [v2.10.1]
- Deployment method: [zeabur deployment]

**Comment by Hk-Gosuto** [comment]
确实把这块业务忘了
