### ISSUE TITLE
[Feature] 能增加使用Pandora的access token的功能吗？

### ISSUE THREAD

**Issue by s181462537** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#19]
目前项目只能使用api进行访问，存在额度问题，能否增加使用Pandora的access token访问的方式，这样就没有额度焦虑了

**Comment by Hk-Gosuto** [comment]
非 API 调用形式是不支持支持函数调用的微调版本模型的，如果需要在不使用插件的场景下使用类似 Pandora 的转发形式，建议去上游仓库提 issues。
https://github.com/Yidadaa/ChatGPT-Next-Web
