### ISSUE TITLE
[Feature] 目前配置只支持，BASE_URL，OPENAI_API_KEY这样配置，希望可以额外支持按照模型去进行特定的ur和key的配置,另外希望支持配置的时候可以支持配置多个成对的BASE_URL和OPENAI_API_KEY，然后可以轮询或者随机选

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#190]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**你想要什么功能或者有什么建议？**
目前配置只支持，BASE_URL，OPENAI_API_KEY这样配置，希望可以额外支持按照模型去进行特定的ur和key的配置，因为有可能有的url不支持gpt-vision-preview等模型，有的不支持text-embedding-ada-002等模型。
另外希望支持配置的时候可以支持配置多个成对的BASE_URL和OPENAI_API_KEY，然后可以轮询或者随机选，这样也可以容灾
比如BASE_URL= aaa, bbb
OPENAI_API_KEY=1111,2222
然后后面取的时候用 aaa,1111或者bbb,2222来配对使用。
模型相关的配置希望的形式可以是:
gpt-vision-preview-baseurl: xxx,xxx
gpt-vision-preview-openai-key:xxx,xxx
text-embedding-ada-002-baseurl:xxx,xxx
text-embedding-ada-002-openai-key:xxx,xxx等

**Comment by Hk-Gosuto** [comment]
OPENAI_API_KEY 支持多 key 轮询，其他需求暂时不会考虑实现，这些业务会导致当前的代码变的复杂且不利于后续开发和维护。

**Comment by zpng** [comment]
> OPENAI_API_KEY 支持多 key 轮询，其他需求暂时不会考虑实现，这些业务会导致当前的代码变的复杂且不利于后续开发和维护。

但是baseurl不支持吧，理论上应该要支持baseurl多个轮询和OPENAI_API_KEY多轮询吧，并且要一起配对，不然如果这个url挂了，这个服务就挂了？

**Comment by Hk-Gosuto** [comment]
> > OPENAI_API_KEY 支持多 key 轮询，其他需求暂时不会考虑实现，这些业务会导致当前的代码变的复杂且不利于后续开发和维护。
> 
> 但是baseurl不支持吧，理论上应该要支持baseurl多个轮询和OPENAI_API_KEY多轮询吧，并且要一起配对，不然如果这个url挂了，这个服务就挂了？

多 baseurl 还要考虑跟 key 对应，而且每次进行服务存活校验还会增加使用延迟，得不偿失。
本项目支持的主要使用场景还是部署在 vercel 直连 openai 接口。
