### ISSUE TITLE
[Feature] 关于文件上传的简单实现

### ISSUE THREAD

**Issue by Feliks151450** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#191]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
#179 #77 #109 
对于已经配置了对象存储的情况（比如我用的cf的R2存储桶）它很明显不只能用来存储图片，普通的文件也是可以的。
能否支持在特定的模型下（最好是用户可以通过环境变量指定）也显示上传按钮，但对文件类型没有限制。
上传的文件直接把链接追加到输入框中，或者复制到剪贴板让用户自己选择粘贴
这样可以比较轻松的实现如下效果
<img width="946" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/44024139/77821be2-956f-42ad-b540-38d2b04c856c">

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Hk-Gosuto** [comment]
有相关内容的支持计划，目前还在开发中。

**Comment by zpng** [comment]
> 有相关内容的支持计划，目前还在开发中。

大佬这个进度咋样了？

**Comment by Hk-Gosuto** [comment]
> > 有相关内容的支持计划，目前还在开发中。
> 
> 大佬这个进度咋样了？

本周合并完上游 v2.11.2 代码后会开始做这个需求

**Comment by Hk-Gosuto** [comment]
合并到 #77
