### ISSUE TITLE
[Bug] 作者大大，如果使用密码登录的话，使用gemini-pro模型会报错

### ISSUE THREAD

**Issue by Yanyutin753** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#196]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/132346501/dfa7b641-8b51-4c5f-9739-71c431c17784)

## 1. 会报这个错误BUG，使用gemini-pro模型好像会自动开启插件

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/132346501/abb4a3d9-0104-4f9d-a111-c9c8702dfcc8)

## 2. 关掉插件即可正常进行

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/132346501/e0ad9bb5-cbff-41bc-bb5d-33c0c08d435c)

**Comment by Hk-Gosuto** [comment]
描述一下详细的复现流程，如何操作会在使用 gemini-pro 模型时显示插件功能按钮。

**Comment by Yanyutin753** [comment]
不是 就是没有插件开关，直接用gemini-pro这个模型，请求确实用的插件的请求网址，我在设置把插件开关关掉了，才会用到gemini的网址去请求

**Comment by Yanyutin753** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/132346501/2fca9551-229a-4899-8181-d5746a61b634)

**Comment by Yanyutin753** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/132346501/c706ac9b-27ed-4ccb-90db-579dc2c4c7ef)

**Comment by Yanyutin753** [comment]
把这个插件功能关掉才正常

**Comment by Yanyutin753** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/132346501/bb4f53a5-2cd7-4ea9-b074-3fd6e05192a4)


我是直接用密码进行使用的，没有自定义接口和密钥，且在vercel正确填写了gemini-key

**Comment by Hk-Gosuto** [comment]
我使用隐身窗口按照你的流程试了一下，gemini 模型的调用没发现问题，按道理来说只有当模型名开头三个字母是 `gpt` 时才会触发插件接口调用，你开个隐身窗口再试一下会不会出现这个问题，试一下是不是前端缓存之类的导致的。

**Comment by Yanyutin753** [comment]
我的问题哈哈哈哈哈，找到bug所在了
