### ISSUE TITLE
使用copilot-gpt4-service转换的api无法使用联网功能

### ISSUE THREAD

**Issue by macchen123** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#202]
https://github.com/aaamoon/copilot-gpt4-service这个项目可以把github copilot api转为chatgpt api，它支持以下请求：
GET /: Home page
GET /healthz: Health check
GET /v1/models: Get model list
POST /v1/chat/completions: Chat API
POST /v1/embeddings

我发现调用联网插件时的baseurl是http://127.0.0.1:8080/v1（下图所示），但是copilot-gpt4-service只支持上述请求，不支持直接请求/v1。修改了agentapi.ts里面的baseurl后仍然无法解决问题
![112121212](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/40541246/36ddb0ba-cfe2-4e25-96e8-32360059cdf8)

**Comment by Hk-Gosuto** [comment]
转发的接口不支持插件功能

**Comment by macchen123** [comment]
好吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hk-Gosuto ***@***.***&gt;
发送时间: 2024年2月20日 13:09
收件人: Hk-Gosuto/ChatGPT-Next-Web-LangChain ***@***.***&gt;
抄送: LJC ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Hk-Gosuto/ChatGPT-Next-Web-LangChain] 使用copilot-gpt4-service转换的api无法使用联网功能 (Issue #202)





 
转发的接口不支持插件功能
