### ISSUE TITLE
[Bug] 为啥我按例子操作却没生效

### ISSUE THREAD

**Issue by yuanjie-ai** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#204]
[Bug] 为啥我按例子操作却没生效

**Comment by yuanjie-ai** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/20265321/6c1ce90b-b901-47b3-b651-a12aaf92662d)

**Comment by Hk-Gosuto** [comment]
检查下你的api接口是否支持函数调用，目前只支持 openai 官方 api 以及 azure openai 服务接口使用函数调用。

**Comment by zhouyuexie** [comment]
同样没效果，我的是使用的copilot-gpt4-service转发的，看来目前用不了
