### ISSUE TITLE
[Bug] 通过修改 base_url 转发的gpt（非官方直连接口），所有插件都无法使用

### ISSUE THREAD

**Issue by LeeeSe** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#207]
<img width="1231" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/44465325/f21a9358-183e-4dbc-9c45-8f5ab1de9fb1">

**Comment by Hk-Gosuto** [comment]
检查你的转发服务，看起来像是部分参数没有正常转发。

**Comment by LeeeSe** [comment]
睡了一觉问题自动消失了，可能是昨晚 vercel 那边出了问题
