### ISSUE TITLE
[Feature]   语音输入和输出支持

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#208]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**你想要什么功能或者有什么建议？**
支持语音转文字和文字转语音的功能。

**有没有可以参考的同类竞品？**
类似下面这个人的项目里的功能：https://github.com/vual/ChatGPT-Next-Web-Pro
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/3455a331-60a2-4e04-b95e-dff8889a3ed8)

**Comment by Hk-Gosuto** [comment]
先支持了基于 OpenAI 的 TTS 功能，语音输入后面空了再加。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/3fb2236d-1ac1-467e-8196-251720545ef4)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/ef1fce3f-3f32-4cff-8aa6-a744e1e21458)

**Comment by ofllm** [comment]
点击语音报错：json f "stack": "Error: Failed to execut
e 'decodeAudioData' on 'BaseAudioCo
ntext': Unable to decode audio data" 
请问除了页面设置之外还需要配置其他地方么?

**Comment by Hk-Gosuto** [comment]
> 点击语音报错：json f "stack": "Error: Failed to execut e 'decodeAudioData' on 'BaseAudioCo ntext': Unable to decode audio data" 请问除了页面设置之外还需要配置其他地方么?

确定一下是否可以使用 openai 的 tts 模型

**Comment by ofllm** [comment]
> > 点击语音报错：json f "stack": "Error: Failed to execut e 'decodeAudioData' on 'BaseAudioCo ntext': Unable to decode audio data" 请问除了页面设置之外还需要配置其他地方么?
> 
> 确定一下是否可以使用 openai 的 tts 模型

手动调用api发现无法正常使用tts模型，感谢大佬回复，谢谢。

**Comment by zpng** [comment]
@Hk-Gosuto 大佬，语音输入的最终的效果是什么样的？需要key支持什么模型？readme上写的需要https访问是指网址需要https域名吗，这个的原因是？

**Comment by Hk-Gosuto** [comment]
设置里开启后，发送按钮会变成语音输入，点击后开始说话，说完再点停止就行。
具体技术使用的是 SpeechRecognition API 不需要设置 key，关于浏览器兼容性可以参考：https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition
SpeechRecognition API 在大多数浏览器中要求使用HTTPS才能正常工作。

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/107011a9-93b3-4822-9926-d076d63e0306)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/388453b5-5c4e-4be4-8bf8-b8d01559e996)

**Comment by zpng** [comment]
> 设置里开启后，发送按钮会变成语音输入，点击后开始说话，说完再点停止就行。 具体技术使用的是 SpeechRecognition API 不需要设置 key，关于浏览器兼容性可以参考：https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition SpeechRecognition API 在大多数浏览器中要求使用HTTPS才能正常工作。
> 
> ![image](https://private-user-images.githubusercontent.com/14031260/312761075-107011a9-93b3-4822-9926-d076d63e0306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDYwMzIsIm5iZiI6MTcxMDQwNTczMiwicGF0aCI6Ii8xNDAzMTI2MC8zMTI3NjEwNzUtMTA3MDExYTktOTNiMy00ODIyLTk5MjYtZDA3NmQ2M2UwMzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA4NDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMzA3YmU1NTMzNDg4ZjM0ZTYyMmY3MDc3YzdlMDc0MWQxNTJlNGZiYWU1NTY1NmMyOWExZWY5ZjI5MGQ2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oWzcJRaoZbbgZqSx-Rg1wnBXHo_K_9u1Ly3iW_SAmAQ) ![image](https://private-user-images.githubusercontent.com/14031260/312761327-388453b5-5c4e-4be4-8bf8-b8d01559e996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDYwMzIsIm5iZiI6MTcxMDQwNTczMiwicGF0aCI6Ii8xNDAzMTI2MC8zMTI3NjEzMjctMzg4NDUzYjUtNWM0ZS00YmU0LThiZjgtYjhkMDE1NTllOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA4NDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOGUxZTRhNTVmOGNhNzhkN2EwODE3NDM3NzA2MmMzMDBiZGQyNzg2MTYyNmFkMTRmOTI1YmRlMDUyMzZhM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJUwMh7CGoj5ZODWND1A2cNPs_KR4yVQ6Ya8l4AWOvE)

这个为啥不是通过调用openai的api实现的？

**Comment by Hk-Gosuto** [comment]
这个不收费，识别效果也挺好的，为啥要用 wishper？

**Comment by zpng** [comment]
噢噢好的

**Comment by Hk-Gosuto** [comment]
可以多试一些场景，如果复杂场景效果不好的话，后面会考虑增加 wishper 适配。

**Comment by jcr8745dqy100** [comment]
当使用openai tts时，每一次让它说，都会重新申请一次tts请求，能不能第一次就把语音下载到本地，过后重新听就不浪费请求了

**Comment by Hk-Gosuto** [comment]
> 当使用openai tts时，每一次让它说，都会重新申请一次tts请求，能不能第一次就把语音下载到本地，过后重新听就不浪费请求了

我看看能不能把音频丢 indexedDB 里，可以先切换到 edge tts 那个不产生费用。
