### ISSUE TITLE
Image not displaying after generation [Bug] 

### ISSUE THREAD

**Issue by crypticatul** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#21]
**Describe the bug**
Dall-E Generated Image not showing in the app.
**To Reproduce**
Ask to generate any Image, plugin gets activated and it replies with an image , but the image is not showing up in the app.

**Expected behavior**
Images should be visible after generation.

**Screenshots**
<img width="724" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/88734298/eed015f7-138f-444f-ad80-8f9fe1fbb139">

**Deployment**
- [ ] Vercel

**Additional Logs**
Add any logs about the problem here.

On Inspect element in browser it shows following error in console:

 https://chatgptweb.vercel.com/api/file/1695043350537.png 401 (Unauthorized)
Image (async)
ag @ bce60fc1-76a57db123ee8dbb.js:9
ay @ bce60fc1-76a57db123ee8dbb.js:9
aT @ bce60fc1-76a57db123ee8dbb.js:9
ay @ bce60fc1-76a57db123ee8dbb.js:9
aT @ bce60fc1-76a57db123ee8dbb.js:9
ay @ bce60fc1-76a57db123ee8dbb.js:9
aT @ bce60fc1-76a57db123ee8dbb.js:9
ay @ bce60fc1-76a57db123ee8dbb.js:9
......
aT | @ | bce60fc1-76a57db123ee8dbb.js:9
-- | -- | --
  | ay | @ | bce60fc1-76a57db123ee8dbb.js:9
  | (anonymous) | @ | bce60fc1-76a57db123ee8dbb.js:9
  | oO | @ | bce60fc1-76a57db123ee8dbb.js:9
  | nG | @ | bce60fc1-76a57db123ee8dbb.js:9
  | nJ | @ | bce60fc1-76a57db123ee8dbb.js:9
  | (anonymous) | @ | bce60fc1-76a57db123ee8dbb.js:9

**Comment by Hk-Gosuto** [comment]
Is the file present in the bucket of Cloudflare R2?

**Comment by crypticatul** [comment]
No, no files in R2.

**Comment by Hk-Gosuto** [comment]
Please check the following environment variable configuration.
And the permission configuration when creating a token.
If none of the solutions work, you can apply for a temporary token to provide me with for troubleshooting.
- R2_ACCOUNT_ID
- R2_ACCESS_KEY_ID
- R2_SECRET_ACCESS_KEY
- R2_BUCKET

**Comment by crypticatul** [comment]
Hi, thanks for the suggestion and the updated code. The R2_SECRET_ACCESS_KEY in env was wrong and with the latest code, its now working.

**Comment by crypticatul** [comment]
Hi, thanks for the suggestion and the updated code. The R2_SECRET_ACCESS_KEY in env was wrong and with the latest code, its now working.
