### ISSUE TITLE
[Bug] 升级2.10.3版本之后，如果在环境变量中同时设置了code 和 google_api_key，则gemini-pro必须填code才能使用，而OpenAI的模型不需要，只要在自定义接口中填入API Key即可使用。

### ISSUE THREAD

**Issue by zhangbinhui** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#214]
**Describe the bug**
作者大大，升级2.10.3版本之后，如果在环境变量中同时设置了code 和 google_api_key，则gemini-pro必须填code才能使用，而OpenAI的模型不需要，只需要在自定义接口中填入API Key即可使用。在升级这个版本之前，只要在 自定义接口中 填入 API Key(OpenAI的)就可以直接使用gemini-pro，不晓得这次更新是有意如此还算是bug。

我截图说明一下情况：

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/7031406/21db1d9b-2549-4288-b470-8f6d8694a849)
我在自定义接口中填了 API Key，没有填访问密码，这个时候OpenAI的模型可以正常使用，而gemini-pro会报错empty access code.

而当我把访问密码也填上的时候，则可以正常使用gemini-pro；

![langchain_bug](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/7031406/8237eb2e-39b7-4840-ab91-bd348a258e26)
这个图包含了，在隐私模式下，我填 和 不填 访问密码，在使用gemini-pro的两种情况。

我不确定是否作者大大有意如此，还是说这个算是个bug。

**Comment by Hk-Gosuto** [comment]
我使用的是示例的线上环境 https://n3xt.chat，按照你的描述，线上环境是有配置 `code` 的，我在不填写访问密码的情况下配置了 openai 和 google 的密钥，是可以正常使用的，具体配置如下：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/80f96356-1801-439d-9d87-955e7094b1ef)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/65368d89-6ffd-430f-9d6f-5abb2acfdb37)
看你截图中的模型服务商是 openai 是否是 google 的密钥未配置？

**Comment by zhangbinhui** [comment]
> 我使用的是示例的线上环境 [https://n3xt.chat，按照你的描述，线上环境是有配置](https://n3xt.chat%EF%BC%8C%E6%8C%89%E7%85%A7%E4%BD%A0%E7%9A%84%E6%8F%8F%E8%BF%B0%EF%BC%8C%E7%BA%BF%E4%B8%8A%E7%8E%AF%E5%A2%83%E6%98%AF%E6%9C%89%E9%85%8D%E7%BD%AE) `code` 的，我在不填写访问密码的情况下配置了 openai 和 google 的密钥，是可以正常使用的，具体配置如下： ![image](https://private-user-images.githubusercontent.com/14031260/309947314-80f96356-1801-439d-9d87-955e7094b1ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTA0MDgsIm5iZiI6MTcwOTYxMDEwOCwicGF0aCI6Ii8xNDAzMTI2MC8zMDk5NDczMTQtODBmOTYzNTYtMTgwMS00MzlkLTlkODctOTU1ZTcwOTRiMWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAzNDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YTM3NmZkYTQ4OWY5OTIwMTBjZmMxYTcwNzA4NGU3ZjAwYWU5ZDhmNDAyOTFkZjk5MGE5MGNmZGRmNTkwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PVWyAjNd5NWaDQiFvIdPziWSq-jEQE6UcFoQI-JTHVs) ![image](https://private-user-images.githubusercontent.com/14031260/309947434-65368d89-6ffd-430f-9d6f-5abb2acfdb37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTA0MDgsIm5iZiI6MTcwOTYxMDEwOCwicGF0aCI6Ii8xNDAzMTI2MC8zMDk5NDc0MzQtNjUzNjhkODktNmZmZC00MzBmLTlkNmYtNWFiYjJhY2ZkYjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAzNDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZTdkYTZiMTE1MjA0NjUzMjI2ZmQ2ZDhkNzBiYzRlZGEwZmUxNDQ1Y2FlMWZmMzA0MWU0MTA4MTUyZDhlNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LcF57yPSpry_jsPBUmDyyC0cIX6T1IyqIC8Rpk5zDvw) 看你截图中的模型服务商是 openai 是否是 google 的密钥未配置？

感谢大大的回复，我是把google 的密钥 和 openai的密钥都配置在后台的环境变量了，如果我填了访问密码，可以正常使用这两个模型。
google的key是免费的，不需要更换，而openai的key因为不是免费的，环境变量里的用完了在后台换比较麻烦，我就会在前端页面填一个新的openai的 API key填进去。
以前只要填了OpenAI的key，不需要填访问密码，也能正常使用gemini，但是2.10.3之后就不行了，必须把访问密码也填上才能继续使用gemini。
我想反馈的是这次交互逻辑上的变化，当然，这个算不算bug作者大大您定吧，我以前那样用惯了，现在无非就是还得再填个访问密码才能用Gemini。不晓得表达清楚没有。

**Comment by Hk-Gosuto** [comment]
正常来说如果后台配置了访问密码和 key，那在不使用 UI 配置接口密钥的时候是必须填写访问密码。
如果之前只是在 UI 填写 openai 的接口密钥就可以访问到后台配置的 gemini 模型其实才是不正常的。

**Comment by zhangbinhui** [comment]
> 正常来说如果后台配置了访问密码和 key，那在不使用 UI 配置接口密钥的时候是必须填写访问密码。 如果之前只是在 UI 填写 openai 的接口密钥就可以访问到后台配置的 gemini 模型其实才是不正常的。

感谢回答，那这个过了。顺便提一嘴界面上的改动点，NextChat最新版本已经支持传图，他们也做了传图的按钮，跟您这边略有不同，传图的效果也不同，NextChat面板支持多图上传，这个您是否考虑同步呢？
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/7031406/b8444c35-37ea-49a5-b4bd-99b8842cc1b9)

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/7031406/de27bbe0-f6b1-4216-a127-e83b5be32138)

**Comment by Hk-Gosuto** [comment]
这块的变动有点大，会晚一些，本周内会同步。

**Comment by zhangbinhui** [comment]
> 这块的变动有点大，会晚一些，本周内会同步。

谢谢！
