### ISSUE TITLE
请问如何触发搜索功能？

### ISSUE THREAD

**Issue by Timoshao** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#22]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
感觉搜索功能时好时坏的，有时候触发了有时候又没有触发

**如何复现**
连续对话

**截图**
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/108260847/45c85d32-bbcb-4fb3-8e7f-b0869287f5c1)

**一些必要的信息**
 - 系统：windows 11
 - 浏览器：chrome
 - 版本：V2.9.6
 - 部署方式：本地部署

**Comment by Hk-Gosuto** [comment]
是否调用插件以及什么时候调用插件是由 GPT 自己决定的，在每次调用时会发送当前的插件列表到模型接口。
其中包括：插件名称，描述，以及函数签名等。
如果想触发一些插件可以在 prompt 中进行引导，比如：帮我在网上搜索xxx、使用wiki查找xxx、计算xxxxx等等
