### ISSUE TITLE
[Feature] 支持 OpenAI Whisper

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#226]
### Bug Description

语音输入只能翻墙的时候使用，不翻墙语音不能用，说话之后文字在输入框无展示。
另外希望大佬可以把语音开关调整下，改成类似微信的交互，放到输入框加个类似开关，不然太不方便使用了，需要来回到设置中去切换。

### Steps to Reproduce

语音输入只能翻墙的时候使用，不翻墙语音不能用，说话之后文字在输入框无展示。
另外希望大佬可以把语音开关调整下，改成类似微信的交互，放到输入框加个类似开关，不然太不方便使用了，需要来回到设置中去切换。

### Expected Behavior

预期不翻墙也可以用语音输入的功能。
另外希望大佬可以把语音开关调整下，改成类似微信的交互，放到输入框加个类似开关，不然太不方便使用了，需要来回到设置中去切换。

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

mac 13.6 (22G120)

### Desktop Browser

chrome

### Desktop Browser Version

版本 121.0.6167.184（正式版本） (x86_64)

**Comment by Hk-Gosuto** [comment]
edge 和 safari 都不需要代理

**Comment by Hk-Gosuto** [comment]
文字输入按快捷键也可以正常发送

**Comment by zpng** [comment]
> edge 和 safari 都不需要代理

那chrome用不了，很不方便，而且还有个问题 手机微信自带的浏览器上也用不了，点击说话然后停止之后，没有文字的显示，希望大佬解决下这俩问题，非常影响使用~

**Comment by zpng** [comment]
> 文字输入按快捷键也可以正常发送

另外希望同时保留说话和发送两个按钮呢，不只是通过快捷键发送~

**Comment by Hk-Gosuto** [comment]
有更好的设计可以简单画个原型图，或者有能力提个 pr 过来更好。
按现有的样式放两个按钮看着会很别扭，所以就先弄成现在这样了。

**Comment by Hk-Gosuto** [comment]
> > edge 和 safari 都不需要代理
> 
> 那chrome用不了，很不方便，而且还有个问题 手机微信自带的浏览器上也用不了，点击说话然后停止之后，没有文字的显示，希望大佬解决下这俩问题，非常影响使用~

这是浏览器本身的特性支持，微信的内置浏览器有很多限制，不建议在微信内置的浏览器下使用。

**Comment by zpng** [comment]
> > > edge 和 safari 都不需要代理
> > 
> > 
> > 那chrome用不了，很不方便，而且还有个问题 手机微信自带的浏览器上也用不了，点击说话然后停止之后，没有文字的显示，希望大佬解决下这俩问题，非常影响使用~
> 
> 这是浏览器本身的特性支持，微信的内置浏览器有很多限制，不建议在微信内置的浏览器下使用。

但是需要翻墙才能用，这样就基本不可用了呢，这个大佬可以修一下不，或者改一下实现方式，通过调用openai的请求去实现？

**Comment by zpng** [comment]
> > > > edge 和 safari 都不需要代理
> > > 
> > > 
> > > 那chrome用不了，很不方便，而且还有个问题 手机微信自带的浏览器上也用不了，点击说话然后停止之后，没有文字的显示，希望大佬解决下这俩问题，非常影响使用~
> > 
> > 
> > 这是浏览器本身的特性支持，微信的内置浏览器有很多限制，不建议在微信内置的浏览器下使用。
> 
> 但是需要翻墙才能用，这样就基本不可用了呢，这个大佬可以修一下不，或者改一下实现方式，通过调用openai的请求去实现？


@Hk-Gosuto remind 大佬这个可以修一下不，感谢~

**Comment by Hk-Gosuto** [comment]
后面会增加 wishper 支持

**Comment by zpng** [comment]
赞，期待～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hk-Gosuto ***@***.***&gt;
发送时间: 2024年3月17日 11:24
收件人: Hk-Gosuto/ChatGPT-Next-Web-LangChain ***@***.***&gt;
抄送: zpng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Hk-Gosuto/ChatGPT-Next-Web-LangChain] [Bug]  语音输入只能翻墙的时候使用，不翻墙语音不能用 (Issue #226)





 
后面会增加 wishper 支持

**Comment by zpng** [comment]
@Hk-Gosuto 大佬  支持whisper这个开发啥进度了？
