### ISSUE TITLE
[Bug] 移动端聚焦文本框时窗口会被放大且不会复原

### ISSUE THREAD

**Issue by adolphnov** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#228]
### Bug Description

移动端：在键入文本时，输入窗口会自动放大且不会复原

### Steps to Reproduce

1. 选择任意一个文本框（例如设置-访问密码）
2. 选中，准备键入文本
3. 结果：页面被放大
4. 键盘选择完成输入，页面仍处于放大状态
5. 手动手势缩小，能够恢复正常

### Expected Behavior

选中文本框时，页面不会放大

### Screenshots

![光标在输入框中](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/30210690/2e58ab01-9029-43f1-adc2-531050fa3428)
![键入完成](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/30210690/36ae62f9-e0c4-43a5-a312-ca32e51b4128)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Smartphone Device

iPhone 13 pro max

### Smartphone OS

iOS 15.6.1

### Smartphone Browser

Safari

**Comment by MuRo-J** [comment]
辛苦作者大大，伴随一个移动端按钮的小问题，语音按钮对于输入框内部内容有覆盖，![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/64354330/6d1e26cd-c03e-4d6a-bbeb-a71a8ae2336f)![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/64354330/e9396e04-d594-48b2-b769-17f4ef7871c8)

**Comment by Hk-Gosuto** [comment]
> 辛苦作者大大，伴随一个移动端按钮的小问题，语音按钮对于输入框内部内容有覆盖，![image](https://private-user-images.githubusercontent.com/64354330/313196548-6d1e26cd-c03e-4d6a-bbeb-a71a8ae2336f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NDE5NjEsIm5iZiI6MTcxMDY0MTY2MSwicGF0aCI6Ii82NDM1NDMzMC8zMTMxOTY1NDgtNmQxZTI2Y2QtYzAzZS00ZDZhLWJiZWItYTcxYThhZTIzMzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAyMTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZmVmMTQ3NjY2ZDc1OWI5MTIzY2I0ZmNhZWM2MTY5Y2JhOWVmOTI3YmZjZjZkMDQwMjQ4YTkxMGRmMTE2NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PuJBQEPLO-ipSdKWju_R2XNZ-veYZeTRC6SOfjVFuno)![image](https://private-user-images.githubusercontent.com/64354330/313196589-e9396e04-d594-48b2-b769-17f4ef7871c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NDE5NjEsIm5iZiI6MTcxMDY0MTY2MSwicGF0aCI6Ii82NDM1NDMzMC8zMTMxOTY1ODktZTkzOTZlMDQtZDU5NC00OGIyLWI3NjktMTdmNGVmNzg3MWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAyMTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ODBhMDNkMTA2YWYyMjhjYjk3ODg4MGE3NWZkM2IyYmNmZGRkNGFmZmNhMjY4ZWZjNGE0OTIxYmJiYzJlMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eyPZU6MxF5wQpYcLiZ1gEsv0ZmIHFG2T-tLGttztflk)

覆盖的问题更新下最新的代码，按钮和 icon 在手机端不显示的问题已经修复了。
