### ISSUE TITLE
[Bug]  拉取了最新代码部署之后，首次加载网址巨慢，之前几秒钟，现在每次都要几十秒甚至分钟级

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#229]
### Bug Description

拉取了最新代码部署之后，首次加载网址巨慢，之前几秒钟，现在每次都要几十秒甚至分钟级

### Steps to Reproduce

拉取了最新代码部署之后，首次加载网址巨慢，之前几秒钟，现在每次都要几十秒甚至分钟级
电脑端和手机端都是，拉取巨慢

### Expected Behavior

期待输入网址后网页加载几秒钟就完成

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

mac 13.6 (22G120)

### Desktop Browser

chrome

### Desktop Browser Version

版本 121.0.6167.184（正式版本） (x86_64)

### Smartphone Device

iphone 12pro

### Smartphone OS

ios 17.3.1

### Smartphone Browser

safari 或者 微信自带浏览器

**Comment by Hk-Gosuto** [comment]
请检查是否为网络问题

**Comment by zpng** [comment]
不是网络问题，是同样的网络合并代码之前很快，现在就很慢，很奇怪。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hk-Gosuto ***@***.***&gt;
发送时间: 2024年3月17日 10:14
收件人: Hk-Gosuto/ChatGPT-Next-Web-LangChain ***@***.***&gt;
抄送: zpng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Hk-Gosuto/ChatGPT-Next-Web-LangChain] [Bug]  拉取了最新代码部署之后，首次加载网址巨慢，之前几秒钟，现在每次都要几十秒甚至分钟级 (Issue #229)





 
请检查是否为网络问题

**Comment by Hk-Gosuto** [comment]
可以监视一下网络请求，看下是什么文件或者什么接口的请求比较慢，我这里并不能复现这个问题。

**Comment by zpng** [comment]
> 可以监视一下网络请求，看下是什么文件或者什么接口的请求比较慢，我这里并不能复现这个问题。

我看你刚又有新的提交，我重新拉了合并了，部署好之后，网络访问又变快了~

**Comment by Hk-Gosuto** [comment]
可能是 nextjs 的问题，之前更新了版本发现对移动端兼容性有些问题，现在回退了。

**Comment by zpng** [comment]
> 可能是 nextjs 的问题，之前更新了版本发现对移动端兼容性有些问题，现在回退了。

噢噢好的
