### ISSUE TITLE
[Bug] iphone上浏览器safari 录音只能录0.98s 语音，且不准确

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#234]
### Bug Description

语音输入在mac上chrome浏览器可用，但是手机上不行
iphone上浏览器safari 录音只能录0.98s 语音，且不准确。
很奇怪每次固定只能录0.98s
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/daedd9f9-3df6-4ed7-b416-25b72bd1f898)

### Steps to Reproduce

iphone上用safari打开浏览器，然后打开语音开关，点击说话，可以看到返回的文字很乱，不对，看后台发现只能录0.98s。很奇怪。

### Expected Behavior

期待iphone手机上可以正常语音输入。

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Smartphone Device

iphone 12pro

### Smartphone OS

ios 17.3.1

### Smartphone Browser

safari

**Comment by Hk-Gosuto** [comment]
https://community.openai.com/t/whisper-problem-with-audio-mp4-blobs-from-safari/322252
