### ISSUE TITLE
[Bug]  tauri mac桌面客户端语音输入不能使用，点击说话然后停止之后一直卡在三个点

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#235]
### Bug Description

tauri mac桌面客户端语音输入不能使用，点击说话然后停止一直卡在三个点，不能有有效的输入和请求进去

### Steps to Reproduce

编译打包mac客户端，打开语音输入开关，点击说话，然后停止，一直卡在三个点，不能有有效的输入和请求进去

### Expected Behavior

预期可以输入进去语音数据

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

mac 13.6 (22G120)

### Desktop Browser

tauri客户端

**Comment by Hk-Gosuto** [comment]
客户端问题不在本项目处理范围，短时间不会考虑支持客户端。
