### ISSUE TITLE
[Bug] Firefox下报错

### ISSUE THREAD

**Issue by A2Sumie** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#236]
### Bug Description

图片一个是本地一个是这里的示范站，vercel的也和示范那样
Firefox 124.0.1，MacOS 14.3/Windows11，尝试了无插件运行问题照旧
移动端124也是爆了的
服务端日志没有什么异常
不知道是上游带过来的还是什么情况

### Steps to Reproduce

使用Firefox浏览

报错，无法使用

### Expected Behavior

正常访问

### Screenshots

<img width="1444" alt="图片" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/89308692/0e3e3940-abc8-4fcc-90db-ea487a7f6543">
<img width="1515" alt="图片" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/89308692/dd2e428e-2527-44a9-8f1f-1d9baad59c97">

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

**Comment by Hk-Gosuto** [comment]
SpeechRecognition API 浏览器兼容性的问题，晚点我试试在 firefox 禁用这个 API
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/SpeechRecognition
