### ISSUE TITLE
Giga chat

### ISSUE THREAD

**Issue by den47999** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#237]
### Problem Description

Hi, I'm facing a problem with chat behavior when making a simple request, for example: "Hi" - chat displays the answer normally, but if, for example, I ask to write code, the chat response is written in a jerky way. That is, I asked to write "Write a calculator in Python using PyQt libraries" - chat wrote 600 lines of code on the screenshot I showed how it happens. Please help in solving the problem of displaying the response.
import sys

fro

fr

f
from PyQt5.QtWidgets import QApplication, QWidget, QGridLayout, QPushButton, QLineEdit

clas

cla

cl

c
class Calculator(QWidget):
    
    d

    

   

  

 
def __init__(self):
        
        supe

        sup

        su

        s

        

       

     

    

   

  
super().__init__()
        self.setWindowTitle(
        self.setWindow

        self

        sel

        se

        

       

      

     

    

   

  

 
"Калькулятор")
        self.setGeometry(
        self.setGeo

        s
300, 300, 300, 300)

        self.display = QLineEdit()
        self.display.setReadOnly(

        self.display = QLineEdit()
        self.display.setReadOnly

        self.display = QLineEdit()
        self.display.

        self.display = QLineEdit()
        self.dis

        self.display = QLineEdit()
        

        self.display = QLineEdit()

        self.display = QLin

        self.displ

        s

True)
        self.display.setAlignment(Qt.AlignRight)

        self.grid = QGridLayout()
        self.grid.addWidget(self.display, 
        self.display.setAlignment(Qt.AlignRight)

        self.grid = QGridLayout()
        self.grid.addWidget(self.disp

        self.display.setAlignment(Qt.AlignRight)

        self.grid = QGridLayout()
        self.grid.addWidget(sel

        self.display.setAlignment(Qt.AlignRight)

        self.grid = QGridLayout()
        self.grid.addWidg

        self.display.setAlignment(Qt.AlignRight)

        self.grid = QGridLayout()
        self.grid.a

        self.display.setAlignment(Qt.AlignRight)

        self.grid = QGridLayout()
        self.

        self.display.setAlignment(Qt.AlignRight)

        self.grid = QGridLayout()
       

        self.display.setAlignment(Qt.AlignRight)

        self.grid = QGridLayo

        self.display.setAlignment(Qt.AlignRight)

        self.gri

        self.display.setAlignment(Qt.AlignRight)

        s

        self.display.setAlignment(Qt.AlignRig

        self.display.setAlignme

        self.display.
        s

 
0, 0, 1, 4)

        buttons = [

        buttons = [

        button

        b

    
'7', '8', '9', '/',
                   
                   

               

          

     
'4', '5', '6', '*',
                   
                

        

    
'1', '2', '3', '-',
                   
                  

               

            

         

      

   
'0', '.', '=', '+']

        positions = [(i, j) 

        positions = [(i, j) f

        positions = [(i, j)

        positions = [(i, 
![Screenshot_1](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/118296790/cab575d3-7988-43fd-a3dc-c6c8f9df66fb)
![Screenshot_2](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/118296790/58d8356f-22ee-4746-8b31-c171fc14d5f9)
![Screenshot_3](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/118296790/34454a3a-7ba9-411d-8119-6bad88c6c8ea)
![Screenshot_4](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/118296790/dcb19f1f-267f-49d5-aeed-c8a3bf42bdab)

### Solution Description

the mapping should be:
python
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLineEdit, QPushButton, QVBoxLayout
from PyQt5.QtCore import QCoreApplication

class Calculator(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setGeometry(300, 300, 300, 300)
        self.setWindowTitle('Calculator')

        self.display = QLineEdit()
        self.display.move(10, 10)
        self.display.resize(280, 40)

        self.clearButton = QPushButton('C', self)
        self.clearButton.move(10, 50)
        self.clearButton.clicked.connect(self.clearDisplay)

        self.seven = QPushButton('7', self)
        self.seven.move(10, 80)
        self.seven.clicked.connect(self.addNumber)

        self.eight = QPushButton('8', self)
        self.eight.move(100, 80)
        self.eight.clicked.connect(self.addNumber)

        self.nine = QPushButton('9', self)
        self.nine.move(10, 110)
        self.nine.clicked.connect(self.addNumber)

        self.divide = QPushButton('/', self)
        self.divide.move(100, 110)
        self.divide.clicked.connect(self.addOperator)

        self.four = QPushButton('4', self)
        self.four.move(10, 140)
        self.four.clicked.connect(self.addNumber)

        self.five = QPushButton('5', self)
        self.five.move(100, 140)
        self.five.clicked.connect(self.addNumber)

        self.six = QPushButton('6', self)
        self.six.move(10, 170)
        self.six.clicked.connect(self.addNumber)

        self.multiply = QPushButton('*', self)
        self.multiply.move(100, 170)
        self.multiply.clicked.connect(self.addOperator)

        self.one = QPushButton('1', self)
        self.one.move(10, 200)
        self.one.clicked.connect(self.addNumber)

        self.zero = QPushButton('0', self)
        self.zero.move(100, 200)
        self.zero.clicked.connect(self.addNumber)

        self.equals = QPushButton('=', self)
        self.equals.move(10, 230)
        self.equals.clicked.connect(self.calculate)

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.display)
        self.layout.addWidget(self.clearButton)
        self.layout.addWidget(self.seven)
        self.layout.addWidget(self.eight)
        self.layout.addWidget(self.nine)
        self.layout.addWidget(self.divide)
        self.layout.addWidget(self.four)
        self.layout.addWidget(self.five)
        self.layout.addWidget(self.six)
        self.layout.addWidget(self.multiply)
        self.layout.addWidget(self.one)
        self.layout.addWidget(self.zero)
        self.layout.addWidget(self.equals)
        self.setLayout(self.layout)

    def addNumber(self):
        self.display.setText(self.display.text() + str(self.sender().text()))

    def clearDisplay(self):
        self.display.clear()

    def addOperator(self):
        if self.display.text() != '':
            self.display.setText(self.display.text() + str(self.sender().text()))
        else:
            self.display.setText(str(self.sender().text()))

    def calculate(self):
        try:
            result = eval(self.display.text())
            self.display.setText(str(result))
        except:
            self.display.setText('Error')

app = QApplication(sys.argv)
calc = Calculator()
calc.show()
sys.exit(app.exec_())

**Comment by den47999** [comment]
через веб версию отображается отлично
![Screenshot_1](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/118296790/77434a44-511f-48ea-a4d1-01b24dad0e5a)
через локальную версию плохо
![Screenshot_2](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/118296790/d92293ae-1766-4de9-be03-570b173415f8)

**Comment by Hk-Gosuto** [comment]
I don't understand the scene where this problem occurs.
What model are you using?

**Comment by den47999** [comment]
giga chat, deepseek-coder (https://platform.deepseek.com/docs), gemeni

**Comment by den47999** [comment]
я так же проверял с другими моделями и так же через веб deepseek-coder ( https://platform.deepseek.com/docs ), Gemeni

**Comment by den47999** [comment]
I found the problem why it was displayed like that :) I used to use Chromium Portable browser! Now I use a simple browser and the display is perfect!
![Screenshot_2](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/118296790/da8cfcb4-8421-418e-a5a5-7da4739b4966)
![Screenshot_3](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/118296790/c5121498-cf3b-4d73-8b15-7425700bc147)
