### ISSUE TITLE
v2.11.3 docker 启动添加PROXY_URL会导致页面无法显示[Bug] 

### ISSUE THREAD

**Issue by cookieY** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#238]
### Bug Description

v2.11.3 docker 启动添加PROXY_URL会导致页面无法显示，不添加则正常启动

使用v2.11.2版本的镜像添加PROXY_URL可正常启动

### Steps to Reproduce

docker run -d -p 3000:3000 \
   -e PROXY_URL="http://10.10.0.2:7893"  gosuto/chatgpt-next-web-langchain:v2.11.2   可以正常启动
   
docker run -d -p 3000:3000 \
   -e PROXY_URL="http://10.10.0.2:7893"  gosuto/chatgpt-next-web-langchain:v2.11.3   页面无法显示

查看日志无任何报错信息

### Expected Behavior

得到修复

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
删掉重新拉一下最新的试试：
```bash
docker rmi gosuto/chatgpt-next-web-langchain:v2.11.3
```

**Comment by cookieY** [comment]
已解决，感谢
