### ISSUE TITLE
使用DALL-E插件时图片无法显示

### ISSUE THREAD

**Issue by happychos** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#24]
使用DALL-E插件时图片无法显示，连续尝试几次都是如此，但是在R2中是有文件生成的
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/139939316/c3919f59-f418-4c6e-9e22-b5359d042f05)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/139939316/9227f180-87cb-49e1-84ea-9afb9a7e49d4)

**Comment by Hk-Gosuto** [comment]
直接请求 /api/file/xxxx.png 这个路由（图片换成已经上传的），然后看下请求日志中有没有错误信息。

**Comment by mouxangithub** [comment]
同样的问题，好像S3的域是访问不了不对外的，配了个R2.dev 子域或者自定义域就可以用这两个域名访问

**Comment by mouxangithub** [comment]
> 直接请求 /api/file/xxxx.png 这个路由（图片换成已经上传的），然后看下请求日志中有没有错误信息。

看了下确实是图片跨域不对外访问的问题，可以加个图片域配置，S3域是不对外访问

**Comment by Hk-Gosuto** [comment]
这个是接口鉴权的问题导致的，目前已将该接口的鉴权移除了，更新到最新的主分支代码再尝试一下。
