### ISSUE TITLE
[Bug]  输出结果显示问题

### ISSUE THREAD

**Issue by zpng** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#240]
### Bug Description

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/8509438/1de3da18-84de-4439-ac41-e2ef5ec8149b)

$3^{100}$ 的结果大约为 $5.153775207320113 \times 10^{47}$。这是一个非常大的数字！
如上所示，显示有问题

### Steps to Reproduce

见上文

### Expected Behavior

预期显示正常

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4167
上游仓库已存在相关问题
