### ISSUE TITLE
[Feature Request]: 关于RAG 功能的用法

### ISSUE THREAD

**Issue by laye0619** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#244]
### Problem Description

请教一下大神，我已经按照https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/rag-cn.md#rag-功能配置说明 的要求配置了，也申请了cloudflare r2并配置好了，我是本地docker部署，环境变量已经都加上了，想请教一下如何实现
![](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/raw/main/docs/images/rag-example.jpg)
这里面的功能，模型上我选择了gpt-4*的所有模型，除了vision- preview可以看到对话框跳出来上传图片按钮，其余并没有任何上传文件的按钮出现，请问这应该怎么使用

### Solution Description

希望得到关于RAG 功能的用法的指导

**Comment by Hk-Gosuto** [comment]
pull 一下最新的 gosuto/chatgpt-next-web-langchain:nightly 模型，我是今天中午才上传的。

**Comment by laye0619** [comment]
使用nightly镜像暂时还是没有上传按钮，使用最新的code部署在vercel上也是没有。请问使用openai官方接口 模型gpt-4-turbo-preview应该可以使用这个功能吗？

**Comment by Hk-Gosuto** [comment]
所有的 openai 模型，除了视觉模型都可以使用上传，检查一下环境变量 `ENABLE_RAG` 是否配置正确，docker 版本可以使用下面的命令测试：
```bash
docker run --rm -it -p 3000:3000 -e ENABLE_RAG=1 gosuto/chatgpt-next-web-langchain:nightly
```
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/0b3c494c-63d9-400a-abeb-f6dbbbbe8c26)

**Comment by laye0619** [comment]
十分感谢！修改了docker环境变量，之前加了NEXT_PUBLIC前缀，现在有了文件上传按钮。试了一下，上传了一个英文PDF，在R2中也确实可以看到了，但是问AI问题好像回答不了，自动去调用了Web- Browser插件了（如图）。我看到您的截图里面是会去调用rag-search插件，但是我在插件列表里面没有看到这个插件？
<img width="975" alt="Screenshot 2024-04-09 at 09 42 06" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/9484313/1fd80705-8768-4696-bbd2-e9592c0116ba">

**Comment by Hk-Gosuto** [comment]
可以先关闭其他插件或者使用 gpt4

**Comment by laye0619** [comment]
> 可以先关闭其他插件或者使用 gpt4

关闭了其它插件，并使用gpt-4后，可以调用rag-search了，但是对于文件访问好像还是有些问题，我直接在对话框中点击文件是可以打开的，在r2中也是可以看到文件的：）

**Comment by Hk-Gosuto** [comment]
检查一下 qdrant 仪表盘确认一下向量库是否有正确被创建
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/d4944fec-6a83-425f-91b5-e3aa185923e0)

**Comment by laye0619** [comment]
打开Dashboard后没有看到Collection
<img width="1599" alt="Screenshot 2024-04-09 at 10 08 37" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/9484313/fab26712-a226-480a-a894-1aa2abbc33cd">

**Comment by Hk-Gosuto** [comment]
向量库没有正确被创建，检查一下程序日志看看是否有相关错误信息。

**Comment by laye0619** [comment]
使用docker部署的查询文件就没有创建向量库，但是使用vercel部署的就可以创建向量库，可是返回了这个错误
![Uploading Screenshot 2024-04-09 at 10.31.27.png…]()

**Comment by Hk-Gosuto** [comment]
因为 Qdrant SDK 需要 nodejs 环境，如果要在 vercel 使用必须配置环境变量 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN=1`。
不过需要注意的是，在 vercel 使用 nodejs 运行时会有接口超时风险，还是建议在 docker 下使用。

**Comment by laye0619** [comment]
明白了，设置了环境变量，可以使用了，十分感谢！

**Comment by laxfer** [comment]
经过反复测试，RAG模式下，其他插件都会存在干扰，所以，在RAG模式下，就不会再加载别的插件
