### ISSUE TITLE
[Bug] 文本转语音功能报错：EncodingError: Decoding failed

### ISSUE THREAD

**Issue by laye0619** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#245]
### Bug Description

尝试使用文本转语音功能报错，同样的API Key在LobeChat中文本转语音（模型使用tts-1）就是正常的。错误信息如下
<img width="629" alt="Screenshot 2024-04-09 at 08 25 17" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/9484313/d676d071-0d99-4b90-9ec2-36ab97c3efdd">

### Steps to Reproduce

设置中启用文本转语音功能，模型选择tts-1或者tts-1-hd
在对话中随便选择一条文字，点击“朗读”
出错如上图

### Expected Behavior

可以正常朗读

### Deployment Method

- [X] Docker
- [X] Vercel
- [ ] Server

**Comment by laye0619** [comment]
还是不行，三张图对比一下：
1. 使用docker部署您的项目
<img width="356" alt="Screenshot 2024-04-09 at 09 51 19" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/9484313/e3a51ed9-0d1a-4fd3-82cb-700827310fcf">

2. 使用vercel部署您的项目
<img width="325" alt="Screenshot 2024-04-09 at 09 50 54" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/9484313/3f754a12-3c2a-4fdf-9e34-760e8e3fcc6d">

3. 使用lobeChat使用同样的API Key成功的截图
<img width="313" alt="Screenshot 2024-04-09 at 09 50 01" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/9484313/d1ab11e2-662f-4d30-8534-ed02fc2eb935">

**Comment by Hk-Gosuto** [comment]
docker 和 vercel 版本都没有复现这个问题，你的中转服务是不是不支持 `v1/audio/speech` 路由的请求？

**Comment by laye0619** [comment]
抱歉哈 中转服务是什么意思？我使用的是官方openai api

**Comment by Hk-Gosuto** [comment]
就是是否有单独配置 `BASE_URL` 环境变量，tts 的请求这里只是中转到了 openai 的 `v1/audio/speech` 接口中，不太可能出现类似 404 的问题。
或者你看下后端的日志中是否有相关的错误信息？

openai 的接口文档：https://platform.openai.com/docs/guides/text-to-speech?lang=curl

**Comment by laye0619** [comment]
感谢大神！问题解决了，是我配置的问题，耽误了您很多时间十分抱歉！

**Comment by laye0619** [comment]
Close it.
