### ISSUE TITLE
[Bug] gpt-4-turbo-2024-04-09和gpt-4-turbo模型无法用插件，视觉功能也不能用

### ISSUE THREAD

**Issue by laxfer** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#247]
### Bug Description

openai新出的模型gpt-4-turbo-2024-04-09和gpt-4-turbo模型无法用插件

### Steps to Reproduce

切换到这两个其中一个模型，发送触发插件的消息，返回{
  "error": true,
  "message": "400 Unknown parameter: 'messages[2].tool_calls[0].index'."
}
这个错误，这两个模型的视觉功能也不能用，上传图片后，并没有做图片识别

### Expected Behavior

这个错误可以复现下吗，好解决吗

### Screenshots

![40412094522](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/52877918/82d5292f-bc7a-47ba-936b-07de8240c951)
![0240412094836](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/52877918/3e32a2aa-487f-49e3-9dde-960946fd277f)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

**Comment by Hk-Gosuto** [comment]
gpt-4-turbo-2024-04-09 函数调用的问题需要等 langchain 处理，已经给 langchian 提交了相关问题的 issues。
视觉模型的问题预计今晚会提交修复代码。

**Comment by Hk-Gosuto** [comment]
视觉模型的问题修复了

**Comment by laxfer** [comment]
> 视觉模型的问题修复了

非常感谢，官方也修复了gpt-4-turbo-2024-04-09和gpt-4-turbo模型无法正常调用函数的问题

**Comment by zpng** [comment]
> > 视觉模型的问题修复了
> 
> 非常感谢，官方也修复了gpt-4-turbo-2024-04-09和gpt-4-turbo模型无法正常调用函数的问题

也就是现在gpt-4-turbo-2024-04-09和gpt-4-turbo这俩可用了对吧，另外gpt-4-turbo默认指向的gpt-4-turbo-2024-04-09对吧

**Comment by laxfer** [comment]
> > > 视觉模型的问题修复了
> > 
> > 
> > 非常感谢，官方也修复了gpt-4-turbo-2024-04-09和gpt-4-turbo模型无法正常调用函数的问题
> 
> 也就是现在gpt-4-turbo-2024-04-09和gpt-4-turbo这俩可用了对吧，另外gpt-4-turbo默认指向的gpt-4-turbo-2024-04-09对吧,
对的，把@langchain/openai更新到最新就可以了，最好是和langchain相关的包都更新到最新
