### ISSUE TITLE
[Feature Request]: docker部署的，没有上传文件按钮么？

### ISSUE THREAD

**Issue by zhanghao123321** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#250]
### Problem Description

大佬，docker部署的，没有上传文件按钮么？

### Solution Description

镜像是：gosuto/chatgpt-next-web-langchain
当前版本：v2.11.3  
没有上传文件按钮

**Comment by zhanghao123321** [comment]
![Uploading 1981EF82-D503-4702-8346-8B1D122D3F05.png…]()

**Comment by zhanghao123321** [comment]
文件上传按钮，安装了最新镜像好像还是没有

**Comment by jsjcjsjc** [comment]
确实找不到文件上传的按钮

**Comment by pacmandoh** [comment]
> 确实找不到文件上传的按钮

请选择支持上传文件的模型后，上传按钮会出现

**Comment by jsjcjsjc** [comment]
> 支持上传文件的模型后，上传按钮会出现

我尝试了GPT4-turbo,但是找不到哈,只有图片上传
![](https://cloud.g60.net/d/cloud/note/img/2022/20240419_1713489070.jpg)

使用的是gosuto/chatgpt-next-web-langchain:nightly

**Comment by Hk-Gosuto** [comment]
> > 支持上传文件的模型后，上传按钮会出现
> 
> 我尝试了GPT4-turbo,但是找不到哈,只有图片上传 ![](https://camo.githubusercontent.com/0740ade63d182f89dd93c6eacf38094ba7013a4c53360d39f4dadf0c4596111b/68747470733a2f2f636c6f75642e6736302e6e65742f642f636c6f75642f6e6f74652f696d672f323032322f32303234303431395f313731333438393037302e6a7067)
> 
> 使用的是gosuto/chatgpt-next-web-langchain:nightly

检查一下相关的环境变量配置  https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/rag-cn.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by jsjcjsjc** [comment]
> > > 支持上传文件的模型后，上传按钮会出现
> > 
> > 
> > 我尝试了GPT4-turbo,但是找不到哈,只有图片上传 ![](https://camo.githubusercontent.com/0740ade63d182f89dd93c6eacf38094ba7013a4c53360d39f4dadf0c4596111b/68747470733a2f2f636c6f75642e6736302e6e65742f642f636c6f75642f6e6f74652f696d672f323032322f32303234303431395f313731333438393037302e6a7067)
> > 使用的是gosuto/chatgpt-next-web-langchain:nightly
> 
> 检查一下相关的环境变量配置 https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/rag-cn.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

感谢,我是使用默认配置,需要关注其他配置吗?感谢
```
docker run -d -p 3000:3000 \
   -e OPENAI_API_KEY="sk-xxxx" \
   -e CODE="页面访问密码" \
   gosuto/chatgpt-next-web-langchain:nightly
```

**Comment by Hk-Gosuto** [comment]
> > > > 支持上传文件的模型后，上传按钮会出现
> > > 
> > > 
> > > 我尝试了GPT4-turbo,但是找不到哈,只有图片上传 ![](https://camo.githubusercontent.com/0740ade63d182f89dd93c6eacf38094ba7013a4c53360d39f4dadf0c4596111b/68747470733a2f2f636c6f75642e6736302e6e65742f642f636c6f75642f6e6f74652f696d672f323032322f32303234303431395f313731333438393037302e6a7067)
> > > 使用的是gosuto/chatgpt-next-web-langchain:nightly
> > 
> > 
> > 检查一下相关的环境变量配置 https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/rag-cn.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F
> 
> 感谢,我是使用默认配置,需要关注其他配置吗?感谢
> 
> ```
> docker run -d -p 3000:3000 \
>    -e OPENAI_API_KEY="sk-xxxx" \
>    -e CODE="页面访问密码" \
>    gosuto/chatgpt-next-web-langchain:nightly
> ```



> > Bot detected the issue body's language is not English, translate it automatically.
> 
> > > > After supporting the model of uploading files, the upload button will appear.
> > > 
> > > 
> > > I tried GPT4-turbo, but couldn't find it, only pictures were uploaded![](https://camo.githubusercontent.com/0740ade63d182f89dd93c6eacf38094ba7013a4c53360d39f4dadf0c4596111b/68747470733a2f2f636c6f75642e 6736302e6e65742f642f636c6f75642f6e6f74652f696d672f323032322f32303234303431395f313731333438393037302e6a7067)
> > > Using gosuto/chatgpt-next-web-langchain:nightly
> > 
> > 
> > Check the relevant environment variable configuration https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/rag-cn.md#%E7%8E%AF%E5%A2 %83%E5%8F%98%E9%87%8F
> 
> Thank you. I am using the default configuration. Do I need to pay attention to other configurations? Thanks
> 
> ```
> docker run -d -p 3000:3000 \
>    -e OPENAI_API_KEY="sk-xxxx" \
>    -e CODE="Page access password" \
>    gosuto/chatgpt-next-web-langchain:nightly
> ```

需要使用 RAG 的文件上传就要看下文档中的相关配置，只使用图像上传的话就不需要。
