### ISSUE TITLE
 [Feature Request]: 更新了新版本原生支持claude模型，原来通过中转的claude3无法使用，大佬能修复下吗。中转的接口是openai形式的

### ISSUE THREAD

**Issue by hellobinker** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#251]
### Problem Description

更新了新版本原生支持claude模型，原来通过中转的claude3无法使用，大佬能修复下吗。中转的接口是openai形式的

### Solution Description

希望可以通过openai的接口也能调用claude，否则无法使用第三方中专的cluade，原生claude注册总是被封禁

**Comment by Hk-Gosuto** [comment]
可以试试在中转服务把 claude 的模型名改一下，然后使用 `CUSTOM_MODELS` 环境变量添加后使用。

**Comment by hellobinker** [comment]
好的，谢谢大佬
