### ISSUE TITLE
联网搜索的效果似乎有点问题哈? 

### ISSUE THREAD

**Issue by jsjcjsjc** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#252]
### Bug Description

GPT4-Trubo,提问"微软今天的股价?",回答一直是不正确的,每次回答都不一样,配置的是SERPAPI_API
<img width="655" alt="123" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/23775256/dfd076ca-31cd-47a5-90ad-fb1d5ddce1ff">

### Steps to Reproduce

NA

### Expected Behavior

NA

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
这是模型没区分当前股价和前一个交易日的收盘价
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/de798327-ba7f-45c2-ac8a-c974cf9ea479)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/bf43eb33-bbbc-45ef-8478-81165d76a65d)
