### ISSUE TITLE
[Bug] 关于基于coze中转使用gpt-4-vision-preview模型上传图片提示的URL解析错误报错

### ISSUE THREAD

**Issue by JuaJuanchi** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#253]
### Bug Description

使用本项目时gpt-4-vision-preview模型上传图片时会提示的URL解析错误报错

coze中转gpt对话项目为：https://github.com/deanxv/coze-discord-proxy
该项目是使用coze bot推送至discord再通过该项目将对话转发至当前项目来实现对话
该项目可以自定义模型名称，并且可以在coze官网自行添加bot的内置插件，来实现gpt4vision的功能
但是在最新本版本的更新中，使用gpt-4-vision-preview模型上传图片会提示错误Image URL parsing error 
在原项目ChatGPT-Next-Web中却可以正常使用
在原先旧版本中暂无问题，怀疑可能是在4月21日的修改：Merge remote-tracking branch 'upstream/main' 后导致的
可能跟ChatGPT-Next-Web-LangChain\app\client\platforms\openai.ts以及同级目录中的utils.ts，anthropic.ts有关

### Steps to Reproduce

1.使用coze-discord-proxy转发对话至本项目或转发至oneapi再发送至本项目
2.使用gpt-4-vision-preview模型上传图片
3.弹出报错:"URL解析错误"
{
  "error": {
    "message": "Image URL parsing error (request id: 2024042408052919667738666623494)",
    "type": "request_error",
    "param": "",
    "code": "500"
  }
}

### Expected Behavior

修复上传图片导致url链接解析错误的问题

### Screenshots

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/142490797/259a1ef3-5932-4b86-ba7c-a3da45bd9bf7)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/142490797/b7d6cd7f-02fe-4e46-8dbb-a07c09582929)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows11

### Desktop Browser

Edge

### Desktop Browser Version

版本 124.0.2478.51 (正式版本) stable应用，beta频道 (64 位)

### Smartphone Device

One Plus 11

### Smartphone OS

Android 14

### Smartphone Browser

Via

### Smartphone Browser Version

5.5.1

### Additional Logs

coze-discord-proxy的docker日志本项目以及原项目的调用情况
本项目：
[GIN] 2024/04/24 - 08:05:30 | 20240424080529549841528o8KMFcnk | 500 |  855.171973ms |    106.54.16.70 |    POST /v1/chat/completions
原项目：
[GIN] 2024/04/24 - 08:06:42 | 20240424080605718815544VGyj2b1z | 200 | 36.730719733s |    106.54.16.70 |    POST /v1/chat/completions

**Comment by Hk-Gosuto** [comment]
这部分接口并没有什么额外的改动，目前演示地址的视觉模型也可以正常返回。或者你可以提供一下两个项目接口请求负载的差异来帮忙解决这个问题？

**Comment by JuaJuanchi** [comment]
langchain：
{messages: [{role: "system",…},…], stream: true, model: "gpt-4-vision-preview", temperature: 0.5,…}
frequency_penalty
: 
0
max_tokens
: 
4000
messages
: 
[{role: "system",…},…]
0
: 
{role: "system",…}
content
: 
"\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2023-04\nCurrent model: gpt-4-vision-preview\nCurrent time: Wed Apr 24 2024 09:20:38 GMT+0800 (中国标准时间)\nLatex inline: \\(x^2\\) \nLatex block: $$e=mc^2$$\n\n"
role
: 
"system"
1
: 
{role: "user", content: [{type: "image_url", image_url: {,…}}, {type: "text", text: "这是什么？"}]}
content
: 
[{type: "image_url", image_url: {,…}}, {type: "text", text: "这是什么？"}]
0
: 
{type: "image_url", image_url: {,…}}
image_url
: 
{,…}
url
: 
"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAA
type
: 
"image_url"
1
: 
{type: "text", text: "这是什么？"}
text
: 
"这是什么？"
type
: 
"text"
role
: 
"user"
model
: 
"gpt-4-vision-preview"
presence_penalty
: 
0
stream
: 
true
temperature
: 
0.5
top_p
: 
1

原项目：
{messages: [{role: "system",…},…], stream: true, model: "gpt-4-vision-preview", temperature: 0.5,…}
frequency_penalty
: 
0
max_tokens
: 
4000
messages
: 
[{role: "system",…},…]
0
: 
{role: "system",…}
content
: 
"\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2023-04\nCurrent model: gpt-4-vision-preview\nCurrent time: 2024/4/24 09:24:22\nLatex inline: $x^2$ \nLatex block: $$e=mc^2$$\n\n"
role
: 
"system"
1
: 
{role: "user", content: [{type: "text", text: "这是什么？"}, {type: "image_url", image_url: {,…}}]}
content
: 
[{type: "text", text: "这是什么？"}, {type: "image_url", image_url: {,…}}]
0
: 
{type: "text", text: "这是什么？"}
text
: 
"这是什么？"
type
: 
"text"
1
: 
{type: "image_url", image_url: {,…}}
image_url
: 
{,…}
url
: 
"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAA
type
: 
"image_url"
role
: 
"user"
model
: 
"gpt-4-vision-preview"
presence_penalty
: 
0
stream
: 
true
temperature
: 
0.5
top_p
: 
1

**Comment by JuaJuanchi** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/142490797/a9e092cb-5be5-4f7d-9243-e307af5983f0)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/142490797/a701c034-169b-48f6-bec1-2ba4dcbad801)

**Comment by JuaJuanchi** [comment]
[langchain.json](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/files/15085450/langchain.json)
[原项目.json](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/files/15085452/default.json)
<img width="1280" alt="6c3fabc9339d9b368bb11536735d58ca" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/142490797/d2ca1757-baaf-4bfa-b1f8-e404fc9f945a">

**Comment by Hk-Gosuto** [comment]
之前针对 #220 这个问题调整过视觉模型的消息顺序，看来问题就是这个。
openai 官方接口对这个入参顺序并不敏感，问题还是各个第三方转发服务对参数处理上有问题。
主分支已经恢复上游代码，可以试试演示环境。

**Comment by JuaJuanchi** [comment]
问题已完美解决，感谢作者。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/142490797/6442cf59-edbd-451e-81c7-b76e2c6a8484)

**Comment by JuaJuanchi** [comment]
问题已经解决，麻烦把上方机器人的消息清除掉，不小心露出敏感信息了。

**Comment by Hk-Gosuto** [comment]
> 问题已经解决，麻烦把上方机器人的消息清除掉，不小心露出敏感信息了。

处理了

**Comment by JuaJuanchi** [comment]
貌似我还是能看见那个开发者选项的截图，里面包含中转地址以及key。

**Comment by Hk-Gosuto** [comment]
> 貌似我还是能看见那个开发者选项的截图，里面包含中转地址以及key。

删了
