### ISSUE TITLE
[Bug] 当前项目拉取后，docker build失败

### ISSUE THREAD

**Issue by QYlichuyou** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#255]
### Bug Description

报错为：
220.3 ./app/components/chat.tsx:1280:52
220.3 Type error: Property 'clipboardData' does not exist on type 'Window & typeof globalThis'. Did you mean 'Clipboard'?
220.3 
220.3   1278 |         return;
220.3   1279 |       }
220.3 > 1280 |       const items = (event.clipboardData || window.clipboardData).items;
220.3        |                                                    ^
220.3   1281 |       for (const item of items) {
220.3   1282 |         if (item.kind === "file" && item.type.startsWith("image/")) {
220.3   1283 |           event.preventDefault();

询问GPT亦未能找到解决方法

### Steps to Reproduce

git clone https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain.git
cd ChatGPT-Next-Web-LangChain
docker build -f Dockerfile -t bigbugger/chatgpt-next-web:1.0 .

### Expected Behavior

jobs done

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

ubuntu20.04

**Comment by Hk-Gosuto** [comment]
没能复现该问题，请尝试更新最新代码和 docker 后重新编译
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/716f185b-94b9-4304-9d74-3bd139397058)
