### ISSUE TITLE
[Bug] 回答问题时文字未能显示完全

### ISSUE THREAD

**Issue by yyqno1** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#256]
### Bug Description

![微信图片_20240426110454](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/162905667/f51ac34c-8505-4436-a1ba-01b90445584e)
如图所示，回答问题时文字未能显示完全，这个情况已经持续半个月有余。

### Steps to Reproduce

正常进入使用都出现这种情况，每一次都是。

### Expected Behavior

期望能够正常使用。

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
是否为 vercel 部署且配置了 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN=1` ？

**Comment by yyqno1** [comment]
没有部署，就只是添加了接口地址和API KEY

**Comment by Hk-Gosuto** [comment]
> 没有部署，就只是添加了接口地址和API KEY

用的演示环境么？演示环境之前测试 RAG 功能时做了上面的配置，vercel 环境下是会有超时的问题，目前已经关掉了。

**Comment by yyqno1** [comment]
> > 没有部署，就只是添加了接口地址和API KEY
> 
> 用的演示环境么？演示环境之前测试 RAG 功能时做了上面的配置，vercel 环境下是会有超时的问题，目前已经关掉了。

没有阿，就最普通的用法，把设置里自定义接口里的接口地址和API KEY输入后，没有设置别的东西，结果就这样了。对了，大概一个月前都不会这样的，就突然这样了。

**Comment by Hk-Gosuto** [comment]
> > > 没有部署，就只是添加了接口地址和API KEY
> > 
> > 
> > 用的演示环境么？演示环境之前测试 RAG 功能时做了上面的配置，vercel 环境下是会有超时的问题，目前已经关掉了。
> 
> 没有阿，就最普通的用法，把设置里自定义接口里的接口地址和API KEY输入后，没有设置别的东西，结果就这样了。对了，大概一个月前都不会这样的，就突然这样了。

那你使用的是 https://n3xt.chat 地址上的服务对吧？

**Comment by yyqno1** [comment]
> > > > 没有部署，就只是添加了接口地址和API KEY
> > > 
> > > 
> > > 用的演示环境么？演示环境之前测试 RAG 功能时做了上面的配置，vercel 环境下是会有超时的问题，目前已经关掉了。
> > 
> > 
> > 没有阿，就最普通的用法，把设置里自定义接口里的接口地址和API KEY输入后，没有设置别的东西，结果就这样了。对了，大概一个月前都不会这样的，就突然这样了。
> 
> 那你使用的是 https://n3xt.chat 地址上的服务对吧？

是的呀，我是用 https://n3xt.chat 这个地址的。

**Comment by yyqno1** [comment]
请问现在可以怎么办吗？

**Comment by yyqno1** [comment]
从昨天使用下来，目前没有再出现提到的问题，谢谢你。
