### ISSUE TITLE
Vercel Functions for Hobby can now run up to 60 seconds

### ISSUE THREAD

**Issue by SuiYunsy** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#258]
https://vercel.com/changelog/vercel-functions-for-hobby-can-now-run-up-to-60-seconds

关于 vercel 的这个更新想请教一下大佬：

我看 [文档](https://vercel.com/docs/functions/runtimes#max-duration) 里说 edge function 最大超时是25s，现在 node.js function 最大超时支持60s了，是不是可以把所有 functions 都改成 node.js runtime 呢？

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/104718844/95e6e244-46de-4810-8266-b93ca02052a8)

不太懂 node 和 edge 之间有啥“实际功能”上的区别，望大佬赐教！

**Comment by Hk-Gosuto** [comment]
edge runtime 不支持部分 node 函数，比如文件操作相关的，但 edge function 免费用户的其他限制比较小，所以默认在 vercel 环境下后端接口跑在 edge runtime 上。
其实也可以通过配置 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN=1` 来在 vercel 下启用 node runtime 支持，不过在网络不好或者多次插件调用的场景下可能会出现超时，比如读使用 pdf 浏览器插件去识别一个大的 pdf 文件时。

**Comment by SuiYunsy** [comment]
谢谢大佬，感觉差不多搞懂了😁

今天正好看到文档 https://vercel.com/docs/functions/runtimes#max-duration 这里的解释，我的理解是：
- api/openai/[...path]
如果采用 edge，只要首字在25秒内到达，就可以一直流式传输下去。
如果采用 nodejs，无论首字什么时候到达，只要总的传输时间超过 max-duration 就会被截断。
所以结论是 api/openai/[...path] 还是保持原样，设置为 edge function。
- 其他图中红色框的 nodejs function
默认 hobby plan 的 maxDuration 是10s，所以就可以根据 [blog](https://vercel.com/changelog/vercel-functions-for-hobby-can-now-run-up-to-60-seconds) 加上一行代码
`export const maxDuration = 60;`
来提高 nodejs function 的运行时间。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/104718844/468221ef-4ba6-4043-ac7f-9b27e4f787f8)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/104718844/b4db7336-9566-40c6-a815-697ca11e9e61)

**Comment by MuRo-J** [comment]
感谢分享,之前尝试开启NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN的时候几乎无法正常对话,因为很容易超过10s,
想咨询下修改60后是否有效呀?非常感谢啦!

**Comment by SuiYunsy** [comment]
https://github.com/SuiYunsy/NextWeb-LangChain/commit/85966d38f6ffa1ebe02b82b5d33ec9a27f79ab68

有效，上面commit中的 [app/api/openai/[...path]/route.ts](https://github.com/SuiYunsy/NextWeb-LangChain/commit/85966d38f6ffa1ebe02b82b5d33ec9a27f79ab68#diff-0a92abade8862b97a54d241b91d265f2e93895f6ac5607bd841e1ce7a57cb165) 照理不需要修改，建议保持edge，我还没改回来。

**Comment by MuRo-J** [comment]
再次感谢您的分享啦!我也去捣鼓!非常感谢
