### ISSUE TITLE
[Feature Request]: support gpt-4o

### ISSUE THREAD

**Issue by MuRo-J** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#259]
### Problem Description

作者大大,上游加了gpt-4o参数可以辛苦同步一下,我自己先修改了constant.ts,测试目前功能协作都很顺利
btw: 4o 是真真真真快啊..速度
多有打扰

上游也增加了一个环境变量,需要用到的同学可以使用 
DEFAULT_MODEL

作者大大看要不要补充在文档里,已经是可用状态啦~

### Solution Description

上游 or

**Comment by Hk-Gosuto** [comment]
已合并

**Comment by Linon419** [comment]
问一下大佬，为啥我这还是没有4o模型啊 版本2.12.2

**Comment by Hk-Gosuto** [comment]
> 问一下大佬，为啥我这还是没有4o模型啊 版本2.12.2

没发新版本，docker 部署如果想用最新的可以使用这个镜像 `gosuto/chatgpt-next-web-langchain:nightly`
