### ISSUE TITLE
[Feature Request]: 支持 GOOGLE_API_KEY 环境变量设置多 key

### ISSUE THREAD

**Issue by SuiYunsy** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#267]
### Problem Description

上游 [这个更新](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4626/files) 允许 GOOGLE_API_KEY 环境变量设置多 key 进行轮询，

但是目前作者大大的 GOOGLE_API_KEY 还同时是 GOOGLE_CUSTOM_SEARCH 的鉴权密钥。

### Solution Description

所以希望支持：既能多 Key 调用 Gemini，也同时不影响调用 custom search。

**Comment by cnmozzie** [comment]
README里面的环境变量`GOOGLE_BASE_URL`感觉也有些问题，我参考[这篇教程](https://zhile.io/2023/12/24/gemini-pro-proxy.html)用`GEMINI_BASE_URL`能成功转发，但是`GOOGLE_BASE_URL`就不行

**Comment by Hk-Gosuto** [comment]
> ### Problem Description
> 上游 [这个更新](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4626/files) 允许 GOOGLE_API_KEY 环境变量设置多 key 进行轮询，
> 
> 但是目前作者大大的 GOOGLE_API_KEY 还同时是 GOOGLE_CUSTOM_SEARCH 的鉴权密钥。
> 
> ### Solution Description
> 所以希望支持：既能多 Key 调用 Gemini，也同时不影响调用 custom search。
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_

使用 `GOOGLE_API_KEY` 的主要原因是 langchainjs 里的这个插件默认就是这个环境变量，不过我看插件支持通过构造函数传递其他配置，目前将该参数修改为了 `GOOGLE_SEARCH_API_KEY`，与 Gemini 相关的接口不冲突了。

**Comment by Hk-Gosuto** [comment]
> README里面的环境变量`GOOGLE_BASE_URL`感觉也有些问题，我参考[这篇教程](https://zhile.io/2023/12/24/gemini-pro-proxy.html)用`GEMINI_BASE_URL`能成功转发，但是`GOOGLE_BASE_URL`就不行

这个算是个历史遗留问题，我这个项目适配 Gemini 比上游项目要早一些，导致部分环境变量命名不一致，之前做了一些兼容处理，尽量保证了两个参数都可以用。
这次修正顺便也把这个问题处理了，已经跟上游完全同步了。
转发的话也可以试试我的这个基于 vercel 的转发，部署更方便一些，cf 不做优选的话在国内不太好用。
https://github.com/Hk-Gosuto/vercel-ai-proxy
