### ISSUE TITLE
同时支持RAG和上传图片

### ISSUE THREAD

**Issue by perryrighthere** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#269]
### Problem Description

当前版本中若使用多模态模型，则只能上传图片但是不能上传文档。

### Solution Description

请求更新同时支持上传图片和上传文档

**Comment by Hk-Gosuto** [comment]
暂时对这四个模型增加了支持：
- gpt-4-turbo
- gpt-4-turbo-2024-04-09
- gpt-4o
- gpt-4o-2024-05-13
