### ISSUE TITLE
大佬，我想作画插件对接one-api

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#27]
如果我使用此命令创建容器
```
docker run -d -p 8241:3000 \
	--name chatgpt1 \
	--restart always \
	-e PROXY_URL="http://192.168.1.4:7890" \
	-e BASE_URL="http://192.168.1.4:9150" \
	-e BING_SEARCH_API_KEY="90b3adf5" \
	-e R2_ACCOUNT_ID="1a245e" \
	-e R2_ACCESS_KEY_ID="506df65" \
	-e R2_SECRET_ACCESS_KEY="c773c9815c3486b5" \
	-e R2_BUCKET="gpt" \
	gosuto/chatgpt-next-web-langchain
```
修改 BASE_URL 为 one-api 地址。那么，one-api 日志会提示 `当前分组 svip 下对于模型 dall-e 无可用渠道`，在 one-api 如何怎么添加支持画图插件。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/839fe1ea-f331-4cea-a329-850306a936e0)
如果取消掉修改 BASE_URL 为 one-api 地址。那么，会正常作画。
```
docker run -d -p 8241:3000 \
	--name chatgpt1 \
	--restart always \
	-e PROXY_URL="http://192.168.1.4:7890" \
	-e BING_SEARCH_API_KEY="90b3adf5" \
	-e R2_ACCOUNT_ID="1a245e" \
	-e R2_ACCESS_KEY_ID="506df65" \
	-e R2_SECRET_ACCESS_KEY="c773c9815c3486b5" \
	-e R2_BUCKET="gpt" \
	gosuto/chatgpt-next-web-langchain
```
最后想问下，作画插件需要开代理吗？

**Comment by Hk-Gosuto** [comment]
需要在你创建的渠道中添加 `dall-e` 模型，`dall-e` 插件调用的也是 openai 的接口，如果你 one-api 已经可以正常访问 openai 接口就不需要再配置代理了，插件现在也不支持代理的配置。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/90155279-9595-4a4e-b405-8779a907bf99)

**Comment by cui8** [comment]
> 需要在你创建的渠道中添加 `dall-e` 模型，`dall-e` 插件调用的也是 openai 的接口，如果你 one-api 已经可以正常访问 openai 接口就不需要再配置代理了，插件现在也不支持代理的配置。 ![image](https://user-images.githubusercontent.com/14031260/269516814-90155279-9595-4a4e-b405-8779a907bf99.png)

谢谢大佬，有大佬帮忙，让小白少折腾几个小时。我还以为代理问题，最后没办法才看one-api日志的
