### ISSUE TITLE
[Bug] google custom search 结果好差

### ISSUE THREAD

**Issue by Linon419** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#274]
### Bug Description

<img width="870" alt="Screenshot 2024-06-03 at 17 47 47" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/29937602/ef667961-14fc-4ec9-bb82-315c088725d1">

### Steps to Reproduce

已经配置了相关参数

### Expected Behavior

输出正确的结果

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/c6719c17-338a-43eb-8357-d0fcdf6d4218)
检查一下是否为网络问题，或者参数配置导致插件无法正常运行。
