### ISSUE TITLE
[Bug] rag功能不是很好使,请指点下

### ISSUE THREAD

**Issue by sparkssssssss** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#275]
### Bug Description

没有如作者图中调用插件;
存储中可以看到向量文件,但是都是乱码
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14211550/ea0a71b4-4118-4d98-abef-ca3929f01916)
对话如下
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14211550/4849e588-9974-4583-9847-f88a4c81070f)
pdf内容如下
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14211550/171152cd-c311-4d2d-a6fa-870f2762f6d0)

### Steps to Reproduce

暂无

### Expected Behavior

暂无

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
要不你把 pdf 发出来我试试？

**Comment by sparkssssssssss** [comment]
我感觉不是pdf的问题,我之前传过几次,也有正常显示的,但是我从来没有出现过调用插件rag那个提示,所以想在请教下,正确的姿势?
目前我尝试过:
1-关闭所有插件,无效
2-关闭所有插件,除了那个pdf查看的,无效
3-不管插件,无效
我使用的是最新night的镜像

[020-GB_T 33133.2-2021 信息安全技术 祖冲之序列密码算法 第2部分：保密性算法.pdf](https://github.com/user-attachments/files/15587273/020-GB_T.33133.2-2021.2.pdf)

**Comment by Hk-Gosuto** [comment]
我试了以下这个pdf，该pdf文件应该做了特殊处理，直接在文件中复制出的文本也是乱码，这种文件没办法正确解析出文本的。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/1b67047c-e8f2-43fd-b1f5-02437945d995)

**Comment by sparkssssssss** [comment]
> 我试了以下这个pdf，该pdf文件应该做了特殊处理，直接在文件中复制出的文本也是乱码，这种文件没办法正确解析出文本的。 ![image](https://private-user-images.githubusercontent.com/14031260/337267597-1b67047c-e8f2-43fd-b1f5-02437945d995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzY5ODYsIm5iZiI6MTcxNzczNjY4NiwicGF0aCI6Ii8xNDAzMTI2MC8zMzcyNjc1OTctMWI2NzA0N2MtZThmMi00M2ZkLWIxZjUtMDI0Mzc5NDVkOTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA1MDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NWNhMmM1MjI4MjcxODAwMmQwNmZkY2ZiMTMyZWFhNDAzNDM4MDIwNGVkMWZlMDQzYzA3MDUxOTJkNTdlY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ws3KWs67hYuWKlQZEPLYOoRxSEREFKt-JkRt0RdaWQA)

我随便上一个pdf,生成了向量文件,但是问不出所以然
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14211550/86b8a275-0cdd-4c3d-a05a-26cabfcf01bc)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14211550/eb18b2ca-7ef8-4af8-b627-ed7a9d1d06f4)

**Comment by Hk-Gosuto** [comment]
由于现在是基于插件的形式进行检索的，所以需要引导 gpt 使用 rag-search 才会返回相关上下文。
这个月事情有点多，等待后面的优化吧。
