### ISSUE TITLE
[Bug] 出现错误，无法回答问题

### ISSUE THREAD

**Issue by AthanaD** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#276]
### Bug Description

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/125889247/1ecc6af6-0060-4abd-b5d5-6aa9abe96e72)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/125889247/fcbafe05-21b7-4397-93e2-544e536f91f9)

同样的NEWAPI管理，同样的问题和调用的模型，lobe可以，chatgpt-next不行

### Steps to Reproduce

RT

### Expected Behavior

RTrtrtrt

### Screenshots

rt

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
原版 ChatGPT-Next-Web 是否可用？

**Comment by AthanaD** [comment]
部分模型无法用，常规模型可以用。我采用的https://github.com/Ink-Osier/DeepLXToV1Api创建的API接口及KEY，在lobe chat中可以用

**Comment by Hk-Gosuto** [comment]
你是直接在页面上配置的自定义接口是吧，那里有本身浏览器的限制，比如你的接口协议需要跟你页面协议一致（页面是https的那定义的接口也要是https的），服务器必须支持访问域名的CORS策略（我看了以下，那个项目应该是没配置相关的fastapi中间件）。
如果不想有上述麻烦可以直接配置环境变量中的 `BASE_URL` 和 `CUSTOM_MODELS` 。

**Comment by AthanaD** [comment]
> 你是直接在页面上配置的自定义接口是吧，那里有本身浏览器的限制，比如你的接口协议需要跟你页面协议一致（页面是https的那定义的接口也要是https的），服务器必须支持访问域名的CORS策略（我看了以下，那个项目应该是没配置相关的fastapi中间件）。 如果不想有上述麻烦可以直接配置环境变量中的 `BASE_URL` 和 `CUSTOM_MODELS` 。

我的配置都是好的，而且我在nginx及cloudflare里边已经设置了cors规则，我是采用new-api令牌直接打开自动带有接口及密钥的，还是出错，现在发现很多模型出错，包括claude3系列、deeplx系列、gpts系列等
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/125889247/da2544e6-51de-4ec4-b12e-be788209de93)

`  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    networks:
      mynet:
        ipv4_address: x.x.x.x
    ports:
      - "3005:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      # - /home/ubuntu/data/new-api:/data
    environment:
      - SQL_DSN=newapi:newapi@tcp(x.x.x.x:3306)/newapi
      - TZ=Asia/Shanghai
      - THEME=berry
    depends_on:
      - redis2  # 确保在应用服务启动前 Redis 服务已经运行
      
  chatgpt-next-web:
    container_name: chatgpt-next-web
    image: gosuto/chatgpt-next-web-langchain:latest  # 使用指定的Docker镜像
    restart: always  # 设置容器总是重启
    volumes:
      - next_chat_upload:/app/uploads  # 定义数据卷
    ports:
      - "3000:3000"  # 端口映射
    environment:
      - BASE_URL=https://xxx.com  # 设置基础URL
      - DEFAULT_MODEL=gpt-4o     
      - OPENAI_API_KEY=sk-xxxxx  # 设置OpenAI API密钥
      - ENABLE_BALANCE_QUERY=1  # 启用余额查询功能
      - NEXT_PUBLIC_ENABLE_BASE64=1
      - CUSTOM_MODELS=-all,+gpt-4-s=gpt-4-all,+gpt-4-o=gpt-4o,+gpt-4-gizmo,+gpt-4-gizmo-*,+gpt-4-magic-create,+gpt-4,+gpt-4-vision-preview,+gpt-4-classic,+webpilot,+chiangma,+m/gpt_4_turbo=gpt-4-turbo-2024-04-09,+m/claude_3_opus=claude-3-opus-20240229,+m/claude_3_sonnet=claude-3-sonnet-2024022,+m/claude_3_haiku=claude-3-haiku-20240307,+m/gemini_1_5_pro=gemini-pro,+m/command_r_plus=command-r-plus,+m/gpt-4o=gpt-4o,+copilot4,+deepseek-chat,+deepseek-coder,+deeplx-EN,+deeplx-ZH,+dall-e-3,+whisper-1,+tts-1  # 自定义模型环境变量
      # 其他原有环境变量，如果需要，可以在此基础上添加或修改
      - GOOGLE_API_KEY=
      - OPENAI_ORG_ID=
      - HIDE_USER_API_KEY=
      - DISABLE_GPT4=
      - ENABLE_BALANCE_QUERY=
      - DISABLE_FAST_LINK=
      - OPENAI_SB=`

**Comment by Hk-Gosuto** [comment]
cloudflare 转发我记得是有一些问题，你可以搜索一下以前的 issues，还有就是你说的其他模型调用会出错的问题，因为你是用的中转服务，而中转服务会将接口统一为 openai 的路由规则，原项目对 Claude Gemini 这类模型的路由做了处理，导致中转的接口但凡模型名匹配上了都会强制使用对应服务的接口路由。

关于多提供方模型的路由不一致的问题可以看下我今天新加的环境变量：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain?tab=readme-ov-file#next_public_use_openai_endpoint_for_all_models-%E5%8F%AF%E9%80%89
不过 docker 镜像还没跑，你可以本地用源码跑一下试试。

关于DeepLXToV1Api转发的接口调用错误，我在本地通过源码运行了一个加了CORS中间件的版本，在页面配置接口和环境变量两种形式都是可以正常调用的。

**Comment by AthanaD** [comment]
> cloudflare 转发我记得是有一些问题，你可以搜索一下以前的 issues，还有就是你说的其他模型调用会出错的问题，因为你是用的中转服务，而中转服务会将接口统一为 openai 的路由规则，原项目对 Claude Gemini 这类模型的路由做了处理，导致中转的接口但凡模型名匹配上了都会强制使用对应服务的接口路由。
> 
> 关于多提供方模型的路由不一致的问题可以看下我今天新加的环境变量：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain?tab=readme-ov-file#next_public_use_openai_endpoint_for_all_models-%E5%8F%AF%E9%80%89 不过 docker 镜像还没跑，你可以本地用源码跑一下试试。
> 
> 关于DeepLXToV1Api转发的接口调用错误，我在本地通过源码运行了一个加了CORS中间件的版本，在页面配置接口和环境变量两种形式都是可以正常调用的。
通过postman是可以直接调用的，就是通过chatgpt-next部分模型会出现错误，我在nginx及cloudflare里边都增加了cors规则的，之前一直可以用，最近不晓得更新到哪版了不能用了。

> Request URL:
> https://xxxx.com/v1/chat/completions
> Referrer Policy:
> strict-origin-when-cross-origin
> Accept:
> application/json, text/event-stream
> Authorization:
> Bearer sk-xxxxxx
> Content-Type:
> application/json
> Referer:
> https://ai.xxxx.com/
> Sec-Ch-Ua:
> "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
> Sec-Ch-Ua-Mobile:
> ?0
> Sec-Ch-Ua-Platform:
> "Windows"
> User-Agent:
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
> X-Requested-With:
> XMLHttpRequest

**Comment by AthanaD** [comment]
已经在大佬指点下解决了，nginx里边的跨域名cors以下内容全部注释即可：
        # add_header 'Access-Control-Allow-Origin' '*' always;
