### ISSUE TITLE
[Feature Request]: 先谢！6月7日部署了docker版，与作者官方比无上传图片或者文件按钮，azure中转的api画图后，无法直接保存图片。是否有其他版本可以替换？

### ISSUE THREAD

**Issue by fsyllkn** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#277]
### Problem Description

6月7日部署了docker版，与作者官方比无上传图片或者文件按钮，azure中转的api画图后，无法复制。

### Solution Description

作者部署的版本是哪个版本？希望尝试一下，感谢感谢~

**Comment by fsyllkn** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/76274519/54238d4b-2893-4325-9650-79a3e7811253)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/76274519/f026b503-2cd5-4d36-bc16-27bb04fe8b19)
点击右键，直接复制了字符，并添加到了对话框中，左键无反应，无法打开预览保存图片

**Comment by fsyllkn** [comment]
Thanks for your patience.

**Comment by fsyllkn** [comment]
I use gosuto/chatgpt-next-web-langchain:nightly instead of default version，
Only the image upload button has been added, the file upload button is still not displayed.
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/76274519/fc641fb3-d38a-4104-b456-4b5e7d3f7a4b)
I think the following is the version I want.
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/76274519/54db73d5-e7b4-49c4-94d5-ef6e70da461e)

**Comment by Hk-Gosuto** [comment]
关于视觉模型的判定是根据模型名来判断的，可以参考这个方法：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/fdc0e7447112894e02fdb9629953481e23910e0b/app/utils.ts#L253

图像的话可以使用浏览器的特性来快速保存到本地，左键按住图像，然后拖拽到想要保存的文件夹松开左键即可。

**Comment by fsyllkn** [comment]
> 关于视觉模型的判定是根据模型名来判断的，可以参考这个方法：
> 
> https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/fdc0e7447112894e02fdb9629953481e23910e0b/app/utils.ts#L253
> 
> 图像的话可以使用浏览器的特性来快速保存到本地，左键按住图像，然后拖拽到想要保存的文件夹松开左键即可。

真的可以呀！感谢大佬指导。
