### ISSUE TITLE
azure官方api无法使用

### ISSUE THREAD

**Issue by zbzzh** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#278]
### Bug Description

{
  "error": true,
  "message": "404 The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."
}
还需要转换为openai格式吗，原版的就不需要啊
链接我填的这个
https://xxx.openai.azure.com//openai/deployments
不能用

### Steps to Reproduce

{
  "error": true,
  "message": "404 The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."
}
还需要转换为openai格式吗，原版的就不需要啊
链接我填的这个
https://xxx.openai.azure.com//openai/deployments
不能用

### Expected Behavior

123

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by zbzzh** [comment]
> 按这个格式配置 ![image](https://private-user-images.githubusercontent.com/14031260/337977738-132bc813-61a2-4b70-a9b0-50db6d4f0b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDA3MzMsIm5iZiI6MTcxNzk0MDQzMywicGF0aCI6Ii8xNDAzMTI2MC8zMzc5Nzc3MzgtMTMyYmM4MTMtNjFhMi00YjcwLWE5YjAtNTBkYjZkNGYwYjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEzNDAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMGRhZDg3NWVjMGQyZTk0NjZiOTc3YjE3MmZhOGIzOWNkYzJhMmZlZDY4MTYyZjQ1NmYyYzhhNWQ2MGFjNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vEFeth0rs0gr1IveBYoihdDenu7_52vSJPwKI8Jsfjs)

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/87306816/3c0e62f8-7cd6-4ff1-a37d-5aad16cf0430)

**Comment by zbzzh** [comment]
不行

**Comment by Hk-Gosuto** [comment]
检查以下你的接口地址，你上面发的地址里多了一个 /。
https://xxx.openai.azure.com//openai/deployments -> https://xxx.openai.azure.com/openai/deployments

我刚也部署了一个 gpt-4o 的模型，是可以正常使用的，环境是：https://n3xt.chat/

**Comment by zbzzh** [comment]
> 检查以下你的接口地址，你上面发的地址里多了一个 /。 https://xxx.openai.azure.com//openai/deployments -> https://xxx.openai.azure.com/openai/deployments
> 
> 我刚也部署了一个 gpt-4o 的模型，是可以正常使用的，环境是：https://n3xt.chat/

我就是用的你的demo

https://xxxx.openai.azure.com//openai/deployments
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/87306816/bebcb6c4-07c4-4a86-99d3-13d0c6b38e5c)

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/87306816/892f3891-6457-46df-b65a-aa1101901d1e)

能不能给个临时的联系方式呀，可以远程帮忙看下吗

**Comment by zbzzh** [comment]
我去掉那个/了，还是不行

**Comment by zbzzh** [comment]
我找到原因了，模型名要写gpt4o而不是gpt4o，这个后台可以修改吗

**Comment by zbzzh** [comment]
作者你好，我刚才测试文件上传功能时，在你的demo上传了一些个人资料，麻烦您能删除一下，涉及到个人隐私谢谢

**Comment by Hk-Gosuto** [comment]
删掉了

**Comment by Hk-Gosuto** [comment]
> 我找到原因了，模型名要写gpt4o而不是gpt-4o，我尝试修改一下，另外请问，gpt4o支持传文件吗

支持函数调用的模型都可以，填写好相关的配置就行。

**Comment by zbzzh** [comment]
试了一下 传文件不行，他一直让我提供链接，我无论怎么发给他他都说不行

**Comment by Hk-Gosuto** [comment]
可以引导 ai 使用 rag-search 插件进行文档检索，不然上下文中没用文件相关的内容。
这部分后面会做一些优化，把上传后的文件描述添加到系统提示词里。

**Comment by zbzzh** [comment]
强烈支持，现在很多人需要传文件这个功能，如果可以上传到第三方存储就更好了
顺便问下google custom search免费的api配额有多少

**Comment by Hk-Gosuto** [comment]
看文档中的描述应该是每天免费100次搜索。
https://developers.google.com/custom-search/v1/overview?hl=zh_CN
