### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'delta')

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#28]
实在是不好意思，一直打扰大佬了。这个问题属实是我个人使用出现的问题，不在大佬解决范围内，如果有打扰冒犯大佬的地方，请接受我的道歉，我不是有意的。
我使用 https://github.com/haibbo/cf-openai-azure-proxy 开源项目来把 Azure OpenAI 转为 ChatGPT 的格式，在 one-api 对接，然后再本项目使用，会出错，如下。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/f325f730-06c0-476f-a5f4-62969966ab7d)
但在原版 `Yidadaa/
ChatGPT-Next-Web` 使用正常，这个问题该怎么解决？
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/2e0b7b88-dc10-4983-a550-af1aeadf0c89)
我真的不是有意打扰大佬您的，如果大佬有什么需要，我可以提供 Azure OpenAI 所有参数。

**Comment by Hk-Gosuto** [comment]
Azure 版本的 OpenAI 接口虽然支持微调版本的模型，但是我试过他们接口的出参跟 OpenAI 官方接口的还是有区别，这个 langchain 并没有适配，所以这边调用插件的时候就报错了。

**Comment by cui8** [comment]
> Azure 版本的 OpenAI 接口虽然支持微调版本的模型，但是我试过他们接口的出参跟 OpenAI 官方接口的还是有区别，这个 langchain 并没有适配，所以这边调用插件的时候就报错了。

好的，谢谢大佬，不麻烦大佬了，也就我自己使用，不浪费大佬时间了

**Comment by cui8** [comment]
再次感谢大佬，几天不见，就出了好玩的插件，可以娱乐一段时间了，感谢大佬的付出，辛苦了

**Comment by Hk-Gosuto** [comment]
我看了一下，Azure 版本的 OpenAI 有个预览版的函数调用，可以试试把模型升级到 0613 版本并将 `api_version` 设置为 `2023-07-01-preview`。
我没验证，你可以试试看。

**Comment by cui8** [comment]
> 我看了一下，Azure 版本的 OpenAI 有个预览版的函数调用，可以试试把模型升级到 0613 版本并将 `api_version` 设置为 `2023-07-01-preview`。 我没验证，你可以试试看。

这个可以使用，大佬nb
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/90da6550-ea52-4a6a-87da-ce6cfd144ec5)

**Comment by cui8** [comment]
我都没发现这个可以使用，牛
