### ISSUE TITLE
求助关于文件上传和社区交流

### ISSUE THREAD

**Issue by nknkZ** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#280]
### Problem Description

我是小白，目前是vercel部署，可以上传图片，并已配置RAG，但无法实现项目网页版展示的文件上传功能。希望有稍微更详细的步骤说明。
另外大大时间宝贵，求个项目的交流群。

谢谢大家的宝贵时间。

### Solution Description

文件上传功能指导（RAG已配置）
交流社群地址

**Comment by Hk-Gosuto** [comment]
😂没想到这个功能有这么多人关注 我这段时间比较忙 预计7月份会完善这个功能
交流群晚一些我会建一个

**Comment by nknkZ** [comment]
好的，谢谢！！
补充一下问题进展：
在vercel redeploy项目之后有上传文件的按钮了（之前是我的问题抱歉），但是无法识别其中内容（如下图1），
另外请求时间段内，Qdrant没有请求记录（如下图2），不知道有没有其他方法验证环境变量是否配置有误，
其中：希望确认一下，Cluster URL是否需要包括端口号:6333，希望RAG说明里能有示例
万分感谢阅读！
图1：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/152165853/bd994943-a7ec-4a92-a66a-1d5c517b1520)
图2：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/152165853/b28e41c9-e095-4f1d-97d4-26d2bee0ceb9)

**Comment by felix5572** [comment]
Similar situation. Deployed on zeabur.com. But it shows upload figures instead of upload file. 
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/32410372/6123fc9d-73ed-4f73-8343-9ccc22385278)

**Comment by Hk-Gosuto** [comment]
已建立 discord 和 QQ群，相关链接请查看：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/discussions/283
