### ISSUE TITLE
无法使用Google Custom Search

### ISSUE THREAD

**Issue by JasonxlxCharles** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#282]
### Bug Description

已经成功申请了Google API与Custom Search Engine ID，在Custom Search Engine的界面可以成功打开他的网页版Custom Search， 但是使用docker部署后填入两个环境变量却无法使用，每次联网搜索都是选择duckduckgo，研究数小时仍然费解

### Steps to Reproduce

.

### Expected Behavior

希望在填入Google_API_Key与CSE环境变量后可以成功启用Google Custom Search

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows10

### Desktop Browser

Chrome

### Desktop Browser Version

125.0.6422.142

**Comment by Hk-Gosuto** [comment]
docker 的运行运行命令发一下，相关 key 记得隐藏。
