### ISSUE TITLE
[Feature Request]: Claude3可以接入插件功能吗

### ISSUE THREAD

**Issue by laxfer** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#288]
### Problem Description

Claude3可以接入插件功能吗

### Solution Description

目前只有openai的模型接入了插件的工具，Claude3可以接入插件功能吗，改动大吗

**Comment by Hk-Gosuto** [comment]
改动应该不是太大，不过我的 claude 账户被封了，我看看能不能找到能测试的接口吧😂

**Comment by laxfer** [comment]
> 婚姻应该不是那么重要，我的克劳德·米勒被封了，我看看能不能找到能测试的接口吧
我可以把我的Cluade的秘钥给你用，但是不知道怎么私密发你，你可以提供个邮箱，我发你也行！

**Comment by laxfer** [comment]
> 改动应该不是太大，不过我的 claude 账户被封了，我看看能不能找到能测试的接口吧😂

我可以把我的Cluade的秘钥给你用，但是不知道怎么私密发你，你可以提供个邮箱，我发你也行！

**Comment by Hk-Gosuto** [comment]
> > 改动应该不是太大，不过我的 claude 账户被封了，我看看能不能找到能测试的接口吧😂
> 
> 我可以把我的Cluade的秘钥给你用，但是不知道怎么私密发你，你可以提供个邮箱，我发你也行！

可以在 QQ 群里找到我后私信
