### ISSUE TITLE
[Feature Request]: 增加默认模型的环境变量

### ISSUE THREAD

**Issue by winter2399** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#290]
### Problem Description

希望增加一个变量，修改默认使用的模型。
如果不增加变量，大佬可以告知修改源码哪里吗？

### Solution Description

增加一个变量，修改默认使用的模型。想把默认模型从gpt3.5改为gemini

**Comment by MuRo-J** [comment]
DEFAULT_MODEL
上游已经支持过了，其实有，只是这边文档没有写，实测也是可用的，如 vercel 配置的
![CleanShot 2024-07-10 at 23 30 41](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/64354330/6e83e3c5-54d0-470b-b09c-edcc53ec1172)

**Comment by winter2399** [comment]
> DEFAULT_MODEL 上游已经支持过了，其实有，只是这边文档没有写，实测也是可用的，如 vercel 配置的 ![CleanShot 2024-07-10 at 23 30 41](https://private-user-images.githubusercontent.com/64354330/347468567-6e83e3c5-54d0-470b-b09c-edcc53ec1172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NTkwNTMsIm5iZiI6MTcyMDY1ODc1MywicGF0aCI6Ii82NDM1NDMzMC8zNDc0Njg1NjctNmU4M2UzYzUtNTRkMC00NzBiLWIwOWMtZWRjYzUzZWMxMTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAwNDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YjM1ZmZjMGZjOWRkOGNkZGFjOWEzZDI0MjVhMjczYmMwN2NmMGEwYmMxNzM1ZTY4YWM1MDU2MjIzOTM2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDMg31xDPOeedC5DzJkmrKUkTE5K0L9H4uwcXC5D9Ac) btw，如果修改了这个变量重新部署后，可以在无痕窗口打开试试看，原使用页面会保留一些设置，可通过清空缓存，或者清空设置，只是这样操作可能导致以前的对话丢失，请根据情况自己处理

感谢，非常感谢

**Comment by Hk-Gosuto** [comment]
> DEFAULT_MODEL 上游已经支持过了，其实有，只是这边文档没有写，实测也是可用的，如 vercel 配置的 ![CleanShot 2024-07-10 at 23 30 41](https://private-user-images.githubusercontent.com/64354330/347468567-6e83e3c5-54d0-470b-b09c-edcc53ec1172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjAyOTEsIm5iZiI6MTcyMDY1OTk5MSwicGF0aCI6Ii82NDM1NDMzMC8zNDc0Njg1NjctNmU4M2UzYzUtNTRkMC00NzBiLWIwOWMtZWRjYzUzZWMxMTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAxMDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNzc0YzlkZDFmODA4OGZiMjQwM2Q5YmNkNThjNGJkMDg1ZTA0MDM0MjJhMTM5NDhlNDA5ZTMyOTJhYmRkZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3gv_zyFYbIgcTItGvvtzKnB5Zqc56OtvvR54rgkALLc) btw，如果修改了这个变量重新部署后，可以在无痕窗口打开试试看，原使用页面会保留一些设置，可通过清空缓存，或者清空设置，只是这样操作可能导致以前的对话丢失，请根据情况自己处理

是的 上游的变量这边都支持 可能部分文档合并的时候有遗漏 大家发现了可以发个pr过来

**Comment by MuRo-J** [comment]
> > DEFAULT_MODEL 上游已经支持过了，其实有，只是这边文档没有写，实测也是可用的，如 vercel 配置的 ![CleanShot 2024-07-10 at 23 30 41](https://private-user-images.githubusercontent.com/64354330/347468567-6e83e3c5-54d0-470b-b09c-edcc53ec1172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjAyOTEsIm5iZiI6MTcyMDY1OTk5MSwicGF0aCI6Ii82NDM1NDMzMC8zNDc0Njg1NjctNmU4M2UzYzUtNTRkMC00NzBiLWIwOWMtZWRjYzUzZWMxMTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAxMDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNzc0YzlkZDFmODA4OGZiMjQwM2Q5YmNkNThjNGJkMDg1ZTA0MDM0MjJhMTM5NDhlNDA5ZTMyOTJhYmRkZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3gv_zyFYbIgcTItGvvtzKnB5Zqc56OtvvR54rgkALLc) btw，如果修改了这个变量重新部署后，可以在无痕窗口打开试试看，原使用页面会保留一些设置，可通过清空缓存，或者清空设置，只是这样操作可能导致以前的对话丢失，请根据情况自己处理
> 
> 是的 上游的变量这边都支持 可能部分文档合并的时候有遗漏 大家发现了可以发个pr过来

谢谢大佬,后面知道啦,因为水平低,不敢做这些操作,感谢您的付出!
