### ISSUE TITLE
[Bug] 语音转文本提示错误

### ISSUE THREAD

**Issue by winter2399** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#291]
### Bug Description

使用 whisper 会报错，使用 WebAPI 不会报这个错误。

![image](https://github.com/user-attachments/assets/f954609b-8564-4aca-a0d4-bea241995d11)

求大佬解答，是因为使用的 one-api 吗？

### Steps to Reproduce

1. 启用语音转文本
2. 切换引擎为 whisper
3. 点击对话框的说话按钮报错（我允许了麦克风权限）

### Expected Behavior

可以使用语音转文本的 whisper 功能。

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

win10

### Desktop Browser

edge 和 谷歌浏览器

**Comment by Hk-Gosuto** [comment]
确认一下你的网站是否开启了 https 访问。

**Comment by winter2399** [comment]
> 确认一下你的网站是否开启了 https 访问。

开了ttps
```
location / {
    proxy_pass http://10.170.0.2:9133;
    proxy_http_version 1.1;
    
    # 不缓存，支持流式输出
    proxy_cache off;  # 关闭缓存
    proxy_buffering off;  # 关闭代理缓冲
    chunked_transfer_encoding on;  # 开启分块传输编码
    tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
    tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
    keepalive_timeout 300;  # 设定keep-alive超时时间为300秒

    # CORS 配置
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

    # 处理 OPTIONS 请求
    if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
    }
}
```

**Comment by ZefanHu** [comment]
我的语言转文本功能也不能使用, 不知道为啥, 没有配置相关的环境变量, 不知道是否需要. 报错[HTTP/2 503 Service Unavailable 515ms], 应该是选择的WebAPI和OpenAI都是这个错.

**Comment by Hk-Gosuto** [comment]
接口中是否有具体的报错信息？可否发下接口返回的原始数据。

**Comment by winter2399** [comment]
> 接口中是否有具体的报错信息？可否发下接口返回的原始数据。

怎么查看接口报错信息

**Comment by Hk-Gosuto** [comment]
F12 打开浏览器开发者工具 然后切到网络选项卡 里面有标红的接口 点击后看里面具体的返回值

**Comment by winter2399** [comment]
> F12 打开浏览器开发者工具 然后切到网络选项卡 里面有标红的接口 点击后看里面具体的返回值

![image](https://github.com/user-attachments/assets/098962f5-92c1-439a-a18e-85d3101e8893)

没有网络请求，单纯的控制台报错

**Comment by Hk-Gosuto** [comment]
试一下演示环境是否正常 https://n3xt.chat

**Comment by winter2399** [comment]
> 试一下演示环境是否正常 https://n3xt.chat

一样的问题，webapi没问题，whisper 控制台报错，不发送网络请求。
![image](https://github.com/user-attachments/assets/557edcfe-13c2-4fa7-821e-690f8fb561e4)

![image](https://github.com/user-attachments/assets/b8933fd5-b7f1-4bae-a8ab-1979a1594408)

**Comment by Hk-Gosuto** [comment]
你开一个隐身窗口试试，我同样版本的edge无法复现这个问题。

**Comment by winter2399** [comment]
> 你开一个隐身窗口试试，我同样版本的edge无法复现这个问题。

找到问题了。这个错误真的太迷惑了。谢谢大佬耐心解答
https://blog.csdn.net/qq_41000974/article/details/121306408

**Comment by winter2399** [comment]
> 你开一个隐身窗口试试，我同样版本的edge无法复现这个问题。

谢谢大佬，非常感谢。这个在win10 ltsc设置默认关闭。错误奇奇怪怪

**Comment by Hk-Gosuto** [comment]
> > 你开一个隐身窗口试试，我同样版本的edge无法复现这个问题。
> 
> 谢谢大佬，非常感谢。这个在win10 2021 ltsc设置默认关闭。错误奇奇怪怪。既然设置默认关闭，为什么webapi可以跳过这个权限

webapi 是直接调用的浏览器提供的语音识别 api，可能浏览器底层申请逻辑不一样吧，具体也不是很清楚，第一次见你这个文章里说的开关。
