### ISSUE TITLE
[Bug] Vercel使用RAG的两个小问题

### ISSUE THREAD

**Issue by MuRo-J** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#293]
### Bug Description

辛苦大佬,终于体验上了,之前一版在vercel上很难体会的到,新的这一版初步尝试后发现这两个点,辛苦您看看

1.开启插件的状态下直接报错
没有查看到哪里引发的,关闭插件后可以正常,这个是不是预期的呀
```
{
  "error": true,
  "message": "400 Invalid 'tools': empty array. Expected an array with minimum length 1, but got an empty array instead."
}
```
2.每点击一次刷新(重新提问)会重复一次文件名,也不算影响,只是报给大佬一下
![CleanShot 2024-07-18 at 21 28 46](https://github.com/user-attachments/assets/88e22d73-8e8b-40c0-ab90-362cb28c71a9)

### Steps to Reproduce

1.vercel
2.上传小文件 [testcsv.csv](https://github.com/user-attachments/files/16283941/testcsv.csv)
3.简单提问,想尝试看看是否会读取

### Expected Behavior

1.不确定是预期内的结果还是,没有发现的 目前关闭插件使用Rag可以正常上传文件并被读取
2.只是文案向的优化,看看是否值得

3.点击刷新按钮重问,模拟日常可能想获取一些其他答案的时候

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by Hk-Gosuto** [comment]
如果你是vercel部署的话需要配置 `NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN=1` 强制使用 node 运行时来使用 rag 功能
