### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by qi-mooo** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#295]
### 📦 部署方式

Docker

### 📌 软件版本

275308b

### 💻 系统环境

Other Linux

### 📌 系统版本

arch

### 🌐 浏览器

Chrome

### 📌 浏览器版本

120

### 🐛 问题描述

USE_OPENAI_ENDPOINT_FOR_ALL_MODELS
功能失效，即使将他设置成 1 ，在实际请求时其他模型还是使用模型路由，并没有成功切换成 OpenAI 路由
![Screenshot_2024-07-25-22-08-49-631_mark via-edit](https://github.com/user-attachments/assets/2c4a79bd-fc86-45a3-a499-25b545432c5d)

**Comment by MuRo-J** [comment]
还有一个附近的问题,不过比题主这个问题要轻微,上游的动静实在太大,DEFAULT_MODEL参数也失效了,但是他们后续补丁处理了,头大,他们整活呢

**Comment by Hk-Gosuto** [comment]
前些天的代码合并搞出了好多问题 晚一点我处理一下

**Comment by Hk-Gosuto** [comment]
> 还有一个附近的问题,不过比题主这个问题要轻微,上游的动静实在太大,DEFAULT_MODEL参数也失效了,但是他们后续补丁处理了,得辛苦大佬需要的时候合并
> 
> btw目前已知的一个常用环境变量设置方式: CUSTOM_MODELS 举例: 原使用方法:
> 
> ```
> -all,+gpt-4o,+gpt-4o-mini,+gpt-4-turbo,+gemini-1.5-flash-latest,+gemini-1.5-pro-latest,+gpt-3.5-turbo,+claude-3-opus-20240229,+claude-3-5-sonnet-20240620,gemini-1.5-pro-latest=gemini-1.5-pro,claude-3-opus-20240229=claude-3-opus,claude-3-5-sonnet-20240620=claude-3.5-sonnet,gemini-1.5-flash-latest=gemini-1.5-flash
> ```
> 
> 会出现一个问题就是,gpt-4o会同时命中openai + azure等,会导致模型列表多处很多可能不需要使用的模型列表 改为用法:
> 
> ```
> -all,+gpt-4o@openai=gpt-4o,+gpt-4o-mini@openai=gpt-4o-mini,+gpt-4-turbo@openai=gpt-4-turbo,+gemini-1.5-flash-latest@google=gemini-1.5,+gemini-1.5-pro-latest@google=gemini-1.5-pro,+claude-3-opus-20240229@anthropic=claude-3-opus,+claude-3-5-sonnet-20240620@anthropic=claude-3.5-sonnet
> ```

没找到上游这部分的代码的差别 可否指出修复部分的代码  我单独合一下这部分

**Comment by MuRo-J** [comment]
> > 还有一个附近的问题,不过比题主这个问题要轻微,上游的动静实在太大,DEFAULT_MODEL参数也失效了,但是他们后续补丁处理了,得辛苦大佬需要的时候合并
> > btw目前已知的一个常用环境变量设置方式: CUSTOM_MODELS 举例: 原使用方法:
> > ```
> > -all,+gpt-4o,+gpt-4o-mini,+gpt-4-turbo,+gemini-1.5-flash-latest,+gemini-1.5-pro-latest,+gpt-3.5-turbo,+claude-3-opus-20240229,+claude-3-5-sonnet-20240620,gemini-1.5-pro-latest=gemini-1.5-pro,claude-3-opus-20240229=claude-3-opus,claude-3-5-sonnet-20240620=claude-3.5-sonnet,gemini-1.5-flash-latest=gemini-1.5-flash
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会出现一个问题就是,gpt-4o会同时命中openai + azure等,会导致模型列表多处很多可能不需要使用的模型列表 改为用法:
> > ```
> > -all,+gpt-4o@openai=gpt-4o,+gpt-4o-mini@openai=gpt-4o-mini,+gpt-4-turbo@openai=gpt-4-turbo,+gemini-1.5-flash-latest@google=gemini-1.5,+gemini-1.5-pro-latest@google=gemini-1.5-pro,+claude-3-opus-20240229@anthropic=claude-3-opus,+claude-3-5-sonnet-20240620@anthropic=claude-3.5-sonnet
> > ```
> 
> 没找到上游这部分的代码的差别 可否指出修复部分的代码 我单独合一下这部分

感谢您费心,
DEFAULT_MODULE他们通过
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/2fd68bcac3f8aa9e8227b9f93acb4518e7e1165a
修复了

CUSTUM_MODULE暂时无解,只能自己修改变量用法解决同时有 chatgpt-4o(OpenAI) 和chatgpt-4o(Azure)的问题
如这里
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5030
![CleanShot 2024-07-26 at 22 33 22](https://github.com/user-attachments/assets/e044dad2-9c4d-45f7-aa29-51b902cdc640)

**Comment by Hk-Gosuto** [comment]
> > > 还有一个附近的问题,不过比题主这个问题要轻微,上游的动静实在太大,DEFAULT_MODEL参数也失效了,但是他们后续补丁处理了,得辛苦大佬需要的时候合并
> > > btw目前已知的一个常用环境变量设置方式: CUSTOM_MODELS 举例: 原使用方法:
> > > ```
> > > -all,+gpt-4o,+gpt-4o-mini,+gpt-4-turbo,+gemini-1.5-flash-latest,+gemini-1.5-pro-latest,+gpt-3.5-turbo,+claude-3-opus-20240229,+claude-3-5-sonnet-20240620,gemini-1.5-pro-latest=gemini-1.5-pro,claude-3-opus-20240229=claude-3-opus,claude-3-5-sonnet-20240620=claude-3.5-sonnet,gemini-1.5-flash-latest=gemini-1.5-flash
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 会出现一个问题就是,gpt-4o会同时命中openai + azure等,会导致模型列表多处很多可能不需要使用的模型列表 改为用法:
> > > ```
> > > -all,+gpt-4o@openai=gpt-4o,+gpt-4o-mini@openai=gpt-4o-mini,+gpt-4-turbo@openai=gpt-4-turbo,+gemini-1.5-flash-latest@google=gemini-1.5,+gemini-1.5-pro-latest@google=gemini-1.5-pro,+claude-3-opus-20240229@anthropic=claude-3-opus,+claude-3-5-sonnet-20240620@anthropic=claude-3.5-sonnet
> > > ```
> > 
> > 
> > 没找到上游这部分的代码的差别 可否指出修复部分的代码 我单独合一下这部分
> 
> 感谢您费心, DEFAULT_MODULE他们通过 [ChatGPTNextWeb@2fd68bc](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/2fd68bcac3f8aa9e8227b9f93acb4518e7e1165a) 修复了
> 
> CUSTUM_MODULE暂时无解,只能自己修改变量用法解决同时有 chatgpt-4o(OpenAI) 和chatgpt-4o(Azure)的问题 如这里 [ChatGPTNextWeb#5030](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5030) ![CleanShot 2024-07-26 at 22 33 22](https://private-user-images.githubusercontent.com/64354330/352568433-e044dad2-9c4d-45f7-aa29-51b902cdc640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjM1MjEsIm5iZiI6MTcyMjE2MzIyMSwicGF0aCI6Ii82NDM1NDMzMC8zNTI1Njg0MzMtZTA0NGRhZDItOWM0ZC00NWY3LWFhMjktNTFiOTAyY2RjNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEwNDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjFhMTlkN2JjZGU1MWY3ODE0Y2YyM2MyMTAzNzE1YjZjMTQ5ZjZhNzNkZGMyNjExMzZmMzhhMTMzOTdiN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pYI5uBKW7oqxJ8gAaeDQfHbBnWNuSMBvGVAga0EUTKA)

单独 merge 了 collectModelTableWithDefaultModel 方法，可以试试看问题是否解决。

**Comment by MuRo-J** [comment]
> > > > 还有一个附近的问题,不过比题主这个问题要轻微,上游的动静实在太大,DEFAULT_MODEL参数也失效了,但是他们后续补丁处理了,得辛苦大佬需要的时候合并
> > > > btw目前已知的一个常用环境变量设置方式: CUSTOM_MODELS 举例: 原使用方法:
> > > > ```
> > > > -all,+gpt-4o,+gpt-4o-mini,+gpt-4-turbo,+gemini-1.5-flash-latest,+gemini-1.5-pro-latest,+gpt-3.5-turbo,+claude-3-opus-20240229,+claude-3-5-sonnet-20240620,gemini-1.5-pro-latest=gemini-1.5-pro,claude-3-opus-20240229=claude-3-opus,claude-3-5-sonnet-20240620=claude-3.5-sonnet,gemini-1.5-flash-latest=gemini-1.5-flash
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 会出现一个问题就是,gpt-4o会同时命中openai + azure等,会导致模型列表多处很多可能不需要使用的模型列表 改为用法:
> > > > ```
> > > > -all,+gpt-4o@openai=gpt-4o,+gpt-4o-mini@openai=gpt-4o-mini,+gpt-4-turbo@openai=gpt-4-turbo,+gemini-1.5-flash-latest@google=gemini-1.5,+gemini-1.5-pro-latest@google=gemini-1.5-pro,+claude-3-opus-20240229@anthropic=claude-3-opus,+claude-3-5-sonnet-20240620@anthropic=claude-3.5-sonnet
> > > > ```
> > > 
> > > 
> > > 没找到上游这部分的代码的差别 可否指出修复部分的代码 我单独合一下这部分
> > 
> > 
> > 感谢您费心, DEFAULT_MODULE他们通过 [ChatGPTNextWeb@2fd68bc](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/2fd68bcac3f8aa9e8227b9f93acb4518e7e1165a) 修复了
> > CUSTUM_MODULE暂时无解,只能自己修改变量用法解决同时有 chatgpt-4o(OpenAI) 和chatgpt-4o(Azure)的问题 如这里 [ChatGPTNextWeb#5030](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5030) ![CleanShot 2024-07-26 at 22 33 22](https://private-user-images.githubusercontent.com/64354330/352568433-e044dad2-9c4d-45f7-aa29-51b902cdc640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjM1MjEsIm5iZiI6MTcyMjE2MzIyMSwicGF0aCI6Ii82NDM1NDMzMC8zNTI1Njg0MzMtZTA0NGRhZDItOWM0ZC00NWY3LWFhMjktNTFiOTAyY2RjNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEwNDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjFhMTlkN2JjZGU1MWY3ODE0Y2YyM2MyMTAzNzE1YjZjMTQ5ZjZhNzNkZGMyNjExMzZmMzhhMTMzOTdiN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pYI5uBKW7oqxJ8gAaeDQfHbBnWNuSMBvGVAga0EUTKA)
> 
> 单独 merge 了 collectModelTableWithDefaultModel 方法，可以试试看问题是否解决。

再次说声辛苦啦,DEFAUT_MODULE正常了,可以正常起作用
