### ISSUE TITLE
[Bug] 配置好的RAG功能无法正常运行

### ISSUE THREAD

**Issue by xssoo** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#296]
### 📦 部署方式

官方安装包, Docker

### 📌 软件版本

v2.12.4

### 💻 系统环境

Ubuntu

### 📌 系统版本

22.04

### 🌐 浏览器

Chrome, Safari

### 📌 浏览器版本

100

### 🐛 问题描述

单独的VPS主机，DOCKER部署，按教程配置好了RAG，然后聊天中上传文件，上传后的文件可以点击打开：https://xxx/api/file/1722058370669.txt
但是聊天中好像并没有把文件发送过去，显示如图：
![b](https://github.com/user-attachments/assets/79566448-17ac-43a8-b1ad-b07329336b4d)

### 🚦 期望结果

我看教程中的图片，发送文件后，会显示出处理的步骤，可在我的聊天中并没有显示。

**Comment by Hk-Gosuto** [comment]
检查一下文件是否成功上传，也尝试更新一下镜像 gosuto/chatgpt-next-web-langchain:nightly
