### ISSUE TITLE
[Bug] RAG功能开启后，聊天无反应

### ISSUE THREAD

**Issue by Silentely** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#299]
### 📦 Deployment Method

Docker

### 📌 Version

2.13.1-nightly

### 💻 Operating System

Ubuntu

### 📌 System Version

20.04

### 🌐 Browser

Edge

### 📌 Browser Version

127.0.2651.105

### 🐛 Bug Description

Docker通过变量开启RAG功能并按教程配置好RAG后，页面插件开启，随便发送一句话都是查看网络是通过nodejs调用（不是只有在调用RAG时才是nodejs吗），查看第三方one-api日志是有正常调用，关闭所有插件后（仅关闭文件浏览器插件也不行）再次聊天是正常回复，路径是completions，但是仅仅是chatgpt是这样，换gemini与claude模型开启插件也正常回复

开启插件时无反应 网络活动显示nodejs
![f26b2caeceb0edb31b29b84ef5c0e49d.jpeg](https://ice.frostsky.com/2024/08/20/f26b2caeceb0edb31b29b84ef5c0e49d.jpeg)
![bf92011bbe899c133d9316afba598b92.jpeg](https://ice.frostsky.com/2024/08/20/bf92011bbe899c133d9316afba598b92.jpeg)

开启插件时无反应 网络活动显示nodejs
![8c858127cf25d8c04178fc60e8137aba.jpeg](https://ice.frostsky.com/2024/08/20/8c858127cf25d8c04178fc60e8137aba.jpeg)
![16cada9d6a53217d5f1b1042ed2d5cf1.jpeg](https://ice.frostsky.com/2024/08/20/16cada9d6a53217d5f1b1042ed2d5cf1.jpeg)

nginx日志
1.1.1.1 2024-08-20T15:06:57+08:00 "POST /api/langchain/tool/agent/nodejs HTTP/2.0" chat-web.xx.xx 499 0 "https://chat-web.xx.xx/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0" "123.123.123.123"

关闭插件后聊天回复正常，网络活动显示completions
![ea6eb8b9b167d9600571f0c2e4e82475.jpeg](https://ice.frostsky.com/2024/08/20/ea6eb8b9b167d9600571f0c2e4e82475.jpeg)

one-api后端调用日志
![08b3b6b8e4ed85c9d10d019e9e9a0032.jpeg](https://ice.frostsky.com/2024/08/20/08b3b6b8e4ed85c9d10d019e9e9a0032.jpeg)

### 📷 Recurrence Steps

页面点击开启插件后聊天无回复
页面关闭插件聊天正常回复

### 🚦 Expected Behavior

1

### 📝 Additional Information

1

**Comment by Hk-Gosuto** [comment]
docker 部署默认就使用 node 环境的接口，你转发的上游服务是否支持函数调用？

**Comment by Silentely** [comment]
> docker 部署默认就使用 node 环境的接口，你转发的上游服务是否支持函数调用？

上游（https://github.com/MartialBE/one-hub）是支持调用，因为前几个版本也是这个上游也能正常函数调用，也是最近两天发现更新镜像后调用不了

**Comment by Hk-Gosuto** [comment]
应该是最近的插件调用业务变更导致的，可以试下添加这个环境变量 `LANGCHAIN_CALLBACKS_BACKGROUND=true`

**Comment by Silentely** [comment]
> LANGCHAIN_CALLBACKS_BACKGROUND=true

感谢，增加变量`LANGCHAIN_CALLBACKS_BACKGROUND=true`后恢复正常了，能正常调用了
