### ISSUE TITLE
[Bug] 使用vercel部署出现504报错代码

### ISSUE THREAD

**Issue by Arthur409** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#302]
### 📦 部署方式

Vercel

### 📌 软件版本

最近

### 💻 系统环境

Windows

### 📌 系统版本

Windows11

### 🌐 浏览器

Edge

### 📌 浏览器版本

最新

### 🐛 问题描述

使用vercel部署产生代码：
{"error": {"code": "504", "message": "An error occurred with your deployment"}}
<img width="908" alt="屏幕截图 2024-08-24 144633" src="https://github.com/user-attachments/assets/5dc083d6-f38d-489b-b4d5-fd35c7d04ed4">

### 🚦 期望结果

请求尽快修复

**Comment by AAlexDing** [comment]
me,too

**Comment by Hk-Gosuto** [comment]
复现了，调查中

**Comment by MrPeterJin** [comment]
merge 了如上 commit 之后仍报 504 错误，辛苦修复

**Comment by Hk-Gosuto** [comment]
正在处理，今天会修复
