### ISSUE TITLE
[Bug] STT error

### ISSUE THREAD

**Issue by DDMeaqua** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#305]
### 📦 Deployment Method

Other

### 📌 Version

2.13

### 💻 Operating System

macOS

### 📌 System Version

14

### 🌐 Browser

Chrome

### 📌 Browser Version

128.0.6613.114

### 🐛 Bug Description

OpenAI whisper STT
手机上正常，电脑端使用 Safari 正常，但是 Chrome 有报错

### 📷 Recurrence Steps

![image](https://github.com/user-attachments/assets/9896026f-0511-42c1-8c8e-78e9dfc3a24f)

![image](https://github.com/user-attachments/assets/feb39e23-8433-4321-a03c-794c86d27b80)

**Comment by Hk-Gosuto** [comment]
做了一些处理，可以试一下，手边没有 whisper 接口。

**Comment by DDMeaqua** [comment]
我测试了一下，还是没用，这个bug只会在电脑端chrome和edge里有，Firefox和safari是正常的，手机端的chrome也是正常，很奇怪（这次改动似乎出现了一个新bug）

![image](https://github.com/user-attachments/assets/7595293c-0ab8-499d-a900-3f3d2b0d0c66)

**Comment by Hk-Gosuto** [comment]
可以再试试了 我用azure部署的whisper，测试了edge（128.0.2739.42）和chrome（128.0.6613.114）都正常了。

**Comment by DDMeaqua** [comment]
感谢大佬，辛苦了，但我试了下 openai 的，又出现新的问题了，不过查了下这个报错似乎是openai那边的问题？
![image](https://github.com/user-attachments/assets/5854b565-81b2-4adc-ba67-205de169fefc)

**Comment by Hk-Gosuto** [comment]
你这个报错看起来应该是上游接口出问题了

**Comment by DDMeaqua** [comment]
但是接口报错按道理来说其他浏览器都应该调用失败...... 这个bug困扰我几天，因为我实在想不明白为什么同一套代码调用同一个接口，会出现电脑端Chrome浏览器和edge浏览器中失败，其他的浏览器正常😂（手机端调接口也正常）

**Comment by Hk-Gosuto** [comment]
可以用postman单独调下接口试试，排除一下接口问题。

**Comment by DDMeaqua** [comment]
我用apifox测试过，应该能排除接口问题
![image](https://github.com/user-attachments/assets/4232591b-9d17-42f1-a00a-22fd88772ad2)

**Comment by Hk-Gosuto** [comment]
什么浏览器和版本会出现上面的问题，顺便看下调用时接口form的数据是否有异常，比如空的之类。

**Comment by DDMeaqua** [comment]
chrome和edge的pc端会出现这个问题，和firefox对比如下， 似乎formdata有问题？

![image](https://github.com/user-attachments/assets/2388eb51-1486-4d9e-9710-6ac6d04b08ee)

![image](https://github.com/user-attachments/assets/8b27caf0-0d34-4b24-8efd-9f29570114a8)

**Comment by Hk-Gosuto** [comment]
你的密钥暴露了 记得换一个 你看下网络请求中的file有没有数据
![image](https://github.com/user-attachments/assets/7d0277c7-a778-49d7-9903-b8138b60aa3d)

**Comment by DDMeaqua** [comment]
有的
![image](https://github.com/user-attachments/assets/e7f82006-3b14-492f-8568-a629f6246656)

**Comment by Hk-Gosuto** [comment]
方便的话发我一下key和api地址吧，我跑一下测试。
可以发送到：gosuto@n3xt.chat 或者 在Q群里私聊我。

**Comment by DDMeaqua** [comment]
我手上也没key了😂

**Comment by Hk-Gosuto** [comment]
> 我手上也没key了😂

主要我用 Azure 部署的版本复现不了你的问题，或者你把详细的浏览器版本发我一下我再试试看。

**Comment by DDMeaqua** [comment]
![image](https://github.com/user-attachments/assets/3f32830a-f053-4bd4-8785-1895c14edbe8)
