### ISSUE TITLE
[Bug] 如何使上传的图片转为URL，而不是base64

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#307]
### 📦 部署方式

Docker

### 📌 软件版本

2.12.4

### 💻 系统环境

Other Linux

### 📌 系统版本

Debian 12

### 🌐 浏览器

Edge

### 📌 浏览器版本

最新

### 🐛 问题描述

我在linux上部署了此项目，使用docker。如何把上传的图片默认改为url，而不是base64？

**Comment by Hk-Gosuto** [comment]
某次合并上游代码后就没有这个功能了，是什么场景需要上传而不是用编码后的图片？

**Comment by cui8** [comment]
> 某次合并上游代码后就没有这个功能了，是什么场景需要上传而不是用编码后的图片？

原来这样啊，我就记得以前图片是链接。没需求就随便问下。麻烦大佬了
