### ISSUE TITLE
大佬，bing搜索我的以前用的好好的，现在报错了

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#31]
前几天拉取的Docker版本，刚弄好bing搜索还可以，现在怎么使用报错了。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/edc25352-e0b0-4288-b5ba-1456ab88b8c8)
其实昨天就想问大佬这个问题，但自己问的太多了。现在还是无法使用，实在抱歉，如果可以，我可以把bing搜索的key给大佬，是我不会玩吗？

**Comment by Hk-Gosuto** [comment]
用的是哪一个版本的镜像？

**Comment by cui8** [comment]
> 用的是哪一个版本的镜像？

我现在换成仓库最新的bing搜索也不行。大佬可以拉取下这个镜像。
```
docker pull 2650714479/chatgpt-next-web-langchain:1.0.3
```

**Comment by cui8** [comment]
这个镜像用的是大佬仓库最新的代码，我照原版文档里的公众号文章教程改了些界面上的文字，应该与大佬的没有差别，我只会照猫画虎改些文字

**Comment by Hk-Gosuto** [comment]
试了一下，没发现问题，检查一下配置 `BING_SEARCH_API_KEY` 是否可用吧。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/8c6b92d8-2263-4c3e-8fa0-d877525c3543)

**Comment by cui8** [comment]
> 试了一下，没发现问题，检查一下配置 `BING_SEARCH_API_KEY` 是否可用吧。 ![image](https://user-images.githubusercontent.com/14031260/269840842-8c6b92d8-2263-4c3e-8fa0-d877525c3543.png)

bing key：901ab2e9e27c4971aa502f169db3adf5

我这里不可以，大佬能帮忙看下可以用吗

**Comment by Hk-Gosuto** [comment]
> > 试了一下，没发现问题，检查一下配置 `BING_SEARCH_API_KEY` 是否可用吧。 ![image](https://user-images.githubusercontent.com/14031260/269840842-8c6b92d8-2263-4c3e-8fa0-d877525c3543.png)
> 
> bing key：901ab2e9e27c4971aa502f169db3adf5
> 
> 我这里不可以，大佬能帮忙看下可以用吗

你这个key是可用的，检查一下是不是你的网络问题导致的，也可以考虑使用其它方案。

**Comment by cui8** [comment]
> > > 试了一下，没发现问题，检查一下配置 `BING_SEARCH_API_KEY` 是否可用吧。 ![image](https://user-images.githubusercontent.com/14031260/269840842-8c6b92d8-2263-4c3e-8fa0-d877525c3543.png)
> > 
> > 
> > bing key：901ab2e9e27c4971aa502f169db3adf5
> > 我这里不可以，大佬能帮忙看下可以用吗
> 
> 你这个key是可用的，检查一下是不是你的网络问题导致的，也可以考虑使用其它方案。

谢谢大佬，我更换为今天刚更新的直连百度的功能，可以使用了，不用bing了
