### ISSUE TITLE
[Feature Request] 可以支持一下在render上部署吗？

### ISSUE THREAD

**Issue by winter2399** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#310]
### 🥰 需求描述

在render上使用最新docker镜像，设置好环境变量，提示运行成功，但访问链接显示502，估计内部端口什么没弄好，render不知道什么端口导致。
但在koyeb上倒是按照上面的方法没有什么问题，成功部署且可以访问。

### 🧐 解决方案

大佬可以在render上使用最新docker镜像部署下看下什么问题导致无法访问的吗？

### 📝 补充信息

恳请大佬能支持下。
如果大佬不方便可以说下，我会关闭这个提问的。
打扰大佬非常抱歉，我知道这个在大佬范围之外。
再次感谢！！！

**Comment by Hk-Gosuto** [comment]
我来试试看

**Comment by winter2399** [comment]
> docker 部署的问题没找到，不过你可以通过源码构建，语言那里选择 `Node` 就行 ![image](https://private-user-images.githubusercontent.com/14031260/375370686-cdeed500-8fdc-4112-a18f-a16c2964e7cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjM4MTAsIm5iZiI6MTcyODYyMzUxMCwicGF0aCI6Ii8xNDAzMTI2MC8zNzUzNzA2ODYtY2RlZWQ1MDAtOGZkYy00MTEyLWExOGYtYTE2YzI5NjRlN2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA1MTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNDdjN2I1MGY2NTM4OTE4NmQzODJlYjU3ZjE4MWEyNTliNTYxNDhkMjk0YTM2NzY4NDcwZDU0N2E2MGJiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8bmvjaHNrfvGmk0IEIB_4OQ2uPx2rcUZ0DcYf1c8I_A)

非常感谢，node部署确实成功啦，我自己折腾了好久，一直docker，最后还没成功。
大佬就是专业，还能node部署，一试就成功啦，专业的事情专业人士解决，赞👍
