### ISSUE TITLE
[Feature Request] 增加一个功能

### ISSUE THREAD

**Issue by qingyuan0o0** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#311]
### 🥰 需求描述

建议增加一个变量,不输入则使用默认可以自定义的duckduckgo的地址

### 🧐 解决方案

方案1:用cf域名worker,曾经我进入那个包修改过地址,可以实现用cf在墙内,速度很快
方案2:给这些访问速度慢的url,增加一个url,项目在此https://github.com/1234567Yang/cf-proxy-ex/

### 📝 补充信息

比如[duckduckai](https://y.demo.wvusd.homes/https://duckduckgo.com/?t=h_&q=hi&ia=chat)
比如[搜索](https://y.demo.wvusd.homes/https://duckduckgo.com/?t=h_&q=ip)

**Comment by Hk-Gosuto** [comment]
这种倒也是个办法，先在 ddg 插件里加个环境变量好了。

**Comment by Hk-Gosuto** [comment]
使用环境变量 `DDG_API_PROXY_PREFIX` 添加插件接口前缀

**Comment by qingyuan0o0** [comment]
之前推荐的那个项目在浏览器打开正常,但是测试使用git clone https://test.com/https://github.com是异常的,推荐用他原来的版本
https://github.com/gaboolic/cloudflare-reverse-proxy/
