### ISSUE TITLE
[Feature Request] 能否自动保活 Supabase 项目

### ISSUE THREAD

**Issue by winter2399** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#312]
### 🥰 需求描述

今天需要使用文档分析功能，搞了半天是 Supabase 项目因为没有活动记录被暂停了。
![image](https://github.com/user-attachments/assets/899c79af-c167-4f15-aa30-1f2c32002ad9)
目前，文档分析功能我偶尔使用，但依赖 Supabase，每隔7天就要重启项目，好麻烦。
![image](https://github.com/user-attachments/assets/2aca7177-7b5c-4242-a9f6-cd1f04ef0a3b)
大佬有什么自动保活的办法吗？

---

每次都打扰大佬，实在不好意思，给大佬添麻烦了。

### 🧐 解决方案

希望大佬能有个保活 Supabase 项目的办法，对于我来说不经常使用文档分析，导致 Supabase 项目老被暂停。

**Comment by Hk-Gosuto** [comment]
也不一定非要用线上服务，自托管一个也可以：
https://supabase.com/docs/guides/self-hosting

**Comment by winter2399** [comment]
> 也不一定非要用线上服务，自托管一个也可以： https://supabase.com/docs/guides/self-hosting

原来可以自己托管，谢谢大佬解答。这就去搞搞
