### ISSUE TITLE
[Bug] Artifacts需刷新页面/切换聊天tab 来显示HTML

### ISSUE THREAD

**Issue by MuRo-J** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#314]
### 📦 部署方式

Vercel

### 📌 软件版本

最新

### 💻 系统环境

macOS

### 📌 系统版本

默认

### 🌐 浏览器

Chrome

### 📌 浏览器版本

默认

### 🐛 问题描述

大佬,感谢您的付出,现在最喜欢您的版本
今天尝试了下
**Artifacts需要刷新页面,或者切换聊天刷新后能正常渲染html**
不确定是否是预期结果

### 📷 复现步骤

见录屏
https://github.com/user-attachments/assets/6056526e-dbb0-4bff-abfd-d055269da601

**Comment by Hk-Gosuto** [comment]
使用其他方式实现了 Artifacts 页面渲染的监听，试试看是否修复了。

**Comment by MuRo-J** [comment]
哥我发现了错误原因,
app/api/webdav/[...path]/route.ts
的第9行, allowedWebDevEndpoints 应该是 allowedWebDavEndpoints
或者修改其他的  *Dav*
小问题,我自己先手动修改了本地 

对git不熟练不太会提交pr到上游,给您添麻烦啦
