### ISSUE TITLE
[Feature Request] 能否把界面模型列表的提供商名字不展示

### ISSUE THREAD

**Issue by winter2399** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#316]
### 🥰 需求描述

![image](https://github.com/user-attachments/assets/c1edebca-1210-4b98-b635-8a5f8a879d46)
上面的提供商名字能不展示吗？看着好长，只展示模型名可以吗？

### 🧐 解决方案

请大佬修改源码，只展示模型名，不展示提供商名字。

### 📝 补充信息

如果不可以，可以说下改哪些地方吗？

**Comment by cnmozzie** [comment]
其实我更希望大佬能解决这个上游的这个[issue](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5050)，里面有个PR5160，但是不知道为什么一直不合并

**Comment by Hk-Gosuto** [comment]
显示提供商名字估计是主要用来区分OpenAI和Auzre这种模型名一样但是提供商不一样的。
删除某些提供商的模型倒是挺实用的，明天我处理一下。

**Comment by winter2399** [comment]
> 显示提供商名字估计是主要用来区分OpenAI和Auzre这种模型名一样但是提供商不一样的。 删除某些提供商的模型倒是挺实用的，明天我处理一下。

大佬能否加个模型列表不显示提供商的环境变量（弱弱问下）。
这个需求确实有点小众了，大佬不加也不麻烦大佬了，毕竟大佬无私维护项目已经很辛苦了

**Comment by MuRo-J** [comment]
![image](https://github.com/user-attachments/assets/18200fcb-1dad-4424-9801-fd65ca17ae43)
现在的CUSTOM_MODELS 配置能达成这个效果呢，感觉可以满足嘞
```
-all,+gpt-4o@openai=gpt-4o,+gpt-4o-mini@openai=gpt-4o-mini,+o1-preview@openai=gpt-o1,+o1-mini@openai=gpt-o1-mini,+gemini-1.5-flash-latest@google=gemini-1.5,+gemini-1.5-pro-latest@google=gemini-1.5-pro,+claude-3-opus-20240229@anthropic=claude-3-opus,+claude-3-5-sonnet-20241022@anthropic=claude-3.5-sonnet
```
然后还有个
DEFAULT_MODEL
配合使用前置自己常用模型
```
gpt-4o
```

**Comment by winter2399** [comment]
> ![image](https://private-user-images.githubusercontent.com/64354330/382001050-18200fcb-1dad-4424-9801-fd65ca17ae43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDMxODEsIm5iZiI6MTczMDQ0Mjg4MSwicGF0aCI6Ii82NDM1NDMzMC8zODIwMDEwNTAtMTgyMDBmY2ItMWRhZC00NDI0LTk4MDEtZmQ2NWNhMTdhZTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA2MzQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZDEwNzc3YjgzNDZiNjhkZDM3MmY3NzhmNmQ4MWQ4YzYzZTMzOWUwMWE3YzMxOWE1MzBiM2JjNDYxNDdjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v2Kex0jCY7Rpz_JRcFJ5Sfo3edqmkmXdA04WiMkG7mI) 现在的CUSTOM_MODELS 配置能达成这个效果呢，感觉可以满足嘞
> 
> ```
> -all,+gpt-4o@openai=gpt-4o,+gpt-4o-mini@openai=gpt-4o-mini,+o1-preview@openai=gpt-o1,+o1-mini@openai=gpt-o1-mini,+gemini-1.5-flash-latest@google=gemini-1.5,+gemini-1.5-pro-latest@google=gemini-1.5-pro,+claude-3-opus-20240229@anthropic=claude-3-opus,+claude-3-5-sonnet-20241022@anthropic=claude-3.5-sonnet
> ```
> 
> 然后还有个 DEFAULT_MODEL 配合使用前置自己常用模型
> 
> ```
> gpt-4o
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/64354330/382002178-d53e1cad-0837-43a8-a518-5dae5851cc9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDMxODEsIm5iZiI6MTczMDQ0Mjg4MSwicGF0aCI6Ii82NDM1NDMzMC8zODIwMDIxNzgtZDUzZTFjYWQtMDgzNy00M2E4LWE1MTgtNWRhZTU4NTFjYzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA2MzQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOWMyMmE1YmUxNzgxMzcyNzIzZWRiY2U0NTBjN2E3OGNiYjRmMmMxM2Y4YjA2ZjYzZGEwMGJmMjMxNDkwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xjhk7sMF2fBsz5h4pb7fylLxE807-ON8oZVf10sHKOA)

![image](https://github.com/user-attachments/assets/82a47116-6cee-4124-855c-2c2cb58737a2)
是的，非常好用，我也在使用。主要是因为最新版不知道模型怎么排序，模型与在代码里出现的顺序不一致，而为了顺序修改提供商，看着憋扭

**Comment by Hk-Gosuto** [comment]
加了个环境变量，配置 `DISABLE_MODEL_PROVIDER_DISPLAY=1` 关闭 Provider 显示。
