### ISSUE TITLE
[Feature] 同步上游模型服务商逻辑

### ISSUE THREAD

**Issue by Hk-Gosuto** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#317]
### 🥰 需求描述

同步上游模型服务商逻辑

### 🧐 解决方案

同步上游模型服务商逻辑

### 📝 补充信息

本次同步将除 OpenAI 插件部分代码外的模型服务商代码和逻辑进行同步，将新增以下模型提供商：
- xai
- tencent
- moonshot
- iflytek
- chatglm

**Comment by MuRo-J** [comment]
辛苦大佬啦~
