### ISSUE TITLE
[Bug] 搜索框输入 `[` 导致页面崩溃

### ISSUE THREAD

**Issue by SuiYunsy** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#319]
### 📦 Deployment Method

Official installation package

### 📌 Version

n3xt.chat

### 💻 Operating System

Windows

### 📌 System Version

Win10

### 🌐 Browser

Edge

### 📌 Browser Version

130

### 🐛 Bug Description

聊天记录中含有特殊字段时，输入框中输入 `[` 会导致页面崩溃。

![image](https://github.com/user-attachments/assets/b55ad340-7c97-4a8e-aae0-779a73495a42)

### 📷 Recurrence Steps

使用 https://n3xt.chat 可以复现：

首先确保聊天记录中含有这样一段话：`访问密码不正确或为空，请前往[登录](/#/auth)页输入正确的访问密码，或者在[设置](/#/settings)页填入你自己的 OpenAI API Key。`

或者简短一点：`请前往[登录](/#/auth)页，或者在[设置](/#/settings)页`。

然后在左栏搜索聊天框里输入 `[` 符号，就会触发页面崩溃。

![image](https://github.com/user-attachments/assets/d75cb804-ee2f-4539-ad08-7b3bec7ede84)

**Comment by SuiYunsy** [comment]
目前测试，如果聊天记录中有 `[*+?()\` 并且搜索框里输入其中一个，就会报错。
遂让AI修复了一下，貌似没问题了😀

![image](https://github.com/user-attachments/assets/74c5bf04-8060-4343-b18e-72420a02727e)

**Comment by Hk-Gosuto** [comment]
使用了差不多的方案，对特殊字符作了转义。
