### ISSUE TITLE
看以前提问记录，不知大佬是否有考虑适配Azure OpenAI

### ISSUE THREAD

**Issue by winter2399** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#32]
如果不能适配，真的非常遗憾。

**Comment by Hk-Gosuto** [comment]
昨天正好有尝试一些方案，晚点我会更新一个文档关联到 README 上。

**Comment by winter2399** [comment]
> 昨天正好有尝试一些方案，晚点我会更新一个文档关联到 README 上。

哇欧，太棒了，我非常需要，一直会关注的。如果大佬需要Azure OpenAI参数的，可以找我，只不过大佬要费心，我可能不知道从哪里获取

**Comment by Hk-Gosuto** [comment]
参考这个文档配置试试：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/azure-openai-cn.md

**Comment by winter2399** [comment]
> 参考这个文档配置试试：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/azure-openai-cn.md

大佬效劳好高，能正常使用了，太感谢大佬了

**Comment by winter2399** [comment]
> 参考这个文档配置试试：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/azure-openai-cn.md

真的很佩服向大佬这样的人，还热心

**Comment by winter2399** [comment]
> 参考这个文档配置试试：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/azure-openai-cn.md

真的是GitHub很难见到向大佬这么热心肠的人了，大佬是我的榜样👍强

**Comment by winter2399** [comment]
> 参考这个文档配置试试：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/azure-openai-cn.md

辛苦了，谢谢大佬无私奉献，用的非常完美，没有任何bug
