### ISSUE TITLE
[Bug] claude 有点问题请求都发不出去

### ISSUE THREAD

**Issue by MuRo-J** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#324]
### 📦 Deployment Method

Vercel

### 📌 Version

lateset

### 💻 Operating System

macOS

### 📌 System Version

any

### 🌐 Browser

Chrome

### 📌 Browser Version

any

### 🐛 Bug Description

测试了下我自己部署的和大佬主页的 
![CleanShot 2024-11-20 at 21 38 33](https://github.com/user-attachments/assets/7dd1c539-eff6-468e-982d-1d15d2108dc7)
表现还不太一样,但是最终都是无请求出去,
如果需要key我稍后发送您的Q

**Comment by MuRo-J** [comment]
回滚合并多模型版本前的代码是可以的,
对前端代码苦手,无法定位原因啦,辛苦您

**Comment by Hk-Gosuto** [comment]
是使用的claude官方API么？

**Comment by MuRo-J** [comment]
> 是使用的claude官方API么？

是的,已经发您Q 辛苦看看,能复现不

**Comment by MuRo-J** [comment]
> 修复了，试试看吧。

感谢感谢辛苦了,插件按钮是不能点亮的,否则还是会出现,这个是预期内的不

**Comment by laxfer** [comment]
> 修复了，试试看吧。

现在的最新版本，确实还有问题，出现在anthropic无法调用插件的问题，经检查源码，问题出现在/ChatGPT-Next-Web-LangChain/blob/main/app/client/platforms/anthropic.ts中87行代码的这个函数上，toolAgentChat(options: AgentChatOptions): Promise<void> {
    throw new Error("Method not implemented.");
  }，从代码分析来看，你这边想改成ChatGPT-Next-Web主版本插件的原生调用，但是anthropic在调用插件的时候，还是执行到了toolAgentChat函数里面了，导致不输出结果。同样openai的虽然写了插件原生调用的代码，但是执行插件调用的时候，还是执行到了toolAgentChat函数里面。

**Comment by laxfer** [comment]
> > 修复了，试试看吧。
> 
> 感谢感谢辛苦了,插件按钮是不能点亮的,否则还是会出现,这个是预期内的不

最新版是有这个问题，@Hk-Gosuto 这个版本对插件原生支持这块改的不彻底，自己熟悉源码的话，可以改下，让插件执行的时候不调用toolAgentChat即可。

**Comment by Hk-Gosuto** [comment]
今天晚些我再修改一下，之前同步上游代码的时候做了一些兼容处理，应该是处理的有些问题。

**Comment by Hk-Gosuto** [comment]
已修复，同时增加了几个新的 claude 3.5 模型的函数调用。

**Comment by laxfer** [comment]
> 已修复，同时增加了几个新的 claude 3.5 模型的函数调用。

看了你同步主版本的插件原生调用代码，toolAgentChat函数可以去掉了，也能跑起来，但是完全去掉，RAG功能就不行了。

**Comment by Hk-Gosuto** [comment]
> > 已修复，同时增加了几个新的 claude 3.5 模型的函数调用。
> 
> 看了你同步主版本的插件原生调用代码，toolAgentChat函数可以去掉了，也能跑起来，但是完全去掉，RAG功能就不行了。

主分支用的原生 API 插件调用的方式实现的，我这里是基于 langchian 的实现，目前还不能兼容，我再考虑后面移除 langchian 部分的函数调用并保留已有的插件。
