### ISSUE TITLE
[Feature Request] 优化模型选择的交互

### ISSUE THREAD

**Issue by code-october** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#326]
### 🥰 需求描述

模型 Selector 的搜索框很方便，但它不是默认聚焦的，导致需要额外添加一个点击动作，可以做成点开模型 Selector 后自动聚焦到搜索框上，键盘无缝输入

### 🧐 解决方案

如图，给 ui.lib.tsx 添加如下聚焦代码即可：
```
  const inputRef = useRef<HTMLInputElement>(null);

  // 当组件加载时自动聚焦到输入框
  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.focus();
    }
  }, []);
```

![image](https://github.com/user-attachments/assets/18d085d4-d910-4569-bbcd-d035675c9490)

### 📝 补充信息

(ps. 为什么不通过 pr 方式提交呢，因为我发现我两个号都 fork 过原版 nextweb，导致无法再 fork 当前项目，又实在懒得再开新号了，见谅)

**Comment by Hk-Gosuto** [comment]
方便的话可以提个 pr 过来
