### ISSUE TITLE
联网访问网页对外API提供内容

### ISSUE THREAD

**Issue by tanlentboy** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#33]
作者你好， 你增加的浏览网页的这插件非常棒，还有联网搜索。
请问能实现 目前的项目提供对外服务API吗？ 就是比如，提供个http://localhost:3000/api 我可以在外部post或者get 提交网页或者搜索内容过来，gpt分析和获取内容之后返回给我。 

之所以有这想法是因为 好像无法实现非插件的方式访问网页或者搜索。  

有尝试过爬取网页获取内容进行分析或者搜索，但是有的网址有反爬机制。但是 插件形式，基本上没有。

**Comment by Hk-Gosuto** [comment]
你调用 `/api/langchain/tool/agent` 就可以，不过你要处理返回的stream数据。
header 中要携带 Authorization 鉴权信息。
入参：
```json
{
    "messages": [       // 消息上下文
        {
            "role": "system",
            "content": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2023/9/23 10:17:48\n"
        },
        {
            "role": "user",
            "content": "帮我查一下上海明天的天气"
        }
    ],
    "stream": true,     // 是否为stream返回 这个参数现在并没有实际作用
    "model": "gpt-3.5-turbo",   // 使用的模型
    "temperature": 0.5,         // 模型参数
    "presence_penalty": 0,      // 模型参数
    "frequency_penalty": 0,     // 模型参数
    "top_p": 1,                 // 模型参数
    "baseUrl": "https://openai.xxx.xxx",       // 接口地址
    "maxIterations": 10,                    // 插件参数
    "returnIntermediateSteps": true,        // 插件参数
    "useTools": [                           // 本次请求可以调用的插件列表
        "web-search",
        "calculator",
        "web-browser",
        "WikipediaQueryRun"
    ]
}
```

**Comment by tanlentboy** [comment]
> 你调用 `/api/langchain/tool/agent` 就可以，不过你要处理返回的stream数据。 header 中要携带 Authorization 鉴权信息。 入参：
> 
> ```json
> {
>     "messages": [       // 消息上下文
>         {
>             "role": "system",
>             "content": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2023/9/23 10:17:48\n"
>         },
>         {
>             "role": "user",
>             "content": "帮我查一下上海明天的天气"
>         }
>     ],
>     "stream": true,     // 是否为stream返回 这个参数现在并没有实际作用
>     "model": "gpt-3.5-turbo",   // 使用的模型
>     "temperature": 0.5,         // 模型参数
>     "presence_penalty": 0,      // 模型参数
>     "frequency_penalty": 0,     // 模型参数
>     "top_p": 1,                 // 模型参数
>     "baseUrl": "https://openai.xxx.xxx",       // 接口地址
>     "maxIterations": 10,                    // 插件参数
>     "returnIntermediateSteps": true,        // 插件参数
>     "useTools": [                           // 本次请求可以调用的插件列表
>         "web-search",
>         "calculator",
>         "web-browser",
>         "WikipediaQueryRun"
>     ]
> }
> ```


谢谢   [Hk-Gosuto](https://github.com/Hk-Gosuto) 作者热心的帮助,测试成功,非常感谢.  简直太棒了.
