### ISSUE TITLE
本机Docker部署，如何让它走代理

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#35]
实在抱歉大佬，百度搜索有点不好用，想换回bing搜索，有时网络错误。我在想是不是one-api的问题，导致bing搜索不能用。现在想去掉one-api的base_url，换回openai官方的接口，但需要走代理。我使用下面命令创建容器。
```
docker run -d -p 8261:3000 \
	--name chatgpt \
	--restart always \
	-e https_proxy="http://192.168.1.4:7890" \
	-e CODE="eRelV54B" \
	-e BING_SEARCH_API_KEY="21ac9b" \
	-e R2_ACCOUNT_ID="1a2fb43cb45e" \
	-e R2_ACCESS_KEY_ID="dfd955" \
	-e R2_SECRET_ACCESS_KEY="c4d5" \
	-e R2_BUCKET="gpt" \
	gosuto/chatgpt-next-web-langchain:1.0.4
````
之后在设置里的API_Key填入OpenAI的key，不回复我。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/e9434cc8-c224-4cf8-84f8-8903ce41865f)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/7d116df2-b619-4efc-992d-89325dc75879)

**Comment by Hk-Gosuto** [comment]
目前所有插件是没办法单独配置代理的，最好的方式还是部署在境外vps或者vercel上。

**Comment by cui8** [comment]
> 目前所有插件是没办法单独配置代理的，最好的方式还是部署在境外vps或者vercel上。

谢谢大佬，看来只能这样才能使用bing搜索了。
