### ISSUE TITLE
调用不了DALL-E插件

### ISSUE THREAD

**Issue by 18838742239** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#36]
![mmexport1695550778052.png](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/123466464/c76eb3d7-1514-44d1-b48d-2af27809abd9)

![Screenshot_2023-09-24-18-17-53-989_com.mmbox.xbrowser.jpg](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/123466464/c6c3cb2e-58dd-4c70-8d35-0e276e7f770e)

**Comment by Hk-Gosuto** [comment]
检查你的key调用dall-e服务本身是否正常
