### ISSUE TITLE
好奇怪，部署好刚开始可以使用，但是过段时间不行了

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#37]
我现在把它部署到国外 vps 上了，但是还是过段时间就不能使用了，大佬知道怎么解决吗？如果大佬需要，我可以把我自己搭建的让大佬看下。

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/9f48543f-019e-4047-a2ce-42501ed66fbd)

**Comment by Hk-Gosuto** [comment]
需要提供详细的错误日志

**Comment by cui8** [comment]
> 需要提供详细的错误日志

非常抱歉，给大佬添麻烦了。
大佬，我把服务对外开放关闭了，现在只有自己使用，bing搜索没有任何问题了
