### ISSUE TITLE
[Bug] 使用DALL.E进行绘画时，出现图片未成功写入R2存储桶，图片无法显示

### ISSUE THREAD

**Issue by s181462537** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#39]
使用DALL.E进行绘画时，出现图片无法显示情况如下图
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/135143533/a1375b42-350e-4309-a6cd-5cf92c8e2f5f)
查看cloudflare中的R2中，没有出现新的图片，应该是未成功写入，尝试使用![](/api/file/xxx.png)来显示R2中已有的图片，图片能过正常显示出来。所以问题应该是出在不能成功将图片写入到R2，请问这要怎么解决？

**Comment by s181462537** [comment]
修改/api/file/xxx.png为已有的图片，是可以正常显示的

**Comment by Hk-Gosuto** [comment]
可以尝试按以下步骤检查：
1. R2 服务的 token 是否具有写入权限
2. 确认当前的 openai token 可以正常使用 dall-e 服务
3. 检查日志中的 dall-e 返回的图片 url 是否可以在你当前的网络环境正常访问

**Comment by s181462537** [comment]
1、R2的密钥权限设置的是管理员读和写；
2、能正常反回图片的url，说明能正常使用dall-e服务
3、反回的url路径是指向R2的，但R2中未正常写入图片
我的R2存储桶设为开放后，用那个公共url打开网页还是会显示无权访问，会不会是这个原因，R2存储桶并未成功开放权限，导致无法写入？是否还有什么设置被遗漏了呢

**Comment by Hk-Gosuto** [comment]
使用的是 openai 官方的接口和 key 么，还是其它的中转服务？

**Comment by s181462537** [comment]
使用的是GPT_API_free项目获得的免费api，接口是https://api.chatanywhere.com.cn

**Comment by Hk-Gosuto** [comment]
这个转发服务的免费版本并不支持 DALL-E 服务

https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file#%E7%89%B9%E7%82%B9

支持Models, Embedding, text-davinci, GPT-3.5-Turbo, GPT-3.5-Turbo-16K(免费版不支持), GPT-4(免费版不支持), **DALLE(免费版不支持)**, Whisper(免费版不支持)。（免费版就可以支持AutoGPT, gpt_academic, langchain等）

**Comment by s181462537** [comment]
原来如此，我没注意去看项目细节，非常感谢，我回头用官网api试试
