### ISSUE TITLE
使用DALL.E进行绘画时，出现一些问题

### ISSUE THREAD

**Issue by cui8** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#42]
无法激活插件作画
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/cd4a0612-05fa-4852-8bd2-4664b7b517ee)
作画提示饱和
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/081f5fa2-989a-4602-bba2-96e898493438)

试了很多次，只有一次成功。这个什么原因？看大佬以前解答，想问下大佬如何查看 OpenAI token 是否可以使用 dall-e？

**Comment by cui8** [comment]
大佬，无法画图，是因为我的账号没有积分了吗？需要购买？
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/70044239/bd40d635-9b39-41b8-9012-b91f2d0ccaf6)

**Comment by Hk-Gosuto** [comment]
使用 openai 官方服务的 api，不会消耗这边的积分，接口调用价格是 $0.020 / image。
看你的报错信息不像是 openai 接口返回的，如果使用了其他服务中转需要检查一下你的中转服务。
也可以直接尝试直接调用官方的 api 来测试 dall-e 的相关接口是否可用：https://platform.openai.com/docs/api-reference/images/create

**Comment by cui8** [comment]
> 使用 openai 官方服务的 api，不会消耗这边的积分，接口调用价格是 $0.020 / image。 看你的报错信息不像是 openai 接口返回的，如果使用了其他服务中转需要检查一下你的中转服务。 也可以直接尝试直接调用官方的 api 来测试 dall-e 的相关接口是否可用：https://platform.openai.com/docs/api-reference/images/create

谢谢大佬解答，真的麻烦大佬了。这个画图功能太帮了👍
