### ISSUE TITLE
使用cloudflare pages部署后，DALL插件无法调用

### ISSUE THREAD

**Issue by happychos** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#43]
部署在vercel上可以正常调用，最近不是vercel被墙了吗？所以按照ChatGPT-Next-Web的cloudflare部署教程进行了部署（
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/cloudflare-pages-en.md
其他插件都可以正常使用，唯独DALL插件无法使用，环境变量也添加了R2参数，R2没有文件写入，希望大神可以解决，谢谢！
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/139939316/74688aa8-3433-4762-90e2-b5125eb40f7f)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/139939316/aa4dc6cf-318f-475d-8174-924669b58a27)

**Comment by Hk-Gosuto** [comment]
vercel 被墙的问题可以尝试解析域名到 76.223.126.88，cf 的问题晚些我会去尝试复现一下。

**Comment by happychos** [comment]
@Hk-Gosuto 可能是设置生效需要时间吧，已经可以了，非常感谢!

**Comment by Hk-Gosuto** [comment]
这个问题应该是 cf 本身运行环境导致的，与该问题类似 https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1436。
暂时没有好的解决方案，我会先在文档中标注该问题。
我在部署期间还发现原项目新增的 webdav 相关功能的运行时配置还会导致部署失败，尽量不要使用 cf 来部署该项目吧。

**Comment by happychos** [comment]
@Hk-Gosuto 按照issues反馈的将app/api/cors/[...path]/route.ts最后一行改为export const runtime = 'edge';，可以正常部署最新的项目，webdav功能也有，我没试过能否正常使用，但插件除了DALL都是可以正常使用的，是不是和对route.ts的更改有关系呢，还有我是把R2参数和其他参数一样直接录入到cloudflare中pages部署的环境变量中，这样部署对吗？

**Comment by Hk-Gosuto** [comment]
> @Hk-Gosuto 我是按照nextweb issues反馈的将app/api/cors/[...path]/route.ts最后一行改为export const runtime = 'edge';，可以正常部署最新的项目，webdav功能也有，我没试过能否正常使用，但插件除了DALL都是可以正常使用的，是不是和对route.ts的更改有关系呢，还有我是把R2参数和其他参数一样直接录入到cloudflare中pages部署的环境变量中，这样部署对吗？

你的配置没有问题，报错是出现在 openai-node 这个包里，dall-e 插件是基于该库实现的。

**Comment by Hk-Gosuto** [comment]
我用 fetch 重写了 dall-e 插件，该问题应该解决了。
不过还是建议使用 vercel 或 docker 来进行部署，不保证以后增加的插件都可以只在 cf 环境下正常运行。

**Comment by happychos** [comment]
@Hk-Gosuto 已经部署成功了，多谢大佬！
