### ISSUE TITLE
[Bug] 开启插件后，搜索时出错

### ISSUE THREAD

**Issue by G-LJDS2022** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#45]
不开启插件，正常输出
![1696694459161](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/134282368/fa9ba896-f3ae-4021-a4b2-7e94e8363f3d)

开启插件后，无法搜索网络上的内容
![1696694502428](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/134282368/bfb5b924-9b10-42bb-aad9-a8aa64fb76c7)

注：配置了SERPAPI_API_KEY
![1696694746176](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/134282368/b8a980da-c26f-42e7-a139-1024397783fa)

**一些必要的信息**
 - 系统：windows 11
 - 浏览器： edge
 - 版本： 2.9.7
 - 部署方式：vercel部署

**Comment by G-LJDS2022** [comment]
> 你的 openai api 必须是 原生的 openai api key。 要能使用 func call 的那种。如果用的是chatgpt网页 token 那个是不行的。不支持，func call。 项目里用的LangChain 的方式实现自动调用合适的已启用插件的。需要模型的支持。原生的 openai api key 然后调用支持func call的模型才行，如模型gpt3.5 0613 然后配合api，和api接口地址.

第三方镜像的openai api不能使用插件？

**Comment by Hk-Gosuto** [comment]
> > 你的 openai api 必须是 原生的 openai api key。 要能使用 func call 的那种。如果用的是chatgpt网页 token 那个是不行的。不支持，func call。 项目里用的LangChain 的方式实现自动调用合适的已启用插件的。需要模型的支持。原生的 openai api key 然后调用支持func call的模型才行，如模型gpt3.5 0613 然后配合api，和api接口地址.
> 
> 第三方镜像的openai api不能使用插件？

本项目的插件调用是基于 openai 发布的微调模型实现的，不支持使用类似 Pandora 项目转发接口的插件调用。
参考：https://openai.com/blog/function-calling-and-other-api-updates

**Comment by Tzyito** [comment]
使用三方API没法调用插件吗？

**Comment by Hk-Gosuto** [comment]
> 使用三方API没法调用插件吗？

不是第三方的 api 不能调用插件，而是要看你的服务商接口是否支持插件调用的参数，比如 Pandora 这种项目是将 https://chat.openai.com 逆向后提供的 api 调用，这种就不支持插件调用的参数，必须是转发 https://api.openai.com 这种 openai 官方提供的接口的服务才可能支持插件调用，感兴趣的话可以看下 openai 的文档：https://platform.openai.com/docs/api-reference/chat/create

**Comment by Tzyito** [comment]
> > 使用三方API没法调用插件吗？
> 
> 不是第三方的 api 不能调用插件，而是要看你的服务商接口是否支持插件调用的参数，比如 Pandora 这种项目是将 https://chat.openai.com 逆向后提供的 api 调用，这种就不支持插件调用的参数，必须是转发 https://api.openai.com 这种 openai 官方提供的接口的服务才可能支持插件调用，感兴趣的话可以看下 openai 的文档：https://platform.openai.com/docs/api-reference/chat/create

但是如果服务商接口不能调用的话，界面上应该也会展示搜索的图标吗？还是说api不支持调用，那么vercel配置的环境变量也不能生效，界面也就看不到搜索的过程

**Comment by Hk-Gosuto** [comment]
> > > 使用三方API没法调用插件吗？
> > 
> > 
> > 不是第三方的 api 不能调用插件，而是要看你的服务商接口是否支持插件调用的参数，比如 Pandora 这种项目是将 https://chat.openai.com 逆向后提供的 api 调用，这种就不支持插件调用的参数，必须是转发 https://api.openai.com 这种 openai 官方提供的接口的服务才可能支持插件调用，感兴趣的话可以看下 openai 的文档：https://platform.openai.com/docs/api-reference/chat/create
> 
> 但是如果服务商接口不能调用的话，界面上应该也会展示搜索的图标吗？还是说api不支持调用，那么vercel配置的环境变量也不能生效，界面也就看不到搜索的过程

不会显示，使用哪个插件是由 GPT 自己选择的，包括传入的参数。
