### ISSUE TITLE
使用时偶尔报错{   "error": true,   "message": "Cannot read properties of undefined (reading '0')" }

### ISSUE THREAD

**Issue by happychos** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#47]
部署是和大佬同步的，部署在vercel,使用的是官方api和代理，十一假期后使用经常会出现报错，即使关闭插件功能也会报错。
报错提示内容：
{
  "error": true,
  "message": "Cannot read properties of undefined (reading '0')"
}
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/139939316/4be9fbba-b4d5-4084-b6e4-ff18e17931e9)

**Comment by Hk-Gosuto** [comment]
看起来像是 openai 接口返回的结果出现了 undefined 的对象或者属性，这个问题我倒是在调用 azure 的接口时见过。
你指的代理是使用了接口的中转服务？可能问题出在这里。

**Comment by Hk-Gosuto** [comment]
我在使用期间没有出现过你说的这个问题。
其实在关闭插件调用的情况下，接口调用跟原版并没有差异，可以部署一个原版项目试试有没有这个问题。

**Comment by MTDickens** [comment]
我的也有类似的问题。

如果关闭插件：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/47918604/3dde93ac-6ab8-4f17-91a2-a304f86657a5)

如果打开插件：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/47918604/815c4049-168e-42e7-957f-20af663b5041)
