### ISSUE TITLE
[Bug] wikipedia-api 查询时报错

### ISSUE THREAD

**Issue by MTDickens** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#50]
**Describe the bug**
wikipedia-api 进行递归查询的时候，如果层数过深（在本例中，超过 4 层），就会报错：

```json
{
  "error": true,
  "message": "[object Object]"
}
```

**To Reproduce**
1. 使用 Azure GPT4 2023-08-01-preview（OpenAI 官方的 GPT4 应该也一样）作为 GPT4 
2. 询问：Who is the 100th prime minister of japan

**Expected behavior**
回复：Fumio Kishida（岸田文雄）

**Screenshots**
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/47918604/fa930685-5ff4-4623-adea-471e816522c5)

**Comment by Hk-Gosuto** [comment]
使用 16k 模型试试
