### ISSUE TITLE
[Bug] 搜索插件配置为google时搜索不到内容，浏览器用的“谷歌上网助手”插件做的代理

### ISSUE THREAD

**Issue by chaishenAI** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#51]
浏览器用chrome+谷歌上网助手插件
![1698566154267](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/148876401/8a39091e-82f5-4cf4-ae8d-aa956a686ada)
![1698566389956](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/148876401/8b21bffb-67cf-44bf-8ba9-0ca452905871)

**Comment by Hk-Gosuto** [comment]
采用什么方式部署的？docker 还是 vercel？

**Comment by Hk-Gosuto** [comment]
其实你这种问题不太适合使用搜索引擎来检索，搜索引擎插件返回的内容只是标题和摘要，第一个错误应该是链接超时或者超出了上下文长度，建议使用16k模型来调用插件。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/5812f9f7-35ab-4e31-bd6e-2ceb14343e40)

**Comment by Hk-Gosuto** [comment]
谷歌的那个问题你使用入参去搜一下就知道了，也并没有你想要的内容
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/c566b204-0b3f-4d9a-91f5-4e52a7915bcf)

**Comment by Hk-Gosuto** [comment]
这个最好的解决方案是实现一个 arxiv api 插件。
