### ISSUE TITLE
[Bug] Calculator调用有时候会卡住一直算

### ISSUE THREAD

**Issue by QAbot-zh** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#52]
**Describe the bug**
 Calculator调用有时候会卡住一直算，出不来结果，如图：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/40236765/1020c50c-24c9-4444-85b9-c8618fbb658a)

**Comment by Hk-Gosuto** [comment]
调用的入参并不能正确解析，这个是模型的问题，这个插件也是langchain官方的可以参考源码：
