### ISSUE TITLE
[Feature] 可以尝试接入midjourney

### ISSUE THREAD

**Issue by mouxangithub** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#56]
**你想要什么功能或者有什么建议？**
可以尝试使用[midjourney-api](https://github.com/erictik/midjourney-api)接入到插件中，然后用midjourney来作图，sd需要专业知识和一台gpu服务器相对来说比较麻烦，但midjourney就有很多共享账号可以部署来玩玩

**有没有可以参考的同类竞品？**
类似[ChatGPT-Midjourney](https://github.com/Licoy/ChatGPT-Midjourney)，我看他源码也是用[midjourney-api](https://github.com/erictik/midjourney-api)去对接实现

**Comment by burugo** [comment]
也可以等dall-e 3的API，很快就能用上了

**Comment by Hk-Gosuto** [comment]
> 也可以等dall-e 3的API，很快就能用上了

最近版本已经将 dall-e 插件升级为 dall-e 3 模型调用了

**Comment by Hk-Gosuto** [comment]
midjourney 对接比较麻烦，还需要加一些特殊指令以及界面上的变动。
主要手边也没有服务用来开发测试，所以短时间应该不会接入。

**Comment by burugo** [comment]
> > 也可以等dall-e 3的API，很快就能用上了
> 
> 最近版本已经将 dall-e 插件升级为 dall-e 3 模型调用了

大佬给力  坐等发布，我是docker版用户
