### ISSUE TITLE
无法调用绘图插件

### ISSUE THREAD

**Issue by thiner** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#59]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我根据项目中已有的Stable Diffusion插件，写了一个Fooocus插件。但是在聊天中无法调用插件。实际上好像所有的插件都不能使用。
我使用的是本地部署的`Vicuna-13b-chat`模型。

**截图**
![AI Illustrator](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/1897227/68c6f62e-027f-4690-96bb-f5a99c9d7cb3)

**一些必要的信息**
 - 系统：Windows 10
 - 浏览器： Chrome
 - 版本：v2.9.9
 - 部署方式：Docker

**Comment by Hk-Gosuto** [comment]
检查你的插件是否存在于可调用的工具列表中 https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/c637826ebe111aae091dd229ce557e23e8207a2b/app/api/langchain/tool/agent/route.ts#L228C20-L228C20
以及确认开启了插件功能并查看接口请求为 /api/langchain/tool/agent

**Comment by thiner** [comment]
> 检查你的插件是否存在于可调用的工具列表中 https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/c637826ebe111aae091dd229ce557e23e8207a2b/app/api/langchain/tool/agent/route.ts#L228C20-L228C20 以及确认开启了插件功能并查看接口请求为 /api/langchain/tool/agent

已经开启了agent router
```typescript
const fooocusTool = new FooocusWrapper();
if (useTools.includes(fooocusTool.name)) tools.push(fooocusTool);
```
而且从下面的API请求截图来看，调用了/api/langchain/tool/agent， 并且useTool里有对应插件。但是我在后端的服务日志里没有发现这个API调用的日志。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/1897227/df92b734-888a-499b-b5e5-0af2aeb0ae8a)

**Comment by Hk-Gosuto** [comment]
你在调试的时候不需要加判断，不然需要在 https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/app/plugins/cn.ts 和 https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/app/plugins/en.ts 添加插件描述
可以修改为：
```typescript
const fooocusTool = new FooocusWrapper();
tools.push(fooocusTool);
```
你用的开源模型我不太清楚是否支持openai函数调用，可以看下我这段回复：
https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/issues/54#issuecomment-1794016843
