### ISSUE TITLE
[Bug] 无法回复问题

### ISSUE THREAD

**Issue by Cyrus-Reed** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#6]
在serpapi.com获取了Private API Key，配置了SERPAPI_API_KEY环境变量。
但是输入问题不能得到回复，一直显示加载中，切换模型不使用gpt-3.5-turbo-0613后就可以正常回复，但不能联网查询了。
<img width="666" alt="ct" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/134946188/c5565289-cd1b-4350-913c-432c80c783bf">

**Comment by Hk-Gosuto** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/7f62ba49-7feb-490b-89cf-cf1aab539100)

无法复现该问题，请尝试更新代码到最新或者检查网络是否可以正常访问到 serpapi，也可以尝试不配置 `SERPAPI_API_KEY` 使用 `duckduckgo` 作为网络检索插件。

**Comment by crypticatul** [comment]
I was also experiencing the same bug. And as rightly pointed out by @Hk-Gosuto , This has something to do with the SERP API. I removed SERP APKI Key from the env vars and the DuckDuckGo search started working. However, it works sometimes but sometimes it gets stucked like this:

<img width="725" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/88734298/3ac2f142-1780-43f5-ab1d-b3e9620c7f82">

Below is the snap of Console in Inspect Element if this can help

<img width="948" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/88734298/fcd1bb49-b338-4a19-9988-60754e0f916e">

**Comment by Hk-Gosuto** [comment]
> > ![image](https://user-images.githubusercontent.com/14031260/257061524-7f62ba49-7feb-490b-89cf-cf1aab539100.png)
> > 无法复现该问题，请尝试更新代码到最新或者检查网络是否可以正常访问到 serpapi，也可以尝试不配置 `SERPAPI_API_KEY` 使用 `duckduckgo` 作为网络检索插件。
> 
> 不配置 SERPAPI_API_KEY 也是这个样子，我的 BASE_URL 是 https://api.chatanywhere.cn ，是转发 api ，和这个有关系吗？

本项目暂时不支持配置 `BASE_URL`，主要是因为 [openai-node](https://github.com/openai/openai-node) 项目目前没支持，建议使用 vercel 部署一个试试。

**Comment by Hk-Gosuto** [comment]
> I was also experiencing the same bug. And as rightly pointed out by @Hk-Gosuto , This has something to do with the SERP API. I removed SERP APKI Key from the env vars and the DuckDuckGo search started working. However, it works sometimes but sometimes it gets stucked like this:
> 
> <img alt="image" width="725" src="https://user-images.githubusercontent.com/88734298/257070872-3ac2f142-1780-43f5-ab1d-b3e9620c7f82.png">
> Below is the snap of Console in Inspect Element if this can help
> 
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/88734298/257070941-fcd1bb49-b338-4a19-9988-60754e0f916e.png">

This problem is caused by the token being too long. You can try using the `gpt-3.5-turbo-16k-0613` model.
At the same time, I have made some adjustments to the two plugins, `duckduckgo` and `RequestsGetTool`, so that they will not call `RequestsGetTool` to retrieve webpage details during searches.

**Comment by mobing163** [comment]
您好，回答字数多尤其是使用搜索的时候，回答会截断，后一部分回答未输出显示，是什么原因呢？

**Comment by Hk-Gosuto** [comment]
> 您好，回答字数多尤其是使用搜索的时候，回答会截断，后一部分回答未输出显示，是什么原因呢？我尝试过，即使是gpt-3.5-turbo-16k-0613也是如此。

确实是一个偶发的问题，我在正常使用的时候也有遇到，但调试时重试了十几次也没再复现。
如果有可以必现该问题的 prompt 也可以发给我进行复现和修复。

**Comment by Hk-Gosuto** [comment]
> 您好，回答字数多尤其是使用搜索的时候，回答会截断，后一部分回答未输出显示，是什么原因呢？我尝试过，即使是gpt-3.5-turbo-16k-0613也是如此。

我找到了这个问题的原因，由于现在 `duckduckgo` 插件是基于 `duck-duck-scrape` 包实现的，而该包依赖一些 nodejs 核心函数。所以上次更新时我将 agent 的 api 运行时修改为了 nodejs，而 vercel hobby 订阅的账号对 nodejs 的函数有运行时间限制导致当回复时间超过10秒时会被强制终止。
可以使用 docker 部署来规避这个问题，或者等待后续更新解决。

参考：https://vercel.com/guides/what-can-i-do-about-vercel-serverless-functions-timing-out

**Comment by Hk-Gosuto** [comment]
> 弱弱的问一句，联网功能，模型目前只支持 gpt-3.5-turbo-0613 吗？gpt-4 是否支持呢？

目前插件功能是基于 OpenAI 的 0613 版本模型的 Function calling 功能实现的，所有 OpenAI 的 0613 版本模型（包括：gpt-4-0613 gpt-4-32k-0613 gpt-3.5-turbo-0613 等等）均支持该功能。
后面会使用 LangChain 的其它类型 Agent 来实现非 0613 模型的插件调用，不过考虑到效果和 Token 消耗，还是推荐使用 0613 版本模型来使用插件。

可以参考该文章：https://openai.com/blog/function-calling-and-other-api-updates

**Comment by Hk-Gosuto** [comment]
相关问题均已解决，请更新代码到最新。
