### ISSUE TITLE
想问个新手问题 

### ISSUE THREAD

**Issue by superen7527** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#62]
说说我的情况：原项目那边过来的，看到有插件就重新部署的这个。但是没有很明确的教程用法，已经跟着文档有的地方能申请的都申请放进环境变量，然后还是只能用普通对话，无法触发插件。

然后又测试琢磨好久用不了，我就分析原因：

我一开始以为这个是先通过gpt分析语义然后进一步根据关键词自动执行插件，毕竟是langchain嘛应该有分析能力，一直不行跟着文档一样一起问也不行，我才想：这个是不是用的是官方接口，对接的是官方的plus账号才能用的插件，就是需要api4的接口？而且我想着dalle官网是只有4才有权限能用，这个项目填了cf就能用连api都不需要，应该不是因为dalle是免费公开接口，而是通过key来申请对接的，cf只是转存资源反代链接。就更证实了这个想法。

不知道是不是这样，而且我没国外信用卡，用的是搭建的对话转api模拟api，正常聊天可以和3.5一样，如果是根据返回的语义实现的，那么应该没问题才对。可是看到文档说除了两个模型其他又都支持插件我又奇怪了，这么说就是3.5的api也能用这个插件，官网不是不支持吗。那就是说要不api有额外的使用接口，要不就是我这个模拟的api实际上接口还是不全。不过我没有办法弄到key测试了。只能猜想论证，又和上面的想法冲突了，如果3.5key能用dalle，那为什么还要plus会员才能用。又死循环了。

我看issue结果好像都是资深使用的大佬问题，不好意思开issue打扰，怕太低级了。大家都会用就我不会是不是哪里遗漏了。然后自己又花了两天把项目看来看去。重新搞(除了搜索api看了要付费申请和收不到验证码以外想着vercel会反代就写的谷歌还有那个sd画图的项目全英文看不太懂没搭建以外其他都弄了)。看着看着又感觉和官方api没关系，搜索要搜索引擎key，画图要搭建sd，都不是依赖openai的。又绕回去感觉像是根据语义自动使用插件。

实在不知道咋回事了，才想着发一个issue吧，如果真的很没意义就直接关了吧。我也不是不花时间自己解决就问问题，实在是不玩这个圈子有点迷糊。如果有人能指点一下用法万分感激。如果觉得我这个问题很棘手或者要花比较多的时间，那就算了和我说一下我就用回原项目好了。

如果有打扰到大家实在抱歉。

**Comment by Hk-Gosuto** [comment]
项目使用的是 langchain agent 来实现的插件调用，可以参考这篇文档了解 [openai_functions_agent](https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent) ，核心还是用到了 openai 官方接口的 [function call](https://platform.openai.com/docs/guides/function-calling) 功能来实现的，这就导致需要你使用官方的 api 接口或者有一个支持 `function call` 的微调模型接口才能使用本项目的函数调用功能。

**Comment by superen7527** [comment]
感谢解答 终于解决了我的疑惑
