### ISSUE TITLE
[Feature] PDF（Text Document）Plugin

### ISSUE THREAD

**Issue by A2Sumie** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#68]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
目前这个项目有web-browser插件，不幸的是vercel访问一些学术网站似乎会吃限制（至少GPT是这么告诉我的）
There is a fine web-browser plugin in this project, but Vercel doesn't have access to certain academic sites (as shown).
<img width="891" alt="图片" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/89308692/0b58e861-b5bb-4fa4-9ca9-1deb76bd678b">
希望可以有一个PDF插件。似乎LangChain那有这样的模块。
I'm looking for a PDF plugin. Document(PDF) module seems to be somehow implemented in LangChain already.
**Describe alternatives you've considered**
一个把任何文本文件挂载到网页再通过web-broswer回读的方案？
Mounting any text(document) into a webpage accessible to Vercel and this project, and reading this webpage through the web-browser plugin.

**Additional context**

**Comment by Hk-Gosuto** [comment]
我在 langchain 文档中找到了这个 https://js.langchain.com/docs/integrations/document_loaders/web_loaders/pdf ，不确定是否可以用在 vercel 的 edge function 中。
其实单纯的实现这个功能并不难，不过在现在这种无状态服务的设计下可能会导致 token 大量浪费，因为每次请求都要重新将文档向量化并进行检索。

**Comment by A2Sumie** [comment]
> 我在 langchain 文档中找到了这个 https://js.langchain.com/docs/integrations/document_loaders/web_loaders/pdf ，不确定是否可以用在 vercel 的 edge function 中。 其实单纯的实现这个功能并不难，不过在现在这种无状态服务的设计下可能会导致 token 大量浪费，因为每次请求都要重新将文档向量化并进行检索。

如果不嫌麻烦的话我肯定是乐意用的，即使有些浪费
不过这个与web-broswer比（比如说，假如没有访问限制，web-browser直接检索对应的论文页面）会相对多用很多token吗

**Comment by Hk-Gosuto** [comment]
WebBrowser 插件内部也是使用 OpenAIEmbeddings 来对大量文本进行向量化后再检索，主要的消耗应该是在 Embedding models
上，费用可以参考：https://openai.com/pricing。
这是 WebBrowser 插件的实现代码：https://github.com/langchain-ai/langchainjs/blob/02ee2a0fa360b4ededaa51e956eda759f87ceb4c/langchain/src/tools/webbrowser.ts

**Comment by A2Sumie** [comment]
> WebBrowser 插件内部也是使用 OpenAIEmbeddings 来对大量文本进行向量化后再检索，主要的消耗应该是在 Embedding models 上，费用可以参考：[https://openai.com/pricing。](https://openai.com/pricing%E3%80%82) 这是 WebBrowser 插件的实现代码：https://github.com/langchain-ai/langchainjs/blob/02ee2a0fa360b4ededaa51e956eda759f87ceb4c/langchain/src/tools/webbrowser.ts

感谢。
看了下用量，消耗上感觉可以接受，我自己应该会很乐意去用。

**Comment by mouxangithub** [comment]
其实你可以试试用fastgpt或者[gpt_academic](https://github.com/binary-husky/gpt_academic)

**Comment by burugo** [comment]
如果要做的好，需要内置一个向量数据库来存储向量，使之可以复用

**Comment by Hk-Gosuto** [comment]
由于一些 vercel 限制这个插件只支持在非 vercel 环境下运行，如果使用 docker 部署，在下个版本发布前可以使用这个镜像：gosuto/chatgpt-next-web-langchain:20231129

**Comment by A2Sumie** [comment]
> 由于一些 vercel 限制这个插件只支持在非 vercel 环境下运行，如果使用 docker 部署，在下个版本发布前可以使用这个镜像：gosuto/chatgpt-next-web-langchain:20231129

十分感谢

**Comment by A2Sumie** [comment]
> gosuto/chatgpt-next-web-langchain:20231129

请问这个非vercel是怎么判定的
我自己手头立马能启用的linux设备只有个arm64的rk3568盒子，因为docker镜像不能用直接git clone+yarn这样弄的，现在pdf插件和vercel一样是不能勾选的状态

**Comment by Hk-Gosuto** [comment]
环境变量中增加：`NEXT_PUBLIC_ENABLE_NODEJS_PLUGIN=1`
