### ISSUE TITLE
[Bug] DALL-E 3 绘图 Bug

### ISSUE THREAD

**Issue by angping** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#69]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [X ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [X] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [X ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
通过Vercle部署，已配置Cloudflare R2 服务后，调用DALL-E 3依然提示Image upload to R2 storage failed，但是后台有账单记录。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
cloud flare R2截图
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/33945275/043b582d-e0e5-419d-bfd5-21ae37b6078f)
Vercle环境变量截图
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/33945275/07341790-987d-4207-9dad-d090422df8bd)
失败截图
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/33945275/60043a54-cd6e-4c32-8865-33fc14944348)

**Comment by Hk-Gosuto** [comment]
上传失败了，检查下vercel日志看下报错信息

**Comment by angping** [comment]
> 上传失败了，检查下vercel日志看下报错信息

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/33945275/4434e2aa-a415-41dd-b278-1cbd2267b02c)
没看到有报错信息

**Comment by angping** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> > The upload failed. Check the vercel log to see the error message.
> 
> ![image](https://private-user-images.githubusercontent.com/33945275/285627073-4434e2aa-a415-41dd-b278-1cbd2267b02c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NjkzNDIsIm5iZiI6MTcwMDk2OTA0MiwicGF0aCI6Ii8zMzk0NTI3NS8yODU2MjcwNzMtNDQzNGUyYWEtYTQxNS00MWRkLWIyNzgtMWNiZDIyNjdiMDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDAzMjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNTVhY2Q3ZWMyNTA2OGM2YTY0NTM1OTRkODU0YzY1MDY5NzU5ZWM0OTg5Nzc3ZDQ0NDg5YWY3MWQ0MDZhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.THRsNOU8Ck9Gudu19TVf3gQy7jQ25Jngq7asVU-yPFI) I didn’t see any error message

![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/33945275/708f6ee3-e94e-425d-b243-0b47f7a6059b)
补充一个上传失败的详细提示

**Comment by Hk-Gosuto** [comment]
在你的截图中没有看到详细的错误信息，可以检查一下 R2 存储的配置是否有误，我在主分支的代码上进行了尝试并没有复现该问题。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/d24036d1-f946-4034-a374-204eba5e7da8)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/4a990790-28b7-4229-82df-f981213bf6a9)

**Comment by angping** [comment]
大佬，我把项目fork到我的仓库后重新部署了一下就可以使用画图功能了，但是好像不能给出图片的seed，不能原图修改图片，是我使用方法不对吗？

**Comment by Hk-Gosuto** [comment]
dall-e 3 api 接口并没有提供 seed 参数选项，在返回中也没有该参数，如果以后 api 增加该参数我会进行适配。
参考：https://platform.openai.com/docs/api-reference/images/create
