### ISSUE TITLE
4.0模型不能调用默认搜素gpt-4和gpt-4-1106-preview都不行[Bug] 

### ISSUE THREAD

**Issue by sunsky89757** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#72]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by A2Sumie** [comment]
是不是插件没勾选啊，web-browser默认没勾，面板左侧弄一下

**Comment by Hk-Gosuto** [comment]
只有 gpt-4-vision-preview 不支持函数调用 https://platform.openai.com/docs/guides/function-calling/supported-models
我试了另外两个 gpt-4 的模型都没发现问题
请更新代码到最新版本后再次进行尝试，或者提供更多的信息帮助问题排查，如：使用了哪些插件，部署环境，错误信息的截图，日志等
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/8d0e2414-e800-4ed7-9b13-692e0b2a1c2f)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/795f720c-df91-4516-981d-b4a17fa70b71)

**Comment by h1xy** [comment]
确认是真正gpt4 api，如果是web转的是不行
