### ISSUE TITLE
环境变量的问题[Bug] 

### ISSUE THREAD

**Issue by surges567** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#73]
昨天花了几个小时排查，确定隐藏用户API密钥登入会报错：访问密码不正确，即在vercel的环境变量中，设置HIDE_USER_API_KEY的值为1
附图：
<img width="461" alt="屏幕截图 2023-12-01 120102" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/150920764/e1db66e6-e995-4b4d-893b-d4d233e359c5">
<img width="556" alt="屏幕截图 2023-12-01 120125" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/150920764/1eb8d1a4-07d4-4f02-9be4-733a94415f21">
另外，希望能支持控制模型列表的环境变量：CUSTOM_MODELS
因为常用的模型就两三个，模型全显示出来很麻烦

**Comment by Hk-Gosuto** [comment]
问题已经修复，如果仍然出现该问题请清除缓存后再进行尝试。
关于 CUSTOM_MODELS 参数可以参考我下面的写法，先删除所有的模型再添加要保留的：
```
CUSTOM_MODELS=-gpt-4,-gpt-4-0613,-gpt-4-32k,-gpt-4-32k-0613,-gpt-4-1106-preview,-gpt-4-vision-preview,-gpt-3.5-turbo,-gpt-3.5-turbo-0613,-gpt-3.5-turbo-1106,-gpt-3.5-turbo-16k,-gpt-3.5-turbo-16k-0613,gpt-3.5-turbo
```

**Comment by surges567** [comment]
非常感谢
也建议把自定义模型列表的环境变量写法写到readme里，因为写法和yda的有一点不同，比如删除所有模型是-all

**Comment by Hk-Gosuto** [comment]
> 非常感谢 也建议把自定义模型列表的环境变量写法写到readme里，因为写法和yda的有一点不同，比如删除所有模型是-all

是我漏看原版的说明了，理论上这部分应该跟原版功能一致才对，晚些我再跑下测试看看。

**Comment by Hk-Gosuto** [comment]
`CUSTOM_MODELS=-all` 是上游仓库后面更新的功能，目前主分支已经合并了上游仓库代码，该功能正常了。
