### ISSUE TITLE
选用gpt-3.5-turbo-1106模型，搜索时会出现乱码

### ISSUE THREAD

**Issue by s181462537** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#74]
![QQ截图20231202110741](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/135143533/a57b2a4c-fb6f-4f17-ad53-6b312204488f)
选用gpt-3.5-turbo-1106模型触发搜索时，就会出现乱码，若切换到其他模型，例如0613，就能正常搜索，之前的版本是能正常搜索的，更新后出现了乱码

**Comment by seopro1984** [comment]
我也遇到了。。

**Comment by seopro1984** [comment]
我研究了一下，似乎是转接接口的问题。。换个转接接口就好了。。

**Comment by s181462537** [comment]
原来是官方的问题，好吧，只能等了

**Comment by s181462537** [comment]
今天测试了一下，正常了，应该已修复
