### ISSUE TITLE
[Feature] 是否考虑支持文件上传功能

### ISSUE THREAD

**Issue by lialzm** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#77]
**Is your feature request related to a problem? Please describe.**

gpt4已经可以处理文件了,是否考虑将文件上传也添加进去

**Comment by Hk-Gosuto** [comment]
gpt-4-vision-preview？

**Comment by burugo** [comment]
> gpt-4-vision-preview？

麻烦大佬也更新下docker 镜像😂，支持图像上传

**Comment by Hk-Gosuto** [comment]
可以用这个版本的镜像：gosuto/chatgpt-next-web-langchain:20231206
有比较大的功能变更时我会手动打包一个日期为 tag 的镜像，如果想提前使用可以关注下
https://hub.docker.com/repository/docker/gosuto/chatgpt-next-web-langchain/tags?page=1&ordering=last_updated

**Comment by burugo** [comment]
<img width="535" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/1026635/39ac7545-fafe-4b88-8839-81c3a0b1f4c9">
发现bug，这个镜像识别图片可以，但是切换到其他模型正常输入文字发不出去，js报错
@Hk-Gosuto

**Comment by Hk-Gosuto** [comment]
> > <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/1026635/288627473-39ac7545-fafe-4b88-8839-81c3a0b1f4c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjM2NDAsIm5iZiI6MTcwMTkyMzM0MCwicGF0aCI6Ii8xMDI2NjM1LzI4ODYyNzQ3My0zOWFjNzU0NS1mYWZlLTRiODgtODgzOS04MWMzYTBiMWY0YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDQyOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY0MTgyOWRiZTc2ZjU2ZWExYjFkODhlNjZmZjJlZmMwMWUyZTkzOTk4Njg2MGYwMmJiNmU2ZGZhMDFjODU1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kyBKTmhMlsUIlbBtxYegxW0eRxcj6uDS5hesjebBMx8">
> > 发现bug，这个镜像识别图片可以，但是切换到其他模型正常输入文字发不出去，js报错 @Hk-Gosuto
> 
> 我记得昨天已经修复了，等会我再打个包。

使用 `gosuto/chatgpt-next-web-langchain:20231207`

**Comment by burugo** [comment]
感谢大佬，可以用了，很好很强大 👍

**Comment by iccyuan** [comment]
好像有个bug偶现,有时候调用接口没有传图片
操作步骤，先选择图片然后再输入文字

**Comment by burugo** [comment]
> 好像有个bug偶现,有时候调用接口没有传图片 操作步骤，先选择图片然后再输入文字

我发现是快捷键发送会重现，用鼠标点击发送就可以发

**Comment by lialzm** [comment]
> gpt-4-vision-preview？

是的,还有Whisper,挺多场景需要上传文件给到插件,然后插件处理的,另外想请教下vercel是直接实现文件的一些操作是不是限制很多呢,我尝试了下文件下载的很慢,大点文件就不行了

**Comment by Hk-Gosuto** [comment]
> > 好像有个bug偶现,有时候调用接口没有传图片 操作步骤，先选择图片然后再输入文字
> 
> 我发现是快捷键发送会重现，用鼠标点击发送就可以发

主分支修复了，docker镜像用这个：`gosuto/chatgpt-next-web-langchain:20231207-2`

**Comment by iccyuan** [comment]
<img width="1828" alt="image" src="https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/13375166/e176868e-73bc-4d7e-b594-e9d079f26f13">
现在方案看起来会超过存储限制

**Comment by burugo** [comment]
我看现在图片是base64的方案，如果上传到R2，使用图片url传到openai，应该还可以节省token费用？

**Comment by Hk-Gosuto** [comment]
> 我看现在图片是base64的方案，如果上传到R2，使用图片url传到openai，应该还可以节省token费用？

图片是根据像素单独计费的

**Comment by Hk-Gosuto** [comment]
> <img alt="image" width="1828" src="https://private-user-images.githubusercontent.com/13375166/288773588-e176868e-73bc-4d7e-b594-e9d079f26f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTg4MzMsIm5iZiI6MTcwMTk5ODUzMywicGF0aCI6Ii8xMzM3NTE2Ni8yODg3NzM1ODgtZTE3Njg2OGUtNzNiYy00ZDdlLWI1OTQtZTlkMDc5ZjI2ZjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxMjIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiOWNjYmVjMmE0OTM4OWM0NDE2YjZmNmM0ZjVjYjNiNTMwODA0ODM0ZWIzYTYzZGJjZjQ4OTg1YjFjYTkxMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l_I95zCN6HtIKTYjcUkav_IR4ZhLdEMZ3Fel1fUCfZM"> 现在方案看起来会超过存储限制

localStorage 最大是 5m 的容量，看来需要使用其它方案存储图像了。

**Comment by iccyuan** [comment]
> > <img alt="image" width="1828" src="https://private-user-images.githubusercontent.com/13375166/288773588-e176868e-73bc-4d7e-b594-e9d079f26f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTg4MzMsIm5iZiI6MTcwMTk5ODUzMywicGF0aCI6Ii8xMzM3NTE2Ni8yODg3NzM1ODgtZTE3Njg2OGUtNzNiYy00ZDdlLWI1OTQtZTlkMDc5ZjI2ZjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxMjIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiOWNjYmVjMmE0OTM4OWM0NDE2YjZmNmM0ZjVjYjNiNTMwODA0ODM0ZWIzYTYzZGJjZjQ4OTg1YjFjYTkxMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l_I95zCN6HtIKTYjcUkav_IR4ZhLdEMZ3Fel1fUCfZM"> 现在方案看起来会超过存储限制
> 
> localStorage 最大是 5m 的容量，看来需要使用其它方案存储图像了。

觉得这个还是有必要的，也方便PDF浏览器兼容更多格式

**Comment by Dhl9864** [comment]
@Hk-Gosuto 我也同样有这个错误，使用的是：gosuto/chatgpt-next-web-langchain:20231207 
“发现一个bug，这张图片可以识别图片，但是切换到其他模型时，输入文字无法正常发送，js报错”

**Comment by Hk-Gosuto** [comment]
> @Hk-Gosuto 我也同样有这个错误，使用的是：gosuto/chatgpt-next-web-langchain:20231207 “发现一个bug，这张图片可以识别图片，但是切换到其他模型时，输入文字无法正常发送，js报错”

gosuto/chatgpt-next-web-langchain:20231207-2

**Comment by EvilDD** [comment]
gpt-4-vision-preview 可以上传图片。请问是否支持多种日志文件上传的入口呢。

**Comment by Hk-Gosuto** [comment]
> gpt-4-vision-preview 可以上传图片。请问是否支持多种日志文件上传的入口呢。

视觉模型只能解析图片，上传日志之类的东西也没办法处理啊。还是说你想要的是 plus 账户的 Code Interpreter 功能？

**Comment by Hk-Gosuto** [comment]
> <img alt="image" width="1828" src="https://private-user-images.githubusercontent.com/13375166/288773588-e176868e-73bc-4d7e-b594-e9d079f26f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTQyNjcsIm5iZiI6MTcwMjIxMzk2NywicGF0aCI6Ii8xMzM3NTE2Ni8yODg3NzM1ODgtZTE3Njg2OGUtNzNiYy00ZDdlLWI1OTQtZTlkMDc5ZjI2ZjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEzMTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzI5M2I4OGU1MTIxZjE0ZDJhYzc2OTk2MDViNjNiOTE5YTdmMDZkMjhjMTBkYTg0OThkMjEyNTJmZTM4MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qd2VxZ662KcSPgN-xPqEwP0EonpwFwx-cruFfeFgrQA"> 现在方案看起来会超过存储限制

更新为使用对象存储来中转图像文件了，参考文档配置一下：[docs/s3-oss.md](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/blob/main/docs/s3-oss.md)
镜像：`gosuto/chatgpt-next-web-langchain:20231210`

**Comment by frontecho** [comment]
> > gpt-4-vision-preview 可以上传图片。请问是否支持多种日志文件上传的入口呢。
> 
> 视觉模型只能解析图片，上传日志之类的东西也没办法处理啊。还是说你想要的是 plus 账户的 Code Interpreter 功能？

可以考虑接入LangChain的Code Interpreter开源实现 https://github.com/shroominic/codeinterpreter-api

**Comment by Hk-Gosuto** [comment]
> > > gpt-4-vision-preview 可以上传图片。请问是否支持多种日志文件上传的入口呢。
> > 
> > 
> > 视觉模型只能解析图片，上传日志之类的东西也没办法处理啊。还是说你想要的是 plus 账户的 Code Interpreter 功能？
> 
> 可以考虑接入LangChain的Code Interpreter开源实现 https://github.com/shroominic/codeinterpreter-api

这个项目我之前有关注过，想支持要需要对这个项目进行改造，成本比较高，后面如果比较空闲的话会再研究下这个。
