### ISSUE TITLE
宝塔docker部署的项目，咋填插件的配置

### ISSUE THREAD

**Issue by suhou** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#82]
大佬，我想问我使用了宝塔docker部署了这个项目，如果我要使用dall插件就得配置文件，请问配置文件是哪一个，在宝塔如何配置

**Comment by Hk-Gosuto** [comment]
我看了一下宝塔创建容器那里有个创建环境变量的地方，那边应该是用来配置镜像一些启动参数的，你可以试试在那边添加 `-e 环境变量=变量值` 的形式来进行配置。
