### ISSUE TITLE
vercel配置了S3环境变量 ,使用S3 Browser 测试可以通过，但是使用dall-e-3插件画图时，仍然提示Image upload to R2 storage failed错误

### ISSUE THREAD

**Issue by suger404** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#85]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/101552636/a47de7a3-4cf2-46a6-a734-72d0c2cc835b)
![s3测试](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/101552636/887670fd-75e6-48f5-bc6f-c55d6a2eff1c)
已经测试可以上传图片

**Comment by Hk-Gosuto** [comment]
这个错误信息没有更新，你需要检查下程序中的错误日志，我刚在最新的主分支代码尝试了一下，并没有发现问题。

**Comment by suger404** [comment]
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/101552636/f3a1d75b-e253-4424-96ff-df5c84882bf0)
真的很奇怪，昨天晚上我的服务名叫chat-gpt-draw,就改了一个名字，现在没有问题了
