### ISSUE TITLE
关于搜索的优先级疑问

### ISSUE THREAD

**Issue by snakeying** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#86]
在readme中提及

支持使用 DuckDuckGo 作为默认搜索引擎

当前配置 SERPAPI_API_KEY 时优先使用 SerpAPI 作为搜索插件，不配置时默认使用 DuckDuckGo 作为搜索插件。

当前配置 BING_SEARCH_API_KEY 时优先使用 BingSerpAPI 作为搜索插件，不配置时默认使用 DuckDuckGo 作为搜索插件。

优先级：SerpAPI > BingSerpAPI > DuckDuckGo

以及

环境变量中

CHOOSE_SEARCH_ENGINE (可选)
此项为直连搜索引擎，免去api试用量小的烦恼，但可能因为网络问题导致无法使用

可选项如下：

google
baidu

假如我没有输入api，选择使用CHOOSE_SEARCH_ENGINE 的变量（google或者baidu），请问它们的优先级是？

**Comment by Hk-Gosuto** [comment]
> 在readme中提及
> 
> 支持使用 DuckDuckGo 作为默认搜索引擎
> 
> 当前配置 SERPAPI_API_KEY 时优先使用 SerpAPI 作为搜索插件，不配置时默认使用 DuckDuckGo 作为搜索插件。
> 
> 当前配置 BING_SEARCH_API_KEY 时优先使用 BingSerpAPI 作为搜索插件，不配置时默认使用 DuckDuckGo 作为搜索插件。
> 
> 优先级：SerpAPI > BingSerpAPI > DuckDuckGo
> 
> 以及
> 
> 环境变量中
> 
> CHOOSE_SEARCH_ENGINE (可选) 此项为直连搜索引擎，免去api试用量小的烦恼，但可能因为网络问题导致无法使用
> 
> 可选项如下：
> 
> google baidu
> 
> 假如我没有输入api，选择使用CHOOSE_SEARCH_ENGINE 的变量（google或者baidu），请问它们的优先级是？

SerpAPI > BingSerpAPI > CHOOSE_SEARCH_ENGINE > DuckDuckGo

**Comment by snakeying** [comment]
thanks~
