### ISSUE TITLE
上传图片功能在哪个版本，怎么开启

### ISSUE THREAD

**Issue by medoer** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#87]
你好，请问 readme 中第一张系统截图里的上传图片功能在哪个版本？怎么开启。用 gosuto/chatgpt-next-web-langchain 镜像启动没有。

**Comment by Hk-Gosuto** [comment]
对应版本为 v2.9.13 镜像还没推上去。
可以等几分钟在这里看镜像有没有推送上去：https://hub.docker.com/repository/docker/gosuto/chatgpt-next-web-langchain/tags?page=1&ordering=last_updated
切换模型为 `gpt-4-vision-preview` 时就有出现上传按钮。
