### ISSUE TITLE
[Feature] 令生成的图片在本地储存

### ISSUE THREAD

**Issue by PYCHBI** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#88]
我目前是在威联通NAS的docker里安装了gpt next web，使用的是第三方api中转站点的api key，能正常使用聊天功能。但是我看文档里说如果想要调用dalle3等图片相关的服务，必须配置OSS来长久存储图片，那么如果我想把生成的图片直接存到NAS里，有没有什么方法？（因为NAS空间很大，完全可以装下生成的图片，这样就不用另外买OSS了）
比如是否可以添加一个环境变量，来指定图片存储的路径？

**Comment by harukaxxxx** [comment]
從原 REPO 剛換過來，大力支持本地儲存配置，對於 Docker 佈署來說會非常非常有幫助！

**Comment by greatxin** [comment]
现阶段可以试试用minio搭一个s3，我测试下来有些问题，s3地址填域名，程序会访问{S3_BUCKET}.{S3_ENDPOINT}/{图片}，但使用ip地址就能正常访问{S3_ENDPOINT}/{S3_BUCKET}/{图片}，顺带gpt4v貌似没有识别到图像

**Comment by Hk-Gosuto** [comment]
> 现阶段可以试试用minio搭一个s3，我测试下来有些问题，s3地址填域名，程序会访问{S3_BUCKET}.{S3_ENDPOINT}/{图片}，但使用ip地址就能正常访问{S3_ENDPOINT}/{S3_BUCKET}/{图片}，顺带gpt4v貌似没有识别到图像

这个是 s3 协议本身的设计，当你的配置为域名时，会将 bucket 默认拼接到域名中，使用 ip 则会拼接到路由中。
图像识别的问题也修复了，可以更新到主分支最新版本试下。
