### ISSUE TITLE
[Feature] 支持 GoogleCustomSearch 插件

### ISSUE THREAD

**Issue by snakeying** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#89]
在vercel部署

当CHOOSE_SEARCH_ENGINE变量为baidu时候

![天气预报 (1)](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/65364563/7d6ca360-fea9-4be4-a924-13f485e95432)

![天气预报](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/65364563/8fe9e2b2-cb33-431e-a2a6-c6d58dc47431)

当不使用CHOOSE_SEARCH_ENGINE，默认DuckDuckGo时候则是正常的

![天气预报](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/65364563/77a8836c-2809-4573-a41d-40e5276ba3d2)
![新的聊天](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/65364563/98581bb7-55b1-44c8-813c-a88619409291)

**Comment by Hk-Gosuto** [comment]
我在本地调试的，并且输出了百度爬到的内容，并没发现问题，可能是网络原因导致的。
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/04ea8e46-e5b4-4c34-b5f5-a41e0c56d492)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/ad707940-9daa-4ca0-9390-d77eedc99f0b)

**Comment by snakeying** [comment]
调试反馈，使用docker本地部署的话确实没有问题，看来应该是vercel限制了？

**Comment by Hk-Gosuto** [comment]
可以在日志中把插件中的输出打印一下看看具体原因，也不好说是不是百度限制了vercel的ip访问。

**Comment by snakeying** [comment]
经过多次尝试，总结了一下搜索插件的情况

1.在vercel部署，不建议使用CHOOSE_SEARCH_ENGINE变量，因为baidu自动屏蔽vercel的IP导致返回302错误，google则表现不稳定，经常抽风

2.在私人服务器上部署（配合openwet passwall） 可以使用CHOOSE_SEARCH_ENGINE变量，无论是baidu还是google都可以，但搜索质量不敢恭维，还不如webchatgpt插件。

3.bing跟serp 的api搜索质量明显比直接使用搜索引擎要好，但严重受限，serp每月只有100条，bing每月1000条还有TPS限制。

建议加入Google Search Plugin，通过申请google的Custom Search JSON API，每天的查询数上限为 10,000 次。

https://developers.google.com/custom-search/v1/introduction?hl=zh-cn

**Comment by Hk-Gosuto** [comment]
> 经过多次尝试，总结了一下搜索插件的情况
> 
> 1.在vercel部署，不建议使用CHOOSE_SEARCH_ENGINE变量，因为baidu自动屏蔽vercel的IP导致返回302错误，google则表现不稳定，经常抽风
> 
> 2.在私人服务器上部署（配合openwet passwall） 可以使用CHOOSE_SEARCH_ENGINE变量，无论是baidu还是google都可以，但搜索质量不敢恭维，还不如webchatgpt插件。
> 
> 3.bing跟serp 的api搜索质量明显比直接使用搜索引擎要好，但严重受限，serp每月只有100条，bing每月1000条还有TPS限制。
> 
> 建议加入Google Search Plugin，需要获取谷歌自定义搜索 API 密钥和谷歌自定义搜索引擎 ID，每天的查询数上限为 10,000 次。
> 
> 在env中需要加入
> 
> GOOGLE_API_KEY="XXXXXXXX" GOOGLE_CSE_ID="XXXXXXXXX"
> 
> 相关网址
> 
> https://developers.google.com/custom-search/docs/tutorial/creatingcse
> 
> https://developers.google.com/custom-search/v1/introduction?hl=zh-cn

vercel 下的 CHOOSE_SEARCH_ENGINE 配置确实不稳定，该插件是基于爬虫实现的，本身就存在很多不稳定性。
该问题我会在文档中进行标注。

**Comment by snakeying** [comment]
有考虑加入Google Search Plugin吗？σ^_^;

**Comment by Hk-Gosuto** [comment]
> 有考虑加入Google Search Plugin吗？σ^_^;

我看 langchain 有这个插件，我试试引入进来。

**Comment by snakeying** [comment]
那就拜托大佬了  ☆*:.｡. o(≧▽≦)o .｡.:*☆
