### ISSUE TITLE
[Feature]  建议增强上传功能

### ISSUE THREAD

**Issue by iccyuan** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#90]
1.识图模式只能选择图片其他模式可以选择文件
2.文件上传后可以把路径隐式传给插件，输入预览可以看到文件
3.通过Web浏览器和PDF浏览器对文件进行处理

**Comment by Hk-Gosuto** [comment]
1. 我不太理解上传文件的实际用处，gpt模型除了图像并不能直接解析文件。
2. 同上
3. 是指第一条中的文件是可以上传PDF进行总结和询问？

还请提供更多的功能细节
