### ISSUE TITLE
[Question] Docker 构建时报错

### ISSUE THREAD

**Issue by Lavanille777** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#91]
使用 docker 构建时，类型检查出错，debug 的时候没有问题，请问如何解决呢

`46.19 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
48.15 Failed to compile.
48.15 
48.15 ./app/components/chat.tsx:673:11
48.15 Type error: Type 'import("/app/node_modules/langchain-core/dist/schema/messages").ChatMessage[]' is not assignable to type 'import("/app/app/store/chat").ChatMessage[]'.
48.15   Type 'import("/app/node_modules/langchain-core/dist/schema/messages").ChatMessage' is not assignable to type 'import("/app/app/store/chat").ChatMessage'.
48.15 
48.15   671 |         </List>
48.15   672 |         <ContextPrompts
48.15 > 673 |           context={messages}
48.15       |           ^
48.15   674 |           updateContext={(updater) => {
48.15   675 |             const newMessages = messages.slice();
48.15   676 |             updater(newMessages);
48.33 error Command failed with exit code 1.
48.33 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by Hk-Gosuto** [comment]
尝试一下将代码更新到最新后，在本地编译一次有没有问题：
```bash
git pull
yarn
yarn build
```
