### ISSUE TITLE
[Feature] 有没有考虑提供bard模型的支持？

### ISSUE THREAD

**Issue by brinkqiang** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#94]
目前bard Gemini pro已经可以使用了。测试下来还挺不错的。 并且没有其他模型那么多的限制。

**Comment by Hk-Gosuto** [comment]
当前函数调用是依赖于 openai api 的 function call，后面如果 langchain 提供了 Gemini 的函数调用模式可以考虑适配。

**Comment by brinkqiang** [comment]
[langchain 貌似已经加了支持。](https://github.com/langchain-ai/langchain/pull/14670)

**Comment by Hk-Gosuto** [comment]
我中午试了一下，目前 langchain 对 gemini 的支持有限，最近会考虑下使用其它方案先实现不包含函数调用的版本。

**Comment by lialzm** [comment]
> 我中午试了一下，目前 langchain 对 gemini 的支持有限，最近会考虑下使用其它方案先实现不包含函数调用的版本。

现在要是开启插件的情况下,调用类似claude-2的模型就会报错,可能需要添加个判断

**Comment by Hk-Gosuto** [comment]
参考 Gemini 模型的相关说明进行配置：https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain?tab=readme-ov-file#%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD
