### ISSUE TITLE
[Feature] 支持直接显示Azure Dalle3自带的图片链接

### ISSUE THREAD

**Issue by caippx** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#97]
因为Azure的Dalle3自带了一个可外网访问的临时图片链接
所以能否支持选择是上传到R2(S3)还是直接显示原有链接

**Comment by Hk-Gosuto** [comment]
配置环境变量 ` DALLE_NO_IMAGE_STORAGE=1`  即可直接返回 DALL-E 的临时图像链接
