### ISSUE TITLE
 Network connection lost.

### ISSUE THREAD

**Issue by lin-z-z** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#99]
- 部署方式：vercel
你好，我在调用DALL-E插件时，返回的图片接口为404，我使用的s3是minio，搭建在国内腾讯云的服务器上，看了桶中没有数据进入。
这是minio的截图，
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/75935186/fe164e0a-51ae-47b1-9e29-89edf7232b44)
这是报错的日志：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/75935186/fc933f42-4a23-453a-8621-a1fc487c204a)
这是配置的环境变量：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/75935186/93eac32e-cce5-4bdd-8a21-ef27378b3c5c)
错误截图：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/75935186/1981a560-52b2-4a3b-b019-76d45e6d3eab)
想请问下这是什么问题导致的呢

**Comment by Hk-Gosuto** [comment]
可以切换到视觉模型，上传一张图片来测试一下是否能正常上传图片到minio。

**Comment by Hk-Gosuto** [comment]
自建 minio 需要将 `S3_ENDPOINT` 配置为 ip:port 形式

**Comment by lin-z-z** [comment]
> 自建 minio 需要将 `S3_ENDPOINT` 配置为 ip:port 形式

是配置为ip:port的形式的
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/75935186/5740df64-d4f7-429f-be5f-370b6af2b316)

**Comment by Hk-Gosuto** [comment]
建议使用docker在本地跑一个，验证一下 vercel 访问 minio 时是否有网络问题。
